// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    [Migration("20240705081034_is-rented")]
    partial class isrented
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aef2904-4011-44cc-bdad-2fe00b5b43f3"),
                            ManufacturerId = new Guid("b89de499-e213-4fc5-a700-89382b2b4f5d"),
                            Name = "Escalade"
                        },
                        new
                        {
                            Id = new Guid("f0b82dae-0425-4b95-a5fe-826bc62d7e27"),
                            ManufacturerId = new Guid("b89de499-e213-4fc5-a700-89382b2b4f5d"),
                            Name = "Escalade"
                        },
                        new
                        {
                            Id = new Guid("3cec53a9-b6f3-42d9-b6f0-d40a11c478b2"),
                            ManufacturerId = new Guid("b89de499-e213-4fc5-a700-89382b2b4f5d"),
                            Name = "Silverado"
                        },
                        new
                        {
                            Id = new Guid("d766776c-7dac-475d-a50c-8f99fa7579f6"),
                            ManufacturerId = new Guid("b89de499-e213-4fc5-a700-89382b2b4f5d"),
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = new Guid("1e68205e-a045-4b11-94e7-b9795305f9ae"),
                            ManufacturerId = new Guid("b89de499-e213-4fc5-a700-89382b2b4f5d"),
                            Name = "Element"
                        },
                        new
                        {
                            Id = new Guid("540cf388-3096-4941-a651-a226fb287c8d"),
                            ManufacturerId = new Guid("2b321309-e057-4dd8-9a7d-9e0d254e6f37"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("4b524395-7112-4516-aeed-c4d268a68396"),
                            ManufacturerId = new Guid("2b321309-e057-4dd8-9a7d-9e0d254e6f37"),
                            Name = "XC90"
                        },
                        new
                        {
                            Id = new Guid("a10a9bb9-b8dd-4a8f-820f-5094520d4429"),
                            ManufacturerId = new Guid("2b321309-e057-4dd8-9a7d-9e0d254e6f37"),
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = new Guid("079aa0df-7c76-4e77-b1b6-6e9db5599059"),
                            ManufacturerId = new Guid("2b321309-e057-4dd8-9a7d-9e0d254e6f37"),
                            Name = "Volt"
                        },
                        new
                        {
                            Id = new Guid("874fa827-a393-46e1-ba9c-48ea40f01f8b"),
                            ManufacturerId = new Guid("2b321309-e057-4dd8-9a7d-9e0d254e6f37"),
                            Name = "Roadster"
                        },
                        new
                        {
                            Id = new Guid("c38f99d3-66d1-43e4-a9c9-c9f796d46b1d"),
                            ManufacturerId = new Guid("62973dfc-01b5-4642-9d6f-3e739bc1bd6c"),
                            Name = "ATS"
                        },
                        new
                        {
                            Id = new Guid("fd739c86-b73d-4763-8eb9-a0f56022f5d9"),
                            ManufacturerId = new Guid("62973dfc-01b5-4642-9d6f-3e739bc1bd6c"),
                            Name = "Jetta"
                        },
                        new
                        {
                            Id = new Guid("818d9a1e-338f-4704-bed7-3cd0f71b35d5"),
                            ManufacturerId = new Guid("62973dfc-01b5-4642-9d6f-3e739bc1bd6c"),
                            Name = "XTS"
                        },
                        new
                        {
                            Id = new Guid("a360ac28-660d-4819-97d2-8da1875e7907"),
                            ManufacturerId = new Guid("62973dfc-01b5-4642-9d6f-3e739bc1bd6c"),
                            Name = "Grand Cherokee"
                        },
                        new
                        {
                            Id = new Guid("9bb895b3-f778-411f-a977-afbd281e9172"),
                            ManufacturerId = new Guid("62973dfc-01b5-4642-9d6f-3e739bc1bd6c"),
                            Name = "Taurus"
                        },
                        new
                        {
                            Id = new Guid("40cc5e13-99b2-43c9-b86e-e5848ac2244f"),
                            ManufacturerId = new Guid("7336d067-baa3-4c19-867b-2c6e49b58c20"),
                            Name = "Charger"
                        },
                        new
                        {
                            Id = new Guid("bc868db3-207c-4ce8-8f72-a2c2943d7a67"),
                            ManufacturerId = new Guid("7336d067-baa3-4c19-867b-2c6e49b58c20"),
                            Name = "Accord"
                        },
                        new
                        {
                            Id = new Guid("1f80be54-f6ee-4e90-9511-7de71ee80554"),
                            ManufacturerId = new Guid("7336d067-baa3-4c19-867b-2c6e49b58c20"),
                            Name = "Escalade"
                        },
                        new
                        {
                            Id = new Guid("da2f8fba-e449-4c7a-b4ad-3b813b66ac83"),
                            ManufacturerId = new Guid("7336d067-baa3-4c19-867b-2c6e49b58c20"),
                            Name = "Charger"
                        },
                        new
                        {
                            Id = new Guid("b1ff8f2f-12ba-4c1c-98e6-a937620b39a4"),
                            ManufacturerId = new Guid("7336d067-baa3-4c19-867b-2c6e49b58c20"),
                            Name = "Mercielago"
                        },
                        new
                        {
                            Id = new Guid("8951d126-0ae4-4a04-9a59-cf5a0182741a"),
                            ManufacturerId = new Guid("64564c0a-f309-476f-80a0-2b41aeee6695"),
                            Name = "Model T"
                        },
                        new
                        {
                            Id = new Guid("115dc2d1-fb53-428e-8416-e97a2bee119c"),
                            ManufacturerId = new Guid("64564c0a-f309-476f-80a0-2b41aeee6695"),
                            Name = "El Camino"
                        },
                        new
                        {
                            Id = new Guid("2b85290f-9bcb-4091-af8a-28877ee939ab"),
                            ManufacturerId = new Guid("64564c0a-f309-476f-80a0-2b41aeee6695"),
                            Name = "Roadster"
                        },
                        new
                        {
                            Id = new Guid("a34a169c-02ca-47fb-8cd7-04138dbe5266"),
                            ManufacturerId = new Guid("64564c0a-f309-476f-80a0-2b41aeee6695"),
                            Name = "911"
                        },
                        new
                        {
                            Id = new Guid("66841042-23d8-4b53-8f18-d21ac4a30897"),
                            ManufacturerId = new Guid("64564c0a-f309-476f-80a0-2b41aeee6695"),
                            Name = "Element"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b89de499-e213-4fc5-a700-89382b2b4f5d"),
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = new Guid("2b321309-e057-4dd8-9a7d-9e0d254e6f37"),
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = new Guid("62973dfc-01b5-4642-9d6f-3e739bc1bd6c"),
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = new Guid("7336d067-baa3-4c19-867b-2c6e49b58c20"),
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = new Guid("64564c0a-f309-476f-80a0-2b41aeee6695"),
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("DAL.Entities.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRented")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Odo")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RentCost")
                        .HasColumnType("numeric");

                    b.Property<int>("VehicleState")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("783866cb-b69a-4d1b-a69d-3165d7fe12cd"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("5aef2904-4011-44cc-bdad-2fe00b5b43f3"),
                            Odo = 48,
                            PlateNumber = "BSF1L6NC21H761915",
                            RentCost = 669.91043184520900m,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("a7772a68-c19a-41c9-a029-7a9a450ca525"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("5aef2904-4011-44cc-bdad-2fe00b5b43f3"),
                            Odo = 1704,
                            PlateNumber = "VKQYDDT2PMWD42030",
                            RentCost = 3989.154671352199600m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("dd4db276-6ba3-41cd-be5f-ef6756b518a5"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("5aef2904-4011-44cc-bdad-2fe00b5b43f3"),
                            Odo = 9496,
                            PlateNumber = "XCOZR8X2W7Y461115",
                            RentCost = 1736.475563803034500m,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("97eb5374-f109-4d91-971a-e0a2d057e9fa"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("5aef2904-4011-44cc-bdad-2fe00b5b43f3"),
                            Odo = 7819,
                            PlateNumber = "71IJY3S3IBA324631",
                            RentCost = 2202.027501611833900m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("3865e756-b01b-4d30-85fb-7e009c4d0d96"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("5aef2904-4011-44cc-bdad-2fe00b5b43f3"),
                            Odo = 2398,
                            PlateNumber = "WP2468S0CKU360009",
                            RentCost = 3242.705167074023200m,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("543e729b-60b1-48c2-9c7c-2edcfd164787"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("f0b82dae-0425-4b95-a5fe-826bc62d7e27"),
                            Odo = 9998,
                            PlateNumber = "MQS9L3CUKEBO91368",
                            RentCost = 431.3687672481565600m,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("cdf10118-82dc-42c9-b994-9936c00754e9"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("f0b82dae-0425-4b95-a5fe-826bc62d7e27"),
                            Odo = 8418,
                            PlateNumber = "R3HNBHEZOMOV26640",
                            RentCost = 1167.485586753394900m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("0074ed41-b5f1-43a1-9ded-cf544e7f1382"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("f0b82dae-0425-4b95-a5fe-826bc62d7e27"),
                            Odo = 2581,
                            PlateNumber = "FSLACA3WKFMD20512",
                            RentCost = 1433.495962490227900m,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("572701e4-b08d-4091-aedd-2f17479b58ea"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("f0b82dae-0425-4b95-a5fe-826bc62d7e27"),
                            Odo = 4057,
                            PlateNumber = "8SDARFIMAQCV45728",
                            RentCost = 3708.548166965045200m,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("1bd2ef45-4f0c-4b6e-b5bc-df003cb53dff"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("f0b82dae-0425-4b95-a5fe-826bc62d7e27"),
                            Odo = 8682,
                            PlateNumber = "5FN9VCO4LAUQ55634",
                            RentCost = 1761.470475802352800m,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("4bc28e0e-8bca-4f33-a6b2-7b239db3ce50"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("3cec53a9-b6f3-42d9-b6f0-d40a11c478b2"),
                            Odo = 8242,
                            PlateNumber = "8B05ZIFMHGEO95046",
                            RentCost = 1994.005217088883600m,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("d9e4734c-4019-462a-8da4-4e95d364a30f"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("3cec53a9-b6f3-42d9-b6f0-d40a11c478b2"),
                            Odo = 3714,
                            PlateNumber = "UMVPD2T3O6F323437",
                            RentCost = 2043.418003216814800m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("d1d514d9-5bec-4c8f-a943-7e10287d1cb3"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("3cec53a9-b6f3-42d9-b6f0-d40a11c478b2"),
                            Odo = 8634,
                            PlateNumber = "19PPBLRPGYL696736",
                            RentCost = 213.3740351715162100m,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("6abb6e59-6b3c-4558-bf94-a05e2aa9ff03"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("3cec53a9-b6f3-42d9-b6f0-d40a11c478b2"),
                            Odo = 9714,
                            PlateNumber = "B00D2PV5F9SI20228",
                            RentCost = 248.3293568767484500m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("beaff452-e462-4eeb-8393-ee2e90eb8f50"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("3cec53a9-b6f3-42d9-b6f0-d40a11c478b2"),
                            Odo = 9207,
                            PlateNumber = "PAQPPKI6OQBV59666",
                            RentCost = 3239.666229534144700m,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("a10dba78-130e-4a44-98a3-a0167680a0ac"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("d766776c-7dac-475d-a50c-8f99fa7579f6"),
                            Odo = 3380,
                            PlateNumber = "DQ8OT7V3KUUO21283",
                            RentCost = 3088.566494135634100m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("661c7ce9-ea62-4ef5-9584-b05e100b89ef"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("d766776c-7dac-475d-a50c-8f99fa7579f6"),
                            Odo = 9812,
                            PlateNumber = "ODL8KSW0CER116571",
                            RentCost = 3644.708312865943600m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("9119fcb2-6cf3-44c7-80c8-654671bdf245"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("d766776c-7dac-475d-a50c-8f99fa7579f6"),
                            Odo = 3130,
                            PlateNumber = "XSVPOL6B00ZG98078",
                            RentCost = 1401.08329818305800m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("d0d31fd7-6c3f-4a4e-96d0-78acadf0d347"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("d766776c-7dac-475d-a50c-8f99fa7579f6"),
                            Odo = 9841,
                            PlateNumber = "WPCCMT48WZC531219",
                            RentCost = 1299.694315449662500m,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("909d195d-43d8-49f3-bce2-7d7e3b80da9c"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("d766776c-7dac-475d-a50c-8f99fa7579f6"),
                            Odo = 5215,
                            PlateNumber = "BPOGQV2REQO781206",
                            RentCost = 1954.986755879428600m,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("965291fb-3f77-4c4b-9adb-9c9554c6241e"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("1e68205e-a045-4b11-94e7-b9795305f9ae"),
                            Odo = 4026,
                            PlateNumber = "E5ZA7NI5JLTG24086",
                            RentCost = 3031.705227512534200m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("d49fc15a-76f2-41ce-b585-6041c71bada1"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("1e68205e-a045-4b11-94e7-b9795305f9ae"),
                            Odo = 4205,
                            PlateNumber = "ZIVJPM26IIJJ58174",
                            RentCost = 3213.071201064678100m,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("460b6ed2-06d2-4331-9765-eeaeac620fd6"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("1e68205e-a045-4b11-94e7-b9795305f9ae"),
                            Odo = 830,
                            PlateNumber = "WIHY8W6CB5D159189",
                            RentCost = 3940.897910369880100m,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("7d34c61a-90bf-4b78-85cc-fc85be15cb52"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("1e68205e-a045-4b11-94e7-b9795305f9ae"),
                            Odo = 6543,
                            PlateNumber = "NIG5SK2M5WCC28121",
                            RentCost = 1080.269426966724700m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("05c3337c-cdda-4df9-8a1a-bb58b055b126"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("1e68205e-a045-4b11-94e7-b9795305f9ae"),
                            Odo = 6799,
                            PlateNumber = "L0F9DUEGBKFJ58790",
                            RentCost = 3069.230475234657400m,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("54239a14-adc7-499c-b3d7-7fa081366b88"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("540cf388-3096-4941-a651-a226fb287c8d"),
                            Odo = 2499,
                            PlateNumber = "LMGCYST1WVRV21351",
                            RentCost = 3587.850841908620200m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("ca23a0bb-98d5-4dc5-bfcf-f4f607820818"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("540cf388-3096-4941-a651-a226fb287c8d"),
                            Odo = 9257,
                            PlateNumber = "0MYWEFY52LDN66958",
                            RentCost = 2227.571036753691100m,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("dc331a19-2c13-434f-925e-40586b80fa6d"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("540cf388-3096-4941-a651-a226fb287c8d"),
                            Odo = 4048,
                            PlateNumber = "WLFKOCRMQIIL23854",
                            RentCost = 656.014440151350700m,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("b1a24365-5930-4276-85da-674175c3c647"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("540cf388-3096-4941-a651-a226fb287c8d"),
                            Odo = 8121,
                            PlateNumber = "SL7YVIBGGEM594013",
                            RentCost = 3840.252939863997700m,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("1a649605-f7ab-4aaf-b06d-54fe54f47eae"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("540cf388-3096-4941-a651-a226fb287c8d"),
                            Odo = 5154,
                            PlateNumber = "UW88W68P3SDE38841",
                            RentCost = 2754.850338313443400m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f680c942-5ede-49fc-be0a-002a6f7070be"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("4b524395-7112-4516-aeed-c4d268a68396"),
                            Odo = 7280,
                            PlateNumber = "1SWXRABWAIX923781",
                            RentCost = 2672.705298156405100m,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("4cb8aa41-8878-4eaf-af6e-d9f0e2c11bc4"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("4b524395-7112-4516-aeed-c4d268a68396"),
                            Odo = 9789,
                            PlateNumber = "A8UT637VTSMG94911",
                            RentCost = 3243.701823986510800m,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("00ed94c7-5e4a-4177-8e65-d01c861a66d6"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("4b524395-7112-4516-aeed-c4d268a68396"),
                            Odo = 5575,
                            PlateNumber = "HK82XMGY6ERY55484",
                            RentCost = 2879.895803585024800m,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("7842a101-ae51-4938-b0d4-74f28badc71e"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("4b524395-7112-4516-aeed-c4d268a68396"),
                            Odo = 1055,
                            PlateNumber = "OBQI9SC4L2VM65825",
                            RentCost = 740.10234511709200m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("02ed95a4-27f4-4f2e-82ac-6a0cd4643229"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("4b524395-7112-4516-aeed-c4d268a68396"),
                            Odo = 8840,
                            PlateNumber = "2TAEN1HQT9RU64177",
                            RentCost = 3704.16621457344400m,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("e7f8c860-5483-40f9-b4c4-599afb473849"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("a10a9bb9-b8dd-4a8f-820f-5094520d4429"),
                            Odo = 8505,
                            PlateNumber = "OLK0HKHUILOZ51203",
                            RentCost = 793.829991314820100m,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("e2936981-c273-4b56-a3ea-629338a0cbf9"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("a10a9bb9-b8dd-4a8f-820f-5094520d4429"),
                            Odo = 9325,
                            PlateNumber = "XX4LA8QAMFZA43766",
                            RentCost = 2859.669174179569600m,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("9992137d-a4c0-4d1b-82af-5e157a697ff4"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("a10a9bb9-b8dd-4a8f-820f-5094520d4429"),
                            Odo = 4661,
                            PlateNumber = "4DEDX753XJL355568",
                            RentCost = 2933.821732603856800m,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("514769b8-59ac-4b1e-86c5-47a97db6971f"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("a10a9bb9-b8dd-4a8f-820f-5094520d4429"),
                            Odo = 4925,
                            PlateNumber = "KAC8U9AXIZEF22157",
                            RentCost = 1830.684746845837900m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("693b95c6-11a5-46c6-82f8-f2c829a0d86d"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("a10a9bb9-b8dd-4a8f-820f-5094520d4429"),
                            Odo = 4115,
                            PlateNumber = "0L06L02LP3I717213",
                            RentCost = 3925.007923998406600m,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("0b28e941-1209-44ae-9717-808995e500df"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("079aa0df-7c76-4e77-b1b6-6e9db5599059"),
                            Odo = 3688,
                            PlateNumber = "GTA8BSG1NNAH86654",
                            RentCost = 2583.550558141525600m,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("52f237c2-35d7-4f02-8cb6-325ab1f7168f"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("079aa0df-7c76-4e77-b1b6-6e9db5599059"),
                            Odo = 2760,
                            PlateNumber = "FICA98FDH8QU89641",
                            RentCost = 979.439906106119800m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("6748d90f-bfab-4bbe-93b0-15ac385367cd"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("079aa0df-7c76-4e77-b1b6-6e9db5599059"),
                            Odo = 7634,
                            PlateNumber = "ND21RWYN5MFY45620",
                            RentCost = 1175.555566063638400m,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("f833f24b-5274-4241-be63-da4a696a7328"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("079aa0df-7c76-4e77-b1b6-6e9db5599059"),
                            Odo = 4871,
                            PlateNumber = "WY5PX8ZVJ9J654988",
                            RentCost = 3526.367290933350400m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("2ef5df33-d03f-4048-a1ab-c23d85e2400e"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("079aa0df-7c76-4e77-b1b6-6e9db5599059"),
                            Odo = 5386,
                            PlateNumber = "1ZQ2VCZWKLH529997",
                            RentCost = 2494.379797511154700m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("fbde3658-1e75-491b-8ed3-0e7870eafcd4"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("874fa827-a393-46e1-ba9c-48ea40f01f8b"),
                            Odo = 3865,
                            PlateNumber = "B3IVVDJNFFH340027",
                            RentCost = 2659.340655195430600m,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("ad6337e6-5cd0-4b62-afe5-9974954be651"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("874fa827-a393-46e1-ba9c-48ea40f01f8b"),
                            Odo = 2389,
                            PlateNumber = "F3SC5KS1P0LC39578",
                            RentCost = 1165.270943203643800m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("d78544c6-24d9-459e-92f7-987ebdb01344"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("874fa827-a393-46e1-ba9c-48ea40f01f8b"),
                            Odo = 370,
                            PlateNumber = "HUPWPTK463VY96325",
                            RentCost = 1532.781871325416300m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("abf1e8fd-258c-4825-bf68-f6b00f6f0bbf"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("874fa827-a393-46e1-ba9c-48ea40f01f8b"),
                            Odo = 5397,
                            PlateNumber = "ITDUW8YFZ4ZO11248",
                            RentCost = 3807.825334083687700m,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("1fad1d94-ee6e-423b-a2d5-ee8181b6b9c6"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("874fa827-a393-46e1-ba9c-48ea40f01f8b"),
                            Odo = 8007,
                            PlateNumber = "CYL07YJOSBYL93118",
                            RentCost = 1607.49259742547700m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("68af71de-a593-4aa6-8c79-01a37c980a97"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("c38f99d3-66d1-43e4-a9c9-c9f796d46b1d"),
                            Odo = 8979,
                            PlateNumber = "K32B1MZTMFT813427",
                            RentCost = 488.7811073218727200m,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("0d0cf421-d5a8-4589-a5b6-a28a587b56fa"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("c38f99d3-66d1-43e4-a9c9-c9f796d46b1d"),
                            Odo = 4929,
                            PlateNumber = "TTID5UPHGREM33586",
                            RentCost = 2311.4143431491800m,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("a08bd175-0b08-471d-9e6f-703460e655d6"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("c38f99d3-66d1-43e4-a9c9-c9f796d46b1d"),
                            Odo = 2086,
                            PlateNumber = "R8VDZO4S81CH68086",
                            RentCost = 617.749631440705300m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("c8326bf4-b6c8-472d-abea-a6eea890e953"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("c38f99d3-66d1-43e4-a9c9-c9f796d46b1d"),
                            Odo = 7915,
                            PlateNumber = "LS6JVVXUY4U981307",
                            RentCost = 244.4695892496032800m,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("46e084d5-1e54-4b92-8483-9e181b0dac05"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("c38f99d3-66d1-43e4-a9c9-c9f796d46b1d"),
                            Odo = 1501,
                            PlateNumber = "VK7FC49CZQOA91789",
                            RentCost = 892.292638450374100m,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("5c622405-dc83-4ce2-83cd-d00a9f0a19d2"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("fd739c86-b73d-4763-8eb9-a0f56022f5d9"),
                            Odo = 4343,
                            PlateNumber = "EIQAGFU7VKP680372",
                            RentCost = 145.5615690566611900m,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("41ab7d63-7043-4d15-87a9-e721f3f28518"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("fd739c86-b73d-4763-8eb9-a0f56022f5d9"),
                            Odo = 2227,
                            PlateNumber = "1RZBUT27AWGR46827",
                            RentCost = 1231.725359750759800m,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a893a50c-11f4-4085-acec-9d9660a51fa5"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("fd739c86-b73d-4763-8eb9-a0f56022f5d9"),
                            Odo = 9625,
                            PlateNumber = "MZH8PF94YIU457132",
                            RentCost = 3554.694443559724300m,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("e7e1cc08-d962-4d30-a249-77fffdc05a9d"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("fd739c86-b73d-4763-8eb9-a0f56022f5d9"),
                            Odo = 3875,
                            PlateNumber = "ZI4B0V1ABUQ261807",
                            RentCost = 1519.195632932552800m,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("27730151-801c-4965-8718-1d1b19481071"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("fd739c86-b73d-4763-8eb9-a0f56022f5d9"),
                            Odo = 540,
                            PlateNumber = "WH07VJDPO0I732926",
                            RentCost = 3652.810876404840700m,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("aa0306ef-fbee-4142-8c35-6604a2585d3c"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("818d9a1e-338f-4704-bed7-3cd0f71b35d5"),
                            Odo = 4028,
                            PlateNumber = "N9F14ZTLH6RH65256",
                            RentCost = 2383.663231838446900m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("d919e753-9d28-4f53-a8a5-5d2533c0121a"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("818d9a1e-338f-4704-bed7-3cd0f71b35d5"),
                            Odo = 5628,
                            PlateNumber = "74TJSQT9EHX244722",
                            RentCost = 915.403424655656200m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("8e483215-2833-4ffc-9227-6e89893eed17"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("818d9a1e-338f-4704-bed7-3cd0f71b35d5"),
                            Odo = 4892,
                            PlateNumber = "4SNO4QFOC6SL46921",
                            RentCost = 2413.988176161188800m,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("e7691a25-e87e-4881-b1fb-7d775908195d"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("818d9a1e-338f-4704-bed7-3cd0f71b35d5"),
                            Odo = 8610,
                            PlateNumber = "U1OE97MVNZFH87240",
                            RentCost = 3102.598243415617600m,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("0551088a-ff60-4be0-9abc-691b2bd6af73"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("818d9a1e-338f-4704-bed7-3cd0f71b35d5"),
                            Odo = 8271,
                            PlateNumber = "MLIFUCH6WNO455117",
                            RentCost = 900.950177276949700m,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("a1d3b740-21ed-4366-b6aa-c4cefdfdadd0"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("a360ac28-660d-4819-97d2-8da1875e7907"),
                            Odo = 8794,
                            PlateNumber = "4ZZY50K2NYLC83062",
                            RentCost = 459.8684532581479900m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("fb65e3a7-cbf8-486c-a522-b53987ebb519"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("a360ac28-660d-4819-97d2-8da1875e7907"),
                            Odo = 1976,
                            PlateNumber = "IAYX6871OXGG71790",
                            RentCost = 2497.557311354572900m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("73997aa4-127e-42e9-a6be-95cb79b18250"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("a360ac28-660d-4819-97d2-8da1875e7907"),
                            Odo = 4955,
                            PlateNumber = "RKW3J5OJMUJM52806",
                            RentCost = 2662.144196611678900m,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a652e8fa-481c-42fb-b002-a1275f91a92d"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("a360ac28-660d-4819-97d2-8da1875e7907"),
                            Odo = 4046,
                            PlateNumber = "ECEOCA15YAX369775",
                            RentCost = 795.325666422676900m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("7836d28a-4f8b-4ce5-ba4a-644672bb64b4"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("a360ac28-660d-4819-97d2-8da1875e7907"),
                            Odo = 5185,
                            PlateNumber = "EETS125F9XYM19026",
                            RentCost = 3491.03265199909600m,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("18372838-2c64-40cf-8ad9-4cda4b234abd"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("9bb895b3-f778-411f-a977-afbd281e9172"),
                            Odo = 5372,
                            PlateNumber = "CV9RSVYPF3GH58179",
                            RentCost = 2119.243286360466400m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("7a244adf-6df1-4871-b2ee-f7e903c6dbb6"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("9bb895b3-f778-411f-a977-afbd281e9172"),
                            Odo = 6038,
                            PlateNumber = "EYVMQVSJI2VR51968",
                            RentCost = 280.8533573104254100m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("c841e52f-23f4-4d11-b19d-27ef507ab72d"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("9bb895b3-f778-411f-a977-afbd281e9172"),
                            Odo = 5879,
                            PlateNumber = "9A4OHYPIJJLR40401",
                            RentCost = 1087.269612873766300m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("fdbd469d-d452-457d-a93c-c49e27431bd7"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("9bb895b3-f778-411f-a977-afbd281e9172"),
                            Odo = 5128,
                            PlateNumber = "71BJGA2EY7DF38939",
                            RentCost = 2454.100391712413500m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("2098f8d0-4e54-4af1-8ea4-fda7e9e7142e"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("9bb895b3-f778-411f-a977-afbd281e9172"),
                            Odo = 9662,
                            PlateNumber = "GZZJM5WYX3T290315",
                            RentCost = 1091.179840656354700m,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("7ef2b46c-1654-4275-8ba8-b91a1f3aab49"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("40cc5e13-99b2-43c9-b86e-e5848ac2244f"),
                            Odo = 6337,
                            PlateNumber = "AGOUBA0XJUTE11961",
                            RentCost = 3386.125730606258800m,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("0500586f-cf1e-4139-b6f0-7a66cd0835fc"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("40cc5e13-99b2-43c9-b86e-e5848ac2244f"),
                            Odo = 1080,
                            PlateNumber = "CMFGEWI3HTKE71415",
                            RentCost = 3807.856708406191900m,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("04d5cc6c-9717-4331-aa49-a2d91b55cfca"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("40cc5e13-99b2-43c9-b86e-e5848ac2244f"),
                            Odo = 8428,
                            PlateNumber = "XXJ9JSH5YGT172291",
                            RentCost = 351.0837480363830800m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("7ba75e96-bda8-4607-afbe-a67ab67f3aa8"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("40cc5e13-99b2-43c9-b86e-e5848ac2244f"),
                            Odo = 9023,
                            PlateNumber = "5TIZSCC8BXEU53475",
                            RentCost = 706.099175185082800m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("201c1db3-7e6e-4611-899f-a3afb6a7434f"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("40cc5e13-99b2-43c9-b86e-e5848ac2244f"),
                            Odo = 3146,
                            PlateNumber = "5R8U7TRNXHCF37388",
                            RentCost = 3602.272945307917300m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("f31c62dd-9834-475e-8dc9-4124b7bee29e"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("bc868db3-207c-4ce8-8f72-a2c2943d7a67"),
                            Odo = 8429,
                            PlateNumber = "8FIVYBBJETHJ48508",
                            RentCost = 312.4024401171930400m,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("2a1a59a4-e8d0-4ea4-98c3-5b61ba4976d1"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("bc868db3-207c-4ce8-8f72-a2c2943d7a67"),
                            Odo = 7103,
                            PlateNumber = "4HV123QR31RQ99468",
                            RentCost = 356.2077187936454500m,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("0aabe96c-3e39-4872-8cc7-11e0710e32fb"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("bc868db3-207c-4ce8-8f72-a2c2943d7a67"),
                            Odo = 5049,
                            PlateNumber = "YC6ST3YHF4EH36937",
                            RentCost = 2737.877196093696700m,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("47fa4898-c709-4e77-a22c-642a635cf18c"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("bc868db3-207c-4ce8-8f72-a2c2943d7a67"),
                            Odo = 3234,
                            PlateNumber = "UT51MJNSDORF55126",
                            RentCost = 3227.470113487743400m,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("0646dc87-7a5e-4e26-8945-f44d17032165"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("bc868db3-207c-4ce8-8f72-a2c2943d7a67"),
                            Odo = 8477,
                            PlateNumber = "OEIVXL37LTIU14163",
                            RentCost = 249.6352825254695200m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("2753a419-2b39-40db-9641-d3b72f22ee1f"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("1f80be54-f6ee-4e90-9511-7de71ee80554"),
                            Odo = 1482,
                            PlateNumber = "NWII1YCW7TYW17460",
                            RentCost = 3242.851007856102400m,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("b469bb89-443a-4968-ba07-31f6ffc1931b"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("1f80be54-f6ee-4e90-9511-7de71ee80554"),
                            Odo = 1533,
                            PlateNumber = "9KW4P4YGTLGV61690",
                            RentCost = 2817.372189143774500m,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("7e67658d-396f-4d19-ba58-5e3a08c6e405"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("1f80be54-f6ee-4e90-9511-7de71ee80554"),
                            Odo = 7900,
                            PlateNumber = "1TGBUEV8KAKM50925",
                            RentCost = 1887.756040549628500m,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("63e14189-7cb3-4c26-a054-ed966db2111b"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("1f80be54-f6ee-4e90-9511-7de71ee80554"),
                            Odo = 5507,
                            PlateNumber = "01KX3NDL3AZ296660",
                            RentCost = 1388.542819077900100m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("4554f4a6-1e88-4568-b0ad-1ebcc686f4fc"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("1f80be54-f6ee-4e90-9511-7de71ee80554"),
                            Odo = 466,
                            PlateNumber = "WGX1FP34T6GR84853",
                            RentCost = 3151.171215933396400m,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("12308882-80db-4f17-8259-019666ca14f9"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("da2f8fba-e449-4c7a-b4ad-3b813b66ac83"),
                            Odo = 1157,
                            PlateNumber = "KWOMITB51AVG46419",
                            RentCost = 2862.866750642607700m,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("2183346d-f9ff-449f-9108-e69d8786474a"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("da2f8fba-e449-4c7a-b4ad-3b813b66ac83"),
                            Odo = 9626,
                            PlateNumber = "Q9D8XLTBDVS948210",
                            RentCost = 362.9386385940874300m,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6d0e1397-9e31-46a2-a751-ac320f93c920"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("da2f8fba-e449-4c7a-b4ad-3b813b66ac83"),
                            Odo = 3567,
                            PlateNumber = "HOWV940OLYPU52195",
                            RentCost = 1453.558596345498400m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("df06b71c-8821-4c61-b39d-7e0d31b4fba8"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("da2f8fba-e449-4c7a-b4ad-3b813b66ac83"),
                            Odo = 9005,
                            PlateNumber = "1ZO2J4HCUDAH40831",
                            RentCost = 848.580055479525100m,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("ef07de98-b3bf-4ada-975c-23373626e3d1"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("da2f8fba-e449-4c7a-b4ad-3b813b66ac83"),
                            Odo = 9578,
                            PlateNumber = "IZ0CBFC5CSI854787",
                            RentCost = 422.854278376789900m,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("e7b07e06-6ee9-4c83-9b0b-2bbf9e0f9e2d"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("b1ff8f2f-12ba-4c1c-98e6-a937620b39a4"),
                            Odo = 2802,
                            PlateNumber = "C1SQZFBOSRHB16507",
                            RentCost = 3560.04453520558300m,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("07ff6e5a-2176-4840-9c69-0333d5de2e46"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("b1ff8f2f-12ba-4c1c-98e6-a937620b39a4"),
                            Odo = 4023,
                            PlateNumber = "350219113HHA62540",
                            RentCost = 3774.639286874498800m,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("ea5d6418-e5c7-445c-a532-6e8753dfe434"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("b1ff8f2f-12ba-4c1c-98e6-a937620b39a4"),
                            Odo = 9891,
                            PlateNumber = "DUDMAKYB2VLY89390",
                            RentCost = 1170.262378060755100m,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c72805f9-e51d-47b1-8909-05bc4063d090"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("b1ff8f2f-12ba-4c1c-98e6-a937620b39a4"),
                            Odo = 3569,
                            PlateNumber = "TDMO7K6DQBLN24136",
                            RentCost = 1137.933257810983300m,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("62d392b0-afb8-4397-9771-8dfc27444e5a"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("b1ff8f2f-12ba-4c1c-98e6-a937620b39a4"),
                            Odo = 5909,
                            PlateNumber = "BZ9NNVZ0TRAF14503",
                            RentCost = 1571.479167524988700m,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("e2f9c83b-80ef-4eff-a409-85ddcfbbf76c"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("8951d126-0ae4-4a04-9a59-cf5a0182741a"),
                            Odo = 5293,
                            PlateNumber = "YRDMG6E10PD973269",
                            RentCost = 3699.02807503006300m,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("994a2a4c-dcd2-4721-8eed-6d0fd75029d8"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("8951d126-0ae4-4a04-9a59-cf5a0182741a"),
                            Odo = 6336,
                            PlateNumber = "474PEDNPI9GH14021",
                            RentCost = 2718.698583020926900m,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a520ec86-c12e-42db-9814-bc4ff2f524b0"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("8951d126-0ae4-4a04-9a59-cf5a0182741a"),
                            Odo = 8952,
                            PlateNumber = "ALBX9GXNUSNN89116",
                            RentCost = 2287.928360969189800m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("8d530439-7a54-4413-94e6-73c33d3bb40e"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("8951d126-0ae4-4a04-9a59-cf5a0182741a"),
                            Odo = 6916,
                            PlateNumber = "C3OFG1IWAIU298074",
                            RentCost = 2665.28374334724700m,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("d96a57f7-67b6-481f-86ec-0c06a139bcfd"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("8951d126-0ae4-4a04-9a59-cf5a0182741a"),
                            Odo = 7705,
                            PlateNumber = "N2OOIXWZWXUB79127",
                            RentCost = 3111.102154966024600m,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("a99d8758-b9a2-4216-b251-2cb2fefe14fb"),
                            FuelType = 3,
                            IsRented = true,
                            ModelId = new Guid("115dc2d1-fb53-428e-8416-e97a2bee119c"),
                            Odo = 8532,
                            PlateNumber = "NU9TQRSO9ATG40322",
                            RentCost = 2170.69943604487600m,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("e8306a4e-997b-47f5-a208-9775f8e796e4"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("115dc2d1-fb53-428e-8416-e97a2bee119c"),
                            Odo = 158,
                            PlateNumber = "F2UXEIQUA2JF92640",
                            RentCost = 3570.722258732411800m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("80f2b8d1-f244-43dc-a9d6-3359e1867238"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("115dc2d1-fb53-428e-8416-e97a2bee119c"),
                            Odo = 2509,
                            PlateNumber = "I3QXW6I9LHHY91061",
                            RentCost = 2047.667612348278600m,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("8bfb0768-2222-481f-8c2c-987f8e9dfb47"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("115dc2d1-fb53-428e-8416-e97a2bee119c"),
                            Odo = 572,
                            PlateNumber = "88ORYXBHWTA757884",
                            RentCost = 1576.975250852159500m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("d0c47779-49e6-4921-b505-79ce9bed996e"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("115dc2d1-fb53-428e-8416-e97a2bee119c"),
                            Odo = 6266,
                            PlateNumber = "DFECKLOHEADH50434",
                            RentCost = 1567.014620266994500m,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("5aaa99ed-eb22-4862-9839-a5d573ee690e"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("2b85290f-9bcb-4091-af8a-28877ee939ab"),
                            Odo = 898,
                            PlateNumber = "FYUAIA591RNZ53523",
                            RentCost = 3145.139713312106800m,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("2a8d3ba5-1d24-4382-865b-1889552f6fde"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("2b85290f-9bcb-4091-af8a-28877ee939ab"),
                            Odo = 5163,
                            PlateNumber = "O0VBRSCFV4PG51397",
                            RentCost = 830.798038693910200m,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("8c612899-aadf-441b-a1cf-5a32f16ac762"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("2b85290f-9bcb-4091-af8a-28877ee939ab"),
                            Odo = 6529,
                            PlateNumber = "TSSJ849TZRD538357",
                            RentCost = 573.884079992026600m,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("39bfcff8-1a74-4af0-8745-72b0657f9c7e"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("2b85290f-9bcb-4091-af8a-28877ee939ab"),
                            Odo = 8885,
                            PlateNumber = "2Y2QXSR3B2CL35991",
                            RentCost = 3005.383325709837700m,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("19c49823-9fad-4cda-be3f-1c48d5938f8a"),
                            FuelType = 0,
                            IsRented = true,
                            ModelId = new Guid("2b85290f-9bcb-4091-af8a-28877ee939ab"),
                            Odo = 102,
                            PlateNumber = "18E8TOLNTBJQ15025",
                            RentCost = 2995.670580373187500m,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("85a06530-e7e6-484a-85d9-95837348c7ea"),
                            FuelType = 0,
                            IsRented = false,
                            ModelId = new Guid("a34a169c-02ca-47fb-8cd7-04138dbe5266"),
                            Odo = 7629,
                            PlateNumber = "JO10TVJKRNTW89489",
                            RentCost = 2056.826803946739400m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a80409f7-84ae-486a-9021-c5e746b5a221"),
                            FuelType = 1,
                            IsRented = true,
                            ModelId = new Guid("a34a169c-02ca-47fb-8cd7-04138dbe5266"),
                            Odo = 6226,
                            PlateNumber = "WSVLL1R5RGK869416",
                            RentCost = 3238.181761641830800m,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("36781d0e-fe3f-452a-9099-d613309b7304"),
                            FuelType = 1,
                            IsRented = false,
                            ModelId = new Guid("a34a169c-02ca-47fb-8cd7-04138dbe5266"),
                            Odo = 7055,
                            PlateNumber = "E7N82D4GDVU599280",
                            RentCost = 3490.092791984653300m,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("7fcbc263-2991-4a08-9c9f-68b10743a1e4"),
                            FuelType = 3,
                            IsRented = false,
                            ModelId = new Guid("a34a169c-02ca-47fb-8cd7-04138dbe5266"),
                            Odo = 2182,
                            PlateNumber = "KT996CXCF5JL59374",
                            RentCost = 1800.250998492194200m,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("dff49dbe-7fda-40b3-bfda-e1a0ffcf88c2"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("a34a169c-02ca-47fb-8cd7-04138dbe5266"),
                            Odo = 1080,
                            PlateNumber = "KJAKQ3USMSOP79567",
                            RentCost = 2630.525219305002400m,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("3b39ccda-b425-4169-badc-297524379815"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("66841042-23d8-4b53-8f18-d21ac4a30897"),
                            Odo = 2049,
                            PlateNumber = "H4G60WC5OJI964492",
                            RentCost = 1648.703171017011100m,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("f03b9ec5-0052-4550-9998-d41cdd074baf"),
                            FuelType = 2,
                            IsRented = true,
                            ModelId = new Guid("66841042-23d8-4b53-8f18-d21ac4a30897"),
                            Odo = 9761,
                            PlateNumber = "5J2LO2RSIAI098355",
                            RentCost = 1972.426694939405800m,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("f56dafa5-484e-47d1-a4f3-0baa9ab6efe1"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("66841042-23d8-4b53-8f18-d21ac4a30897"),
                            Odo = 188,
                            PlateNumber = "TMPVBJ65NFW837391",
                            RentCost = 980.853801786130900m,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("7a9ef475-d665-4895-bb02-3867fe6c6d0a"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("66841042-23d8-4b53-8f18-d21ac4a30897"),
                            Odo = 4680,
                            PlateNumber = "JHNEOR66HRIR73762",
                            RentCost = 3347.597472881265400m,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("167f5359-200d-472c-baa2-2fb350846c15"),
                            FuelType = 2,
                            IsRented = false,
                            ModelId = new Guid("66841042-23d8-4b53-8f18-d21ac4a30897"),
                            Odo = 4554,
                            PlateNumber = "4VOCCR1V87ON42409",
                            RentCost = 781.986177410410600m,
                            VehicleState = 1,
                            VehicleType = 3
                        });
                });

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.HasOne("DAL.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("CarModels")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DAL.Entities.VehicleEntity", b =>
                {
                    b.HasOne("DAL.Entities.CarModelEntity", "CarModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("CarModelId");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("CarModels");
                });
#pragma warning restore 612, 618
        }
    }
}
