// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    [Migration("20240701092829_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63d7dc30-c83a-46cd-936b-254dc48173b4"),
                            ManufacturerId = new Guid("3d46b121-8c23-422a-b91c-4587f4f81e23"),
                            Name = "2"
                        },
                        new
                        {
                            Id = new Guid("a2e9ac92-8f98-467e-a128-ee5e8b04f7c8"),
                            ManufacturerId = new Guid("3d46b121-8c23-422a-b91c-4587f4f81e23"),
                            Name = "Altima"
                        },
                        new
                        {
                            Id = new Guid("e7eb530e-19cc-4ae9-8341-2961fea3a54c"),
                            ManufacturerId = new Guid("3d46b121-8c23-422a-b91c-4587f4f81e23"),
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = new Guid("c0f12b18-5b1c-486d-a622-709ad132b54a"),
                            ManufacturerId = new Guid("3d46b121-8c23-422a-b91c-4587f4f81e23"),
                            Name = "Corvette"
                        },
                        new
                        {
                            Id = new Guid("2a476438-4af4-4261-9696-8333b85da652"),
                            ManufacturerId = new Guid("3d46b121-8c23-422a-b91c-4587f4f81e23"),
                            Name = "Taurus"
                        },
                        new
                        {
                            Id = new Guid("bcd6b584-9e69-44ce-b51d-86da2b92c1ca"),
                            ManufacturerId = new Guid("63966981-4ee5-4504-a6c9-85fa38b7311e"),
                            Name = "Fortwo"
                        },
                        new
                        {
                            Id = new Guid("994248b5-f049-4012-8b89-ffe0ca5dde6a"),
                            ManufacturerId = new Guid("63966981-4ee5-4504-a6c9-85fa38b7311e"),
                            Name = "Beetle"
                        },
                        new
                        {
                            Id = new Guid("7f47c3ae-5071-462b-b02e-1365c7b96548"),
                            ManufacturerId = new Guid("63966981-4ee5-4504-a6c9-85fa38b7311e"),
                            Name = "Corvette"
                        },
                        new
                        {
                            Id = new Guid("89fb2363-5303-49b2-8241-31c0d0a57240"),
                            ManufacturerId = new Guid("63966981-4ee5-4504-a6c9-85fa38b7311e"),
                            Name = "Fiesta"
                        },
                        new
                        {
                            Id = new Guid("3ae5efb5-eefb-41bb-97fc-2df40a72c8f1"),
                            ManufacturerId = new Guid("63966981-4ee5-4504-a6c9-85fa38b7311e"),
                            Name = "Fiesta"
                        },
                        new
                        {
                            Id = new Guid("acdf47e3-f257-4989-8c09-04f610d0a197"),
                            ManufacturerId = new Guid("834d8097-c842-4d2e-ab0b-808ccb4352f9"),
                            Name = "Focus"
                        },
                        new
                        {
                            Id = new Guid("691d0d40-2f3b-43f1-b392-6bf66a3d874a"),
                            ManufacturerId = new Guid("834d8097-c842-4d2e-ab0b-808ccb4352f9"),
                            Name = "911"
                        },
                        new
                        {
                            Id = new Guid("bd6dc88f-be42-4b5f-bbe4-576771e0890b"),
                            ManufacturerId = new Guid("834d8097-c842-4d2e-ab0b-808ccb4352f9"),
                            Name = "A4"
                        },
                        new
                        {
                            Id = new Guid("a4203fc0-04fe-4dad-9659-145c7d5eb161"),
                            ManufacturerId = new Guid("834d8097-c842-4d2e-ab0b-808ccb4352f9"),
                            Name = "LeBaron"
                        },
                        new
                        {
                            Id = new Guid("e768ecab-0a8f-4246-a02d-dc9139d497dd"),
                            ManufacturerId = new Guid("834d8097-c842-4d2e-ab0b-808ccb4352f9"),
                            Name = "Element"
                        },
                        new
                        {
                            Id = new Guid("019f2d5e-c2c3-4e19-90d7-29b1e57ef74d"),
                            ManufacturerId = new Guid("39f75f2f-d37c-4a20-a6f6-11f4481caf9e"),
                            Name = "Charger"
                        },
                        new
                        {
                            Id = new Guid("774a072c-b689-41b3-aa0d-07d39b86c26d"),
                            ManufacturerId = new Guid("39f75f2f-d37c-4a20-a6f6-11f4481caf9e"),
                            Name = "V90"
                        },
                        new
                        {
                            Id = new Guid("bf80bd70-f83b-4f49-afea-63df41243d78"),
                            ManufacturerId = new Guid("39f75f2f-d37c-4a20-a6f6-11f4481caf9e"),
                            Name = "Element"
                        },
                        new
                        {
                            Id = new Guid("d8a70a3f-6c89-44a8-bed8-9ec5941808eb"),
                            ManufacturerId = new Guid("39f75f2f-d37c-4a20-a6f6-11f4481caf9e"),
                            Name = "ATS"
                        },
                        new
                        {
                            Id = new Guid("04c0fb3c-6a9d-4525-ae5c-0dda606c8442"),
                            ManufacturerId = new Guid("39f75f2f-d37c-4a20-a6f6-11f4481caf9e"),
                            Name = "Model T"
                        },
                        new
                        {
                            Id = new Guid("7f369d6d-3223-4e00-804e-29e7840396e6"),
                            ManufacturerId = new Guid("39c8cafb-e68d-4ed8-8657-59aa992be4d0"),
                            Name = "Civic"
                        },
                        new
                        {
                            Id = new Guid("39c8eb29-afa6-42a8-a75f-2473812a7e2c"),
                            ManufacturerId = new Guid("39c8cafb-e68d-4ed8-8657-59aa992be4d0"),
                            Name = "Civic"
                        },
                        new
                        {
                            Id = new Guid("99ad68d2-f7ac-406e-a7e1-5e53999b33fc"),
                            ManufacturerId = new Guid("39c8cafb-e68d-4ed8-8657-59aa992be4d0"),
                            Name = "Model 3"
                        },
                        new
                        {
                            Id = new Guid("aa3e71dc-c837-4988-8bb7-5e2566ba9b21"),
                            ManufacturerId = new Guid("39c8cafb-e68d-4ed8-8657-59aa992be4d0"),
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = new Guid("1ab2986f-184e-4c30-bba8-7ca6b68d4a63"),
                            ManufacturerId = new Guid("39c8cafb-e68d-4ed8-8657-59aa992be4d0"),
                            Name = "Civic"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d46b121-8c23-422a-b91c-4587f4f81e23"),
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = new Guid("63966981-4ee5-4504-a6c9-85fa38b7311e"),
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = new Guid("834d8097-c842-4d2e-ab0b-808ccb4352f9"),
                            Name = "Mini"
                        },
                        new
                        {
                            Id = new Guid("39f75f2f-d37c-4a20-a6f6-11f4481caf9e"),
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = new Guid("39c8cafb-e68d-4ed8-8657-59aa992be4d0"),
                            Name = "Jeep"
                        });
                });

            modelBuilder.Entity("DAL.Entities.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Odo")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RentCost")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleState")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e81301f-6864-46b1-8e7b-25ed4d31ba37"),
                            FuelType = 2,
                            ModelId = new Guid("63d7dc30-c83a-46cd-936b-254dc48173b4"),
                            Odo = 7657,
                            PlateNumber = "0SDCZW8TUJFM65143",
                            RentCost = 1832.7645954458892,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("259a8f1c-9f3f-4452-b2b2-4e5ca688bf23"),
                            FuelType = 0,
                            ModelId = new Guid("63d7dc30-c83a-46cd-936b-254dc48173b4"),
                            Odo = 416,
                            PlateNumber = "39439PQ4UJD227320",
                            RentCost = 2219.0411241110146,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("665bc1aa-8e16-418c-8a2e-0beaa61b0081"),
                            FuelType = 2,
                            ModelId = new Guid("63d7dc30-c83a-46cd-936b-254dc48173b4"),
                            Odo = 746,
                            PlateNumber = "VJY1HQARLKS918689",
                            RentCost = 799.86151923684463,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("9b1882de-4e39-46ee-a838-7c28ab4481db"),
                            FuelType = 2,
                            ModelId = new Guid("63d7dc30-c83a-46cd-936b-254dc48173b4"),
                            Odo = 3371,
                            PlateNumber = "86JTCNFPVQST78810",
                            RentCost = 3568.7460110709076,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a67fd14b-baed-48ea-9d23-c15263b9791a"),
                            FuelType = 1,
                            ModelId = new Guid("63d7dc30-c83a-46cd-936b-254dc48173b4"),
                            Odo = 2400,
                            PlateNumber = "T9HMJU8R2AIP16392",
                            RentCost = 2508.981634326949,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("0bb19c09-cc01-49e6-b34b-0cbe4708fb1d"),
                            FuelType = 3,
                            ModelId = new Guid("a2e9ac92-8f98-467e-a128-ee5e8b04f7c8"),
                            Odo = 5245,
                            PlateNumber = "7AXGXPD59TVM84651",
                            RentCost = 2248.6260663143644,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("78c8ec32-b1a1-4565-97d8-1b31ff0e01a7"),
                            FuelType = 3,
                            ModelId = new Guid("a2e9ac92-8f98-467e-a128-ee5e8b04f7c8"),
                            Odo = 9087,
                            PlateNumber = "XIYYTRQIOATU86749",
                            RentCost = 2430.8034404019936,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("525c95f1-73a4-4b4d-8033-22a34feb0e5d"),
                            FuelType = 0,
                            ModelId = new Guid("a2e9ac92-8f98-467e-a128-ee5e8b04f7c8"),
                            Odo = 1430,
                            PlateNumber = "9A9KJ5P26HO547511",
                            RentCost = 3851.6534067587404,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("e5815a7c-004e-4225-8875-2f0f299954b6"),
                            FuelType = 1,
                            ModelId = new Guid("a2e9ac92-8f98-467e-a128-ee5e8b04f7c8"),
                            Odo = 6444,
                            PlateNumber = "CWX2QQMJNHPY37450",
                            RentCost = 1957.2832640692322,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("cdc57dde-8e07-48a8-b4ef-88b6316bcd21"),
                            FuelType = 0,
                            ModelId = new Guid("a2e9ac92-8f98-467e-a128-ee5e8b04f7c8"),
                            Odo = 7907,
                            PlateNumber = "6I71NV856QNA67683",
                            RentCost = 3519.8810803289089,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("66ad8c44-eedc-449f-bfe8-4de1024b3416"),
                            FuelType = 1,
                            ModelId = new Guid("e7eb530e-19cc-4ae9-8341-2961fea3a54c"),
                            Odo = 6768,
                            PlateNumber = "KCV12DXJHIBI88813",
                            RentCost = 631.04756455962843,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("0b9f64c1-db1f-44ee-b62f-43e653b47e6a"),
                            FuelType = 2,
                            ModelId = new Guid("e7eb530e-19cc-4ae9-8341-2961fea3a54c"),
                            Odo = 9603,
                            PlateNumber = "2GX5LO2VA4G547209",
                            RentCost = 2804.9137369230375,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("322e6abf-80ac-401f-8f7f-39d9dd93ffff"),
                            FuelType = 2,
                            ModelId = new Guid("e7eb530e-19cc-4ae9-8341-2961fea3a54c"),
                            Odo = 9685,
                            PlateNumber = "DSBY9LI68UTK60415",
                            RentCost = 1149.8410951155297,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("439bac42-a7c4-456f-b07a-09fa674fd464"),
                            FuelType = 3,
                            ModelId = new Guid("e7eb530e-19cc-4ae9-8341-2961fea3a54c"),
                            Odo = 8855,
                            PlateNumber = "5PN2ZITFYYP726089",
                            RentCost = 3539.5426776786289,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("1a597447-676f-4e86-9c97-a375d85c631a"),
                            FuelType = 0,
                            ModelId = new Guid("e7eb530e-19cc-4ae9-8341-2961fea3a54c"),
                            Odo = 5822,
                            PlateNumber = "BTE3JB6GDVSM35069",
                            RentCost = 2149.9537746395604,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("d34a654d-4460-4f94-a89a-74093f717402"),
                            FuelType = 3,
                            ModelId = new Guid("c0f12b18-5b1c-486d-a622-709ad132b54a"),
                            Odo = 7423,
                            PlateNumber = "Y84CUP1462EY74734",
                            RentCost = 1657.4270350714235,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("77b07e70-faa4-43bd-921d-a08584c8c37f"),
                            FuelType = 1,
                            ModelId = new Guid("c0f12b18-5b1c-486d-a622-709ad132b54a"),
                            Odo = 6815,
                            PlateNumber = "2YB5V8TO15K653999",
                            RentCost = 2659.8492246889505,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("fc350745-93f5-45cc-bcf7-cf73e43a37ae"),
                            FuelType = 0,
                            ModelId = new Guid("c0f12b18-5b1c-486d-a622-709ad132b54a"),
                            Odo = 1091,
                            PlateNumber = "81N6P1HGELD357660",
                            RentCost = 717.16298833411668,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("d5981632-bd29-40e8-911f-834de9129eca"),
                            FuelType = 2,
                            ModelId = new Guid("c0f12b18-5b1c-486d-a622-709ad132b54a"),
                            Odo = 4961,
                            PlateNumber = "8B2EQI0FGER738415",
                            RentCost = 3500.7824176056793,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("861b30d3-3cba-4524-a670-84ff5d25496a"),
                            FuelType = 3,
                            ModelId = new Guid("c0f12b18-5b1c-486d-a622-709ad132b54a"),
                            Odo = 3345,
                            PlateNumber = "RR32QM9VGFSA16908",
                            RentCost = 125.65059507755127,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("094d76be-9791-42f5-ba92-5f2ca44aae62"),
                            FuelType = 3,
                            ModelId = new Guid("2a476438-4af4-4261-9696-8333b85da652"),
                            Odo = 8569,
                            PlateNumber = "L8HWXBBVG2NG35288",
                            RentCost = 316.02892140201965,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("266d0b20-6e74-40a5-983e-e8ae81d2516a"),
                            FuelType = 2,
                            ModelId = new Guid("2a476438-4af4-4261-9696-8333b85da652"),
                            Odo = 336,
                            PlateNumber = "OE2A95F4NNVO64884",
                            RentCost = 1293.7960302727647,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("7b479454-8e79-44ee-be4d-c1d9cba30a04"),
                            FuelType = 1,
                            ModelId = new Guid("2a476438-4af4-4261-9696-8333b85da652"),
                            Odo = 1474,
                            PlateNumber = "6C75TAEKO5PG55238",
                            RentCost = 1658.7860429636166,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f72b99be-81c3-48cb-9235-229b967c16bb"),
                            FuelType = 2,
                            ModelId = new Guid("2a476438-4af4-4261-9696-8333b85da652"),
                            Odo = 729,
                            PlateNumber = "J8HI5HM7VHTI41438",
                            RentCost = 1137.4082316726347,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("782af9c0-5a73-492d-8b42-53d2f0342f8a"),
                            FuelType = 0,
                            ModelId = new Guid("2a476438-4af4-4261-9696-8333b85da652"),
                            Odo = 2355,
                            PlateNumber = "M0HVTZ6L94UL67872",
                            RentCost = 2197.1961384791293,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("0714cac0-9dbc-46b9-ad82-515dd52649bc"),
                            FuelType = 0,
                            ModelId = new Guid("bcd6b584-9e69-44ce-b51d-86da2b92c1ca"),
                            Odo = 168,
                            PlateNumber = "RYZX0YQFBHPF98056",
                            RentCost = 3154.2724476414364,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("7670c96d-ba34-4a8e-bfb7-09d8610b878a"),
                            FuelType = 0,
                            ModelId = new Guid("bcd6b584-9e69-44ce-b51d-86da2b92c1ca"),
                            Odo = 8691,
                            PlateNumber = "O43QOS2ZDBB110540",
                            RentCost = 3929.2816685215444,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("870290ba-9223-4d8b-9e84-65478e892fa9"),
                            FuelType = 2,
                            ModelId = new Guid("bcd6b584-9e69-44ce-b51d-86da2b92c1ca"),
                            Odo = 7367,
                            PlateNumber = "HGC2H6E0N9LY53551",
                            RentCost = 3220.9115362807884,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("957521d0-7401-4a2e-9988-85423b69ca64"),
                            FuelType = 2,
                            ModelId = new Guid("bcd6b584-9e69-44ce-b51d-86da2b92c1ca"),
                            Odo = 8327,
                            PlateNumber = "9W693MR7Q1KH87915",
                            RentCost = 2069.5397979692834,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("0f365ed8-52b9-4dbf-9a4e-eedae555da99"),
                            FuelType = 1,
                            ModelId = new Guid("bcd6b584-9e69-44ce-b51d-86da2b92c1ca"),
                            Odo = 5690,
                            PlateNumber = "JJTSB9J7HPF522211",
                            RentCost = 721.43799092725931,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4f1373c8-c8c1-4a9d-a000-b4a976db8d14"),
                            FuelType = 1,
                            ModelId = new Guid("994248b5-f049-4012-8b89-ffe0ca5dde6a"),
                            Odo = 9002,
                            PlateNumber = "ZYP9OR5D3FF140184",
                            RentCost = 597.7792065729036,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("8c56e425-5033-4eb8-a7e2-d56e0c2ae112"),
                            FuelType = 0,
                            ModelId = new Guid("994248b5-f049-4012-8b89-ffe0ca5dde6a"),
                            Odo = 7444,
                            PlateNumber = "NJMA8RR1Z4YV77073",
                            RentCost = 571.8908835296761,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("cd83afe1-2070-4948-9f2c-2099548c553a"),
                            FuelType = 2,
                            ModelId = new Guid("994248b5-f049-4012-8b89-ffe0ca5dde6a"),
                            Odo = 2103,
                            PlateNumber = "SXRY1A1KWVLH28668",
                            RentCost = 1003.9630257530916,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("2fa3703c-5446-4807-a465-7b7ac56a17ce"),
                            FuelType = 1,
                            ModelId = new Guid("994248b5-f049-4012-8b89-ffe0ca5dde6a"),
                            Odo = 4455,
                            PlateNumber = "75CKZQGGFQOR42938",
                            RentCost = 631.62997194541015,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("098a7668-1db5-4b0e-8ed7-41a7e4a2548f"),
                            FuelType = 2,
                            ModelId = new Guid("994248b5-f049-4012-8b89-ffe0ca5dde6a"),
                            Odo = 6410,
                            PlateNumber = "UETYX5YAJBC647340",
                            RentCost = 2134.7948424322631,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("9ce84445-e620-4985-b66f-082d996a0bf6"),
                            FuelType = 2,
                            ModelId = new Guid("7f47c3ae-5071-462b-b02e-1365c7b96548"),
                            Odo = 1392,
                            PlateNumber = "AUN00RU49OMW39696",
                            RentCost = 2667.1972214047087,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("522cd41f-b55e-4733-8b70-2d01806caf80"),
                            FuelType = 3,
                            ModelId = new Guid("7f47c3ae-5071-462b-b02e-1365c7b96548"),
                            Odo = 6277,
                            PlateNumber = "MR2IOBI5CZO597363",
                            RentCost = 147.68023914709306,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("7eca6e37-7119-4316-be8e-b4b9c7492e51"),
                            FuelType = 2,
                            ModelId = new Guid("7f47c3ae-5071-462b-b02e-1365c7b96548"),
                            Odo = 7436,
                            PlateNumber = "LMIG9HJVKHVA39110",
                            RentCost = 3118.6541469942495,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("82ddf777-565f-4894-82e9-2453c3d9a069"),
                            FuelType = 0,
                            ModelId = new Guid("7f47c3ae-5071-462b-b02e-1365c7b96548"),
                            Odo = 3127,
                            PlateNumber = "TY5IECKRP2FT99488",
                            RentCost = 2124.4053556372796,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("04253b82-cfb7-4a46-90ac-c62285ed490a"),
                            FuelType = 2,
                            ModelId = new Guid("7f47c3ae-5071-462b-b02e-1365c7b96548"),
                            Odo = 9164,
                            PlateNumber = "LD2ZLRF3OFJC55704",
                            RentCost = 3685.6132850505442,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("28a01177-678f-46dc-81c7-896765670842"),
                            FuelType = 2,
                            ModelId = new Guid("89fb2363-5303-49b2-8241-31c0d0a57240"),
                            Odo = 4940,
                            PlateNumber = "TT3O80OG7OOP84084",
                            RentCost = 3498.1933967730861,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("2e24a90c-0fdd-450a-8848-42f1627362de"),
                            FuelType = 0,
                            ModelId = new Guid("89fb2363-5303-49b2-8241-31c0d0a57240"),
                            Odo = 3485,
                            PlateNumber = "ZLQV2GXCGXTN48487",
                            RentCost = 2176.3388443105109,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("3c5172e3-d23a-48f4-9329-8403fb761d5c"),
                            FuelType = 2,
                            ModelId = new Guid("89fb2363-5303-49b2-8241-31c0d0a57240"),
                            Odo = 9375,
                            PlateNumber = "T350MBK03TRS93929",
                            RentCost = 3666.555362110947,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("ae98ba44-92f3-435c-b41a-210e55bc6971"),
                            FuelType = 2,
                            ModelId = new Guid("89fb2363-5303-49b2-8241-31c0d0a57240"),
                            Odo = 5339,
                            PlateNumber = "P32ELO2LV5EV12511",
                            RentCost = 1149.209018070243,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("65219251-d587-463a-bb62-3c785c973113"),
                            FuelType = 0,
                            ModelId = new Guid("89fb2363-5303-49b2-8241-31c0d0a57240"),
                            Odo = 5179,
                            PlateNumber = "QNW5PSM013J185451",
                            RentCost = 3512.0141753789035,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("10c4b1cc-2d6c-466a-842f-31a548d81083"),
                            FuelType = 2,
                            ModelId = new Guid("3ae5efb5-eefb-41bb-97fc-2df40a72c8f1"),
                            Odo = 5919,
                            PlateNumber = "LC11QG93ITHQ62064",
                            RentCost = 425.03277661247535,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("2552ae63-a08e-4da0-b85a-eb5d6c05b3fc"),
                            FuelType = 2,
                            ModelId = new Guid("3ae5efb5-eefb-41bb-97fc-2df40a72c8f1"),
                            Odo = 5071,
                            PlateNumber = "EJ6KOO3Z3EVJ26833",
                            RentCost = 558.07146444239743,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("cc281cca-edc9-4387-9c04-cd3a1e68cb35"),
                            FuelType = 3,
                            ModelId = new Guid("3ae5efb5-eefb-41bb-97fc-2df40a72c8f1"),
                            Odo = 6565,
                            PlateNumber = "U8T6C53V9NRD84498",
                            RentCost = 3369.2808966330504,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("52181824-30ff-4356-94c2-2260f2149a5a"),
                            FuelType = 1,
                            ModelId = new Guid("3ae5efb5-eefb-41bb-97fc-2df40a72c8f1"),
                            Odo = 409,
                            PlateNumber = "9QPIENKKNNY382813",
                            RentCost = 193.14621809378423,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("4309d2e7-7441-429c-87c4-aba1573de495"),
                            FuelType = 1,
                            ModelId = new Guid("3ae5efb5-eefb-41bb-97fc-2df40a72c8f1"),
                            Odo = 4631,
                            PlateNumber = "UT141J834CPN99875",
                            RentCost = 234.34772455918545,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("122cfa83-018e-4014-9197-b13d352a27b6"),
                            FuelType = 0,
                            ModelId = new Guid("acdf47e3-f257-4989-8c09-04f610d0a197"),
                            Odo = 5450,
                            PlateNumber = "HRE7K8FIXHCY48518",
                            RentCost = 3042.7160417202972,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("60f73081-d083-4a0d-bca9-f63aef4322c1"),
                            FuelType = 3,
                            ModelId = new Guid("acdf47e3-f257-4989-8c09-04f610d0a197"),
                            Odo = 962,
                            PlateNumber = "I2KMJ0AGSMNG92957",
                            RentCost = 2091.5103273500117,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("a859a4eb-61ee-404a-9533-086e2da71677"),
                            FuelType = 3,
                            ModelId = new Guid("acdf47e3-f257-4989-8c09-04f610d0a197"),
                            Odo = 1275,
                            PlateNumber = "9MPPIXR26WY797092",
                            RentCost = 2555.4314260653732,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("c8567a38-3eac-4471-a310-47a2238ef5aa"),
                            FuelType = 2,
                            ModelId = new Guid("acdf47e3-f257-4989-8c09-04f610d0a197"),
                            Odo = 4477,
                            PlateNumber = "UCD0WXLWD7W517709",
                            RentCost = 2084.6526849290776,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("19fba074-eef5-429c-8d0e-e09ba96cce3f"),
                            FuelType = 0,
                            ModelId = new Guid("acdf47e3-f257-4989-8c09-04f610d0a197"),
                            Odo = 756,
                            PlateNumber = "D4UL0OT0IRA844159",
                            RentCost = 794.65311814367362,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("52d0791e-4037-4a87-a678-545fda1d51d4"),
                            FuelType = 1,
                            ModelId = new Guid("691d0d40-2f3b-43f1-b392-6bf66a3d874a"),
                            Odo = 9855,
                            PlateNumber = "85L02DGUISZB37382",
                            RentCost = 2623.3806476512023,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("d6637746-50d4-4f37-8892-ee316f82dca0"),
                            FuelType = 2,
                            ModelId = new Guid("691d0d40-2f3b-43f1-b392-6bf66a3d874a"),
                            Odo = 1834,
                            PlateNumber = "D9HG7XATCKSM62677",
                            RentCost = 1877.5188459015651,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("f75cb5d7-77d3-4c61-ae7a-206725c56214"),
                            FuelType = 2,
                            ModelId = new Guid("691d0d40-2f3b-43f1-b392-6bf66a3d874a"),
                            Odo = 3049,
                            PlateNumber = "GN1NY8YCLQOT51856",
                            RentCost = 1016.3833134121318,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6430e78b-f9b4-4d13-bc48-4f5403a99372"),
                            FuelType = 2,
                            ModelId = new Guid("691d0d40-2f3b-43f1-b392-6bf66a3d874a"),
                            Odo = 6786,
                            PlateNumber = "U1EALHOI2YU193384",
                            RentCost = 618.07103150944693,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("91f0bb11-3296-4ec3-a07c-7bcee7808340"),
                            FuelType = 0,
                            ModelId = new Guid("691d0d40-2f3b-43f1-b392-6bf66a3d874a"),
                            Odo = 3443,
                            PlateNumber = "5ZJR7FKQGVEH22486",
                            RentCost = 3873.2307881068082,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("1a1a09be-2807-4a49-8c1c-5a5c4ea52334"),
                            FuelType = 3,
                            ModelId = new Guid("bd6dc88f-be42-4b5f-bbe4-576771e0890b"),
                            Odo = 2750,
                            PlateNumber = "T3XWKHG7KKRF49758",
                            RentCost = 2764.537736016418,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("d9507274-7479-4778-9c81-6d5bb90ece5e"),
                            FuelType = 1,
                            ModelId = new Guid("bd6dc88f-be42-4b5f-bbe4-576771e0890b"),
                            Odo = 7949,
                            PlateNumber = "22CEC0WN1KND97541",
                            RentCost = 1657.0766130673831,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("702d5c3f-8510-4c2d-8643-808b785e2db9"),
                            FuelType = 2,
                            ModelId = new Guid("bd6dc88f-be42-4b5f-bbe4-576771e0890b"),
                            Odo = 6440,
                            PlateNumber = "XGNA94WQHMTF37202",
                            RentCost = 247.43957731608435,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("1835525d-70a0-43fe-8f7b-ad159a00843a"),
                            FuelType = 2,
                            ModelId = new Guid("bd6dc88f-be42-4b5f-bbe4-576771e0890b"),
                            Odo = 3434,
                            PlateNumber = "6OBDVQYSPQJ614665",
                            RentCost = 247.31339086741016,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("0361ba9c-642a-4372-961d-c4dce60941fb"),
                            FuelType = 0,
                            ModelId = new Guid("bd6dc88f-be42-4b5f-bbe4-576771e0890b"),
                            Odo = 2055,
                            PlateNumber = "IO8GBGWZHOZ468416",
                            RentCost = 222.11618833593624,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("3f7d0a0f-aa22-4d09-8c9c-2751b6a0dc6f"),
                            FuelType = 0,
                            ModelId = new Guid("a4203fc0-04fe-4dad-9659-145c7d5eb161"),
                            Odo = 6070,
                            PlateNumber = "QFFJC4CZ8TON65192",
                            RentCost = 3372.0124122874327,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("f9819970-5dac-4929-a724-6f206ea59797"),
                            FuelType = 3,
                            ModelId = new Guid("a4203fc0-04fe-4dad-9659-145c7d5eb161"),
                            Odo = 6036,
                            PlateNumber = "4VC3CUCE61RM72220",
                            RentCost = 3917.7873240705667,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("6d92a730-66f1-4efb-9d9a-4f771064176c"),
                            FuelType = 2,
                            ModelId = new Guid("a4203fc0-04fe-4dad-9659-145c7d5eb161"),
                            Odo = 8648,
                            PlateNumber = "73XX3FNED2S988361",
                            RentCost = 2182.7489922469044,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4b1396cc-94aa-47ff-a4a2-084fa5bd777c"),
                            FuelType = 2,
                            ModelId = new Guid("a4203fc0-04fe-4dad-9659-145c7d5eb161"),
                            Odo = 9484,
                            PlateNumber = "B2WEW73JZ5VG22866",
                            RentCost = 143.27656311992246,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("f4a82858-7dc5-4199-9a4b-151bd7bcce28"),
                            FuelType = 3,
                            ModelId = new Guid("a4203fc0-04fe-4dad-9659-145c7d5eb161"),
                            Odo = 1632,
                            PlateNumber = "CAJWAHP46YIB29330",
                            RentCost = 2264.912089788163,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("15d18e48-37c8-4307-9844-e51e3d16d117"),
                            FuelType = 1,
                            ModelId = new Guid("e768ecab-0a8f-4246-a02d-dc9139d497dd"),
                            Odo = 7774,
                            PlateNumber = "UQ53UR29E0N427237",
                            RentCost = 1428.9275258499633,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("3ae7f7b3-fd22-4ef5-a4f8-72311232d882"),
                            FuelType = 3,
                            ModelId = new Guid("e768ecab-0a8f-4246-a02d-dc9139d497dd"),
                            Odo = 9856,
                            PlateNumber = "IBJ9RDX75NED55803",
                            RentCost = 248.28463729510167,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("17b50b3d-5a1d-4e07-ba1a-b669473da0f3"),
                            FuelType = 1,
                            ModelId = new Guid("e768ecab-0a8f-4246-a02d-dc9139d497dd"),
                            Odo = 8085,
                            PlateNumber = "3DK2CSR4EDQR81719",
                            RentCost = 859.0505228475879,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("0efac801-e804-4c1c-a4ae-206aed05ba93"),
                            FuelType = 2,
                            ModelId = new Guid("e768ecab-0a8f-4246-a02d-dc9139d497dd"),
                            Odo = 463,
                            PlateNumber = "BJGZFTE6XBPQ36241",
                            RentCost = 494.96085489072351,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("8d49ab87-09c2-4682-87e5-62f79425cd8a"),
                            FuelType = 2,
                            ModelId = new Guid("e768ecab-0a8f-4246-a02d-dc9139d497dd"),
                            Odo = 2534,
                            PlateNumber = "0GMT2OAOOFZK31840",
                            RentCost = 763.20326667379607,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("aed06558-2655-4a4c-836e-a8181a423143"),
                            FuelType = 1,
                            ModelId = new Guid("019f2d5e-c2c3-4e19-90d7-29b1e57ef74d"),
                            Odo = 2881,
                            PlateNumber = "2VRBW0WNDMTR45245",
                            RentCost = 1299.0409716929362,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("2f334f92-7422-474d-a707-8b6d13263de6"),
                            FuelType = 1,
                            ModelId = new Guid("019f2d5e-c2c3-4e19-90d7-29b1e57ef74d"),
                            Odo = 125,
                            PlateNumber = "AIZQYA1CU8I835204",
                            RentCost = 2194.4698260262871,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("5654291a-9cf6-4175-9c5c-a30037bd3889"),
                            FuelType = 3,
                            ModelId = new Guid("019f2d5e-c2c3-4e19-90d7-29b1e57ef74d"),
                            Odo = 4714,
                            PlateNumber = "KFWWHIBORNQC62436",
                            RentCost = 247.52583720970674,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("f57eece5-c05b-4385-971c-63269344f03e"),
                            FuelType = 0,
                            ModelId = new Guid("019f2d5e-c2c3-4e19-90d7-29b1e57ef74d"),
                            Odo = 8144,
                            PlateNumber = "CLIWN756NTF155400",
                            RentCost = 3251.4638101919577,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("67d99fef-c16e-4836-b851-977d19bc6e49"),
                            FuelType = 1,
                            ModelId = new Guid("019f2d5e-c2c3-4e19-90d7-29b1e57ef74d"),
                            Odo = 3031,
                            PlateNumber = "F4R7RQM78AXH82037",
                            RentCost = 791.42243306705723,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("a02983d5-a2d0-4cba-8926-739596f33a3b"),
                            FuelType = 1,
                            ModelId = new Guid("774a072c-b689-41b3-aa0d-07d39b86c26d"),
                            Odo = 660,
                            PlateNumber = "4W33U5OR1ECK61258",
                            RentCost = 2204.0351922044429,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("2a24678f-42ea-488b-91d2-c4dfe5874141"),
                            FuelType = 1,
                            ModelId = new Guid("774a072c-b689-41b3-aa0d-07d39b86c26d"),
                            Odo = 6326,
                            PlateNumber = "JDY2CK3CD7GM92911",
                            RentCost = 348.50365645303282,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("b6d495f9-de92-477d-b70d-cebf232114bb"),
                            FuelType = 2,
                            ModelId = new Guid("774a072c-b689-41b3-aa0d-07d39b86c26d"),
                            Odo = 2278,
                            PlateNumber = "BC9TZB5YOQSE39756",
                            RentCost = 2357.3101377675594,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("5b24cd05-3be4-4035-bd9e-f31a8d9b9620"),
                            FuelType = 2,
                            ModelId = new Guid("774a072c-b689-41b3-aa0d-07d39b86c26d"),
                            Odo = 1485,
                            PlateNumber = "V51S2B84FCD558653",
                            RentCost = 410.22516505810455,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("b31a6916-9ee7-4db3-a89b-3cd2f48c99aa"),
                            FuelType = 0,
                            ModelId = new Guid("774a072c-b689-41b3-aa0d-07d39b86c26d"),
                            Odo = 6447,
                            PlateNumber = "R9P0SIQS1RTU97011",
                            RentCost = 3731.9061208468265,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("48e3d306-b64c-4a07-9eb5-64f93e4561f1"),
                            FuelType = 3,
                            ModelId = new Guid("bf80bd70-f83b-4f49-afea-63df41243d78"),
                            Odo = 5345,
                            PlateNumber = "0BCDQZ7GJ7DP44779",
                            RentCost = 1767.1711451259685,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("1a1b1bcd-9551-4b63-9085-33ed9cbd5901"),
                            FuelType = 3,
                            ModelId = new Guid("bf80bd70-f83b-4f49-afea-63df41243d78"),
                            Odo = 7694,
                            PlateNumber = "FGS5SLK20VF852455",
                            RentCost = 1008.8959312106759,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("ce2ec460-9c8a-420d-bb64-b23959cc140b"),
                            FuelType = 2,
                            ModelId = new Guid("bf80bd70-f83b-4f49-afea-63df41243d78"),
                            Odo = 6453,
                            PlateNumber = "JOVGAO199HYG59527",
                            RentCost = 3502.7618542756704,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("329d8d53-9aca-48ab-b883-acf2263b4077"),
                            FuelType = 2,
                            ModelId = new Guid("bf80bd70-f83b-4f49-afea-63df41243d78"),
                            Odo = 2209,
                            PlateNumber = "W9G686LWL5AE75761",
                            RentCost = 3521.3208956815688,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("8858203c-68e2-49ac-b9f7-cf8f48b15589"),
                            FuelType = 0,
                            ModelId = new Guid("bf80bd70-f83b-4f49-afea-63df41243d78"),
                            Odo = 8772,
                            PlateNumber = "BSJAVTKTFKNI44769",
                            RentCost = 3199.079786950515,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("c2067438-7752-40d0-8b4d-28002c02dcaf"),
                            FuelType = 0,
                            ModelId = new Guid("d8a70a3f-6c89-44a8-bed8-9ec5941808eb"),
                            Odo = 7450,
                            PlateNumber = "E4SD3UAYG0DM64198",
                            RentCost = 2572.0312449513485,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("593376ed-b53a-47eb-87ff-8c371398018c"),
                            FuelType = 0,
                            ModelId = new Guid("d8a70a3f-6c89-44a8-bed8-9ec5941808eb"),
                            Odo = 3880,
                            PlateNumber = "IZVYGXHDHMFC76339",
                            RentCost = 3867.3180228874462,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("3b2af9a1-8353-4991-a3bf-994e6fc078fb"),
                            FuelType = 1,
                            ModelId = new Guid("d8a70a3f-6c89-44a8-bed8-9ec5941808eb"),
                            Odo = 9977,
                            PlateNumber = "3G3HDPN9R6Q217157",
                            RentCost = 206.36545733794117,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("88a78a0c-f9c0-482c-a5c4-b6aeb832357a"),
                            FuelType = 3,
                            ModelId = new Guid("d8a70a3f-6c89-44a8-bed8-9ec5941808eb"),
                            Odo = 2367,
                            PlateNumber = "LKTL8SMSQXG977873",
                            RentCost = 1074.8432114782549,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("07263759-4174-4107-96fa-5a661ebebd97"),
                            FuelType = 0,
                            ModelId = new Guid("d8a70a3f-6c89-44a8-bed8-9ec5941808eb"),
                            Odo = 6031,
                            PlateNumber = "YV6YMENKIDA559059",
                            RentCost = 3782.5472616247671,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("781e5109-d5a5-4916-8a84-fbe516b48116"),
                            FuelType = 0,
                            ModelId = new Guid("04c0fb3c-6a9d-4525-ae5c-0dda606c8442"),
                            Odo = 7665,
                            PlateNumber = "D98H370QQFET41921",
                            RentCost = 1956.4382389927844,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("3a7cd983-70d5-4b7a-9b0c-62d2c084eac0"),
                            FuelType = 0,
                            ModelId = new Guid("04c0fb3c-6a9d-4525-ae5c-0dda606c8442"),
                            Odo = 8587,
                            PlateNumber = "Z2R1O82XXDU441816",
                            RentCost = 2938.655992539796,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a269dd95-d7b2-4af3-af6c-4298d7ee1b17"),
                            FuelType = 3,
                            ModelId = new Guid("04c0fb3c-6a9d-4525-ae5c-0dda606c8442"),
                            Odo = 6114,
                            PlateNumber = "85T1S5LU9RBW89273",
                            RentCost = 1378.8620877638898,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("73236d96-2b84-477c-9900-8a84a269e914"),
                            FuelType = 0,
                            ModelId = new Guid("04c0fb3c-6a9d-4525-ae5c-0dda606c8442"),
                            Odo = 8262,
                            PlateNumber = "VXL2IU7Q79PN61252",
                            RentCost = 2333.5260048971445,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("dc2b4e73-869b-4fb2-87e2-1581127b1776"),
                            FuelType = 1,
                            ModelId = new Guid("04c0fb3c-6a9d-4525-ae5c-0dda606c8442"),
                            Odo = 6405,
                            PlateNumber = "M4DU21B2U0S211368",
                            RentCost = 3308.6906607010978,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("03acfcb8-e25f-4efc-88fc-2a7005a905d3"),
                            FuelType = 1,
                            ModelId = new Guid("7f369d6d-3223-4e00-804e-29e7840396e6"),
                            Odo = 198,
                            PlateNumber = "1DKWK222MZYK41755",
                            RentCost = 246.69439761542048,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("bf870cfd-ddab-406f-83db-8db3e29a5781"),
                            FuelType = 0,
                            ModelId = new Guid("7f369d6d-3223-4e00-804e-29e7840396e6"),
                            Odo = 1436,
                            PlateNumber = "ZVZFVCZ0B5S419782",
                            RentCost = 1815.5339011215913,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("af34876d-8cd8-4a21-8c70-8dd5d2306bb0"),
                            FuelType = 0,
                            ModelId = new Guid("7f369d6d-3223-4e00-804e-29e7840396e6"),
                            Odo = 2678,
                            PlateNumber = "RIADZYAEY1ZG10509",
                            RentCost = 3741.8604139755107,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("8e8c0827-4af2-4777-8419-d0a0fc07480a"),
                            FuelType = 3,
                            ModelId = new Guid("7f369d6d-3223-4e00-804e-29e7840396e6"),
                            Odo = 9059,
                            PlateNumber = "094PVL9MSQF662429",
                            RentCost = 3459.6883628743371,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("a0082af5-d0c6-4e25-a896-09b66bb78661"),
                            FuelType = 0,
                            ModelId = new Guid("7f369d6d-3223-4e00-804e-29e7840396e6"),
                            Odo = 6006,
                            PlateNumber = "FBVPU5QQLFL034993",
                            RentCost = 730.39903941640296,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("e66ebdf0-e20d-4dd8-9640-65c15b23a683"),
                            FuelType = 2,
                            ModelId = new Guid("39c8eb29-afa6-42a8-a75f-2473812a7e2c"),
                            Odo = 349,
                            PlateNumber = "VC2UUXSQ5MO020021",
                            RentCost = 3553.8841497557764,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("5182d7ad-b0fb-41c5-adf5-fa7124753523"),
                            FuelType = 1,
                            ModelId = new Guid("39c8eb29-afa6-42a8-a75f-2473812a7e2c"),
                            Odo = 2889,
                            PlateNumber = "JYX0U8IK96V175826",
                            RentCost = 124.25036748013498,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("1b1511e8-58e4-445d-bc8c-ad22d881fb9d"),
                            FuelType = 2,
                            ModelId = new Guid("39c8eb29-afa6-42a8-a75f-2473812a7e2c"),
                            Odo = 4607,
                            PlateNumber = "F26OMPX48HP241303",
                            RentCost = 2947.0921812745282,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("166026df-305f-4a4b-8ad7-4306b7d5aad9"),
                            FuelType = 0,
                            ModelId = new Guid("39c8eb29-afa6-42a8-a75f-2473812a7e2c"),
                            Odo = 1139,
                            PlateNumber = "HIU8DARRXWCN90748",
                            RentCost = 2641.8159927113493,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("6de17886-c12a-4f69-8099-171ca460b81d"),
                            FuelType = 0,
                            ModelId = new Guid("39c8eb29-afa6-42a8-a75f-2473812a7e2c"),
                            Odo = 848,
                            PlateNumber = "3970Y6I7KBAB65078",
                            RentCost = 834.42587447638482,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("4256fea8-ea1d-4e72-8e3f-bfdeb66a0264"),
                            FuelType = 1,
                            ModelId = new Guid("99ad68d2-f7ac-406e-a7e1-5e53999b33fc"),
                            Odo = 4845,
                            PlateNumber = "BBRGKL9RLEPU70032",
                            RentCost = 282.51933212100562,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("4783aa81-393b-4372-be78-c79dce7421ca"),
                            FuelType = 2,
                            ModelId = new Guid("99ad68d2-f7ac-406e-a7e1-5e53999b33fc"),
                            Odo = 6329,
                            PlateNumber = "F52ZVZWI5TCV37912",
                            RentCost = 2312.7379253328936,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("9525c881-03ec-4e98-ad99-3054e0751349"),
                            FuelType = 2,
                            ModelId = new Guid("99ad68d2-f7ac-406e-a7e1-5e53999b33fc"),
                            Odo = 3243,
                            PlateNumber = "YI04TFAXVOCJ68244",
                            RentCost = 881.40797034555612,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("84b67b47-2fba-464a-afe1-3cba7e1aeb52"),
                            FuelType = 1,
                            ModelId = new Guid("99ad68d2-f7ac-406e-a7e1-5e53999b33fc"),
                            Odo = 3972,
                            PlateNumber = "ZMG7CJ7P56SN43000",
                            RentCost = 3777.8203835129707,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("62bf891b-b5c7-41c0-b555-607b1cab1eec"),
                            FuelType = 3,
                            ModelId = new Guid("99ad68d2-f7ac-406e-a7e1-5e53999b33fc"),
                            Odo = 9760,
                            PlateNumber = "24A1TAL1JSNY11092",
                            RentCost = 3375.4538179722354,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("959eaf0f-d2b1-4a7b-a96b-b6b24979374e"),
                            FuelType = 0,
                            ModelId = new Guid("aa3e71dc-c837-4988-8bb7-5e2566ba9b21"),
                            Odo = 8503,
                            PlateNumber = "LMXLN32IPHET37605",
                            RentCost = 398.02769459953049,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("36b58940-8dce-46d8-a270-a02e4b2a8e5a"),
                            FuelType = 1,
                            ModelId = new Guid("aa3e71dc-c837-4988-8bb7-5e2566ba9b21"),
                            Odo = 1263,
                            PlateNumber = "7PVELUQZVLT545058",
                            RentCost = 3550.9019595070959,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("53651752-3c3d-48e5-9241-645735e84da8"),
                            FuelType = 0,
                            ModelId = new Guid("aa3e71dc-c837-4988-8bb7-5e2566ba9b21"),
                            Odo = 2164,
                            PlateNumber = "OOD533JWJHK612212",
                            RentCost = 1518.5598139648064,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("bf604fb1-f45b-4c6e-990b-d92f833162af"),
                            FuelType = 0,
                            ModelId = new Guid("aa3e71dc-c837-4988-8bb7-5e2566ba9b21"),
                            Odo = 4635,
                            PlateNumber = "96YJUPEGKNT789149",
                            RentCost = 3888.645263387692,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("afbcc840-b808-4799-9237-7fc267eead78"),
                            FuelType = 0,
                            ModelId = new Guid("aa3e71dc-c837-4988-8bb7-5e2566ba9b21"),
                            Odo = 4191,
                            PlateNumber = "MS11NBJKA3TD14206",
                            RentCost = 3598.3268285102204,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("56361eb5-e3b3-48ec-8b6c-4132673ec75e"),
                            FuelType = 0,
                            ModelId = new Guid("1ab2986f-184e-4c30-bba8-7ca6b68d4a63"),
                            Odo = 3774,
                            PlateNumber = "50VGY7QJUKYL37882",
                            RentCost = 3122.2286666489035,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("38df96fa-90e8-4eb7-bd17-18158c7902b8"),
                            FuelType = 0,
                            ModelId = new Guid("1ab2986f-184e-4c30-bba8-7ca6b68d4a63"),
                            Odo = 4942,
                            PlateNumber = "NUONGL7CIWZ322656",
                            RentCost = 3627.2766399272746,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4c1a1369-8ffe-44e5-ac4b-a0698b3a5a2d"),
                            FuelType = 2,
                            ModelId = new Guid("1ab2986f-184e-4c30-bba8-7ca6b68d4a63"),
                            Odo = 1465,
                            PlateNumber = "WUBCWXOCMLKR87783",
                            RentCost = 2509.7351414044228,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("cd124ce4-bc1c-4d1a-9f56-0c1434ab55b3"),
                            FuelType = 1,
                            ModelId = new Guid("1ab2986f-184e-4c30-bba8-7ca6b68d4a63"),
                            Odo = 7130,
                            PlateNumber = "MSB1K2ZOTEKW29193",
                            RentCost = 1424.22742268101,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("ab4ac36b-459c-4186-b70a-8caa2333b1b0"),
                            FuelType = 1,
                            ModelId = new Guid("1ab2986f-184e-4c30-bba8-7ca6b68d4a63"),
                            Odo = 556,
                            PlateNumber = "997OH2GFSNWP45409",
                            RentCost = 3750.0240590231838,
                            VehicleState = 1,
                            VehicleType = 3
                        });
                });

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.HasOne("DAL.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("CarModels")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DAL.Entities.VehicleEntity", b =>
                {
                    b.HasOne("DAL.Entities.CarModelEntity", "CarModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("CarModelId");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("CarModels");
                });
#pragma warning restore 612, 618
        }
    }
}
