// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AgencyDbContext))]
    [Migration("20240611094602_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5aebbda-44d9-4ddc-8544-521aec01812f"),
                            Email = "Jessyca51@gmail.com",
                            FirstName = "Jarvis",
                            LastName = "Smitham",
                            PhoneNumber = "1-374-792-9051 x2835"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58c5c112-9e6b-4415-afb6-4ee4e600284b"),
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = new Guid("e33c997f-098c-4a50-8248-ddbd287aa698"),
                            Name = "Polestar"
                        },
                        new
                        {
                            Id = new Guid("bb7ea001-6e01-41bb-a55f-f694d34439c5"),
                            Name = "Audi"
                        },
                        new
                        {
                            Id = new Guid("60c2cc48-eab7-4943-a3af-57eb865a7bd7"),
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = new Guid("6e19f0ed-9464-463b-90bd-de3bc8709bda"),
                            Name = "Volkswagen"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ModelName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4301d396-bbe4-49c3-b12c-8a5688b4e2fe"),
                            ManufacturerId = new Guid("58c5c112-9e6b-4415-afb6-4ee4e600284b"),
                            Name = "Golf"
                        },
                        new
                        {
                            Id = new Guid("ec21adfd-abfa-47bd-a5e7-410bd87e8f9e"),
                            ManufacturerId = new Guid("58c5c112-9e6b-4415-afb6-4ee4e600284b"),
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = new Guid("1332b9aa-8cf2-4c67-a0f2-93e7a9f1f34e"),
                            ManufacturerId = new Guid("58c5c112-9e6b-4415-afb6-4ee4e600284b"),
                            Name = "Wrangler"
                        },
                        new
                        {
                            Id = new Guid("0724e700-bbe8-4079-9f17-e2c09b21dcfb"),
                            ManufacturerId = new Guid("58c5c112-9e6b-4415-afb6-4ee4e600284b"),
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = new Guid("57a68423-673c-4c63-9067-9f0565474917"),
                            ManufacturerId = new Guid("58c5c112-9e6b-4415-afb6-4ee4e600284b"),
                            Name = "Durango"
                        },
                        new
                        {
                            Id = new Guid("d78e8a63-167a-4323-b92d-c16cbca7ac27"),
                            ManufacturerId = new Guid("e33c997f-098c-4a50-8248-ddbd287aa698"),
                            Name = "F-150"
                        },
                        new
                        {
                            Id = new Guid("c174c72c-c49d-463e-b98f-7b0c802b0e96"),
                            ManufacturerId = new Guid("e33c997f-098c-4a50-8248-ddbd287aa698"),
                            Name = "Wrangler"
                        },
                        new
                        {
                            Id = new Guid("50e24ab0-ce48-4d11-bd10-26e9f8d98f0c"),
                            ManufacturerId = new Guid("e33c997f-098c-4a50-8248-ddbd287aa698"),
                            Name = "Model T"
                        },
                        new
                        {
                            Id = new Guid("f0a371df-2456-4543-8c2b-fc299a2e200e"),
                            ManufacturerId = new Guid("e33c997f-098c-4a50-8248-ddbd287aa698"),
                            Name = "Camry"
                        },
                        new
                        {
                            Id = new Guid("72b7ecb9-76f8-4f92-926f-42a419d25c93"),
                            ManufacturerId = new Guid("e33c997f-098c-4a50-8248-ddbd287aa698"),
                            Name = "Camry"
                        },
                        new
                        {
                            Id = new Guid("dda0c099-f6e8-4891-aaa0-1b82138597ad"),
                            ManufacturerId = new Guid("bb7ea001-6e01-41bb-a55f-f694d34439c5"),
                            Name = "Grand Caravan"
                        },
                        new
                        {
                            Id = new Guid("c2c3070c-ddd5-4470-9f20-23c3d37f667e"),
                            ManufacturerId = new Guid("bb7ea001-6e01-41bb-a55f-f694d34439c5"),
                            Name = "Model 3"
                        },
                        new
                        {
                            Id = new Guid("e432c58f-2712-4e67-aed0-0f2c9364cf34"),
                            ManufacturerId = new Guid("bb7ea001-6e01-41bb-a55f-f694d34439c5"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("a36a97d8-4026-4db3-ba3e-cab18046c3ea"),
                            ManufacturerId = new Guid("bb7ea001-6e01-41bb-a55f-f694d34439c5"),
                            Name = "CX-9"
                        },
                        new
                        {
                            Id = new Guid("bfb570cb-387f-4e43-a39a-017daea04fe7"),
                            ManufacturerId = new Guid("bb7ea001-6e01-41bb-a55f-f694d34439c5"),
                            Name = "Silverado"
                        },
                        new
                        {
                            Id = new Guid("bc7f894f-d198-4ef5-af37-e394da7a037d"),
                            ManufacturerId = new Guid("60c2cc48-eab7-4943-a3af-57eb865a7bd7"),
                            Name = "ATS"
                        },
                        new
                        {
                            Id = new Guid("462ed1d7-4c19-4572-a2eb-3366a2e4693a"),
                            ManufacturerId = new Guid("60c2cc48-eab7-4943-a3af-57eb865a7bd7"),
                            Name = "Sentra"
                        },
                        new
                        {
                            Id = new Guid("0a35ff90-4efc-4422-9612-76e03974a2f6"),
                            ManufacturerId = new Guid("60c2cc48-eab7-4943-a3af-57eb865a7bd7"),
                            Name = "ATS"
                        },
                        new
                        {
                            Id = new Guid("5e57c9b9-b1b1-43a2-a487-f99a4e1b4592"),
                            ManufacturerId = new Guid("60c2cc48-eab7-4943-a3af-57eb865a7bd7"),
                            Name = "Altima"
                        },
                        new
                        {
                            Id = new Guid("88b6181a-e2f1-4533-a3c7-ca4f1ae6c330"),
                            ManufacturerId = new Guid("60c2cc48-eab7-4943-a3af-57eb865a7bd7"),
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = new Guid("6db7c681-c188-4d29-ac1a-024b537c0973"),
                            ManufacturerId = new Guid("6e19f0ed-9464-463b-90bd-de3bc8709bda"),
                            Name = "PT Cruiser"
                        },
                        new
                        {
                            Id = new Guid("88632cc1-1779-4579-8d2c-9fde553fce74"),
                            ManufacturerId = new Guid("6e19f0ed-9464-463b-90bd-de3bc8709bda"),
                            Name = "Roadster"
                        },
                        new
                        {
                            Id = new Guid("647aabef-d596-449f-8634-ca7f3ad5ebb6"),
                            ManufacturerId = new Guid("6e19f0ed-9464-463b-90bd-de3bc8709bda"),
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = new Guid("98860bd4-682b-4930-a481-81e59e612aa0"),
                            ManufacturerId = new Guid("6e19f0ed-9464-463b-90bd-de3bc8709bda"),
                            Name = "Element"
                        },
                        new
                        {
                            Id = new Guid("5c8603db-1cf4-47a0-a02b-8164425ccace"),
                            ManufacturerId = new Guid("6e19f0ed-9464-463b-90bd-de3bc8709bda"),
                            Name = "Mercielago"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModelNameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Odo")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RentCost")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleState")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelNameId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af2f17c3-c66d-429e-bdcc-57077fb7c9c7"),
                            FuelType = 2,
                            ModelId = new Guid("4301d396-bbe4-49c3-b12c-8a5688b4e2fe"),
                            Odo = 332,
                            PlateNumber = "V30UVQJLU1QN52317",
                            RentCost = 1508.8127604942929,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("bb48518d-cdfe-4ff2-b457-c9e6861b212e"),
                            FuelType = 1,
                            ModelId = new Guid("4301d396-bbe4-49c3-b12c-8a5688b4e2fe"),
                            Odo = 9955,
                            PlateNumber = "ZDLEAS594PFS29276",
                            RentCost = 660.42445577568299,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("e17b6af0-e482-4db6-9808-e05e747c00d4"),
                            FuelType = 0,
                            ModelId = new Guid("4301d396-bbe4-49c3-b12c-8a5688b4e2fe"),
                            Odo = 1721,
                            PlateNumber = "PBU3U88Z54XB36520",
                            RentCost = 3247.3175657638913,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("692956cc-fee1-4336-8ef5-2e51e7d1e45a"),
                            FuelType = 2,
                            ModelId = new Guid("4301d396-bbe4-49c3-b12c-8a5688b4e2fe"),
                            Odo = 9923,
                            PlateNumber = "27VLEVSCA5R149459",
                            RentCost = 1774.7945668619752,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("3af3b33b-f0fa-4a9c-8a21-2f8422988764"),
                            FuelType = 2,
                            ModelId = new Guid("4301d396-bbe4-49c3-b12c-8a5688b4e2fe"),
                            Odo = 2205,
                            PlateNumber = "SIGQX7BXTIFW65100",
                            RentCost = 3662.545548116128,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("68b5bdfc-6b01-42fb-b16a-f0e40509e182"),
                            FuelType = 2,
                            ModelId = new Guid("ec21adfd-abfa-47bd-a5e7-410bd87e8f9e"),
                            Odo = 3505,
                            PlateNumber = "PRFZ87EGBTOL73372",
                            RentCost = 2295.4007136315859,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("50d2f3ed-8f4d-4937-9f7f-cf40aa31c861"),
                            FuelType = 1,
                            ModelId = new Guid("ec21adfd-abfa-47bd-a5e7-410bd87e8f9e"),
                            Odo = 1306,
                            PlateNumber = "3XNFV6IM2XTG27146",
                            RentCost = 410.59217539317291,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("c22c475e-67ea-480d-a828-f41f468462ad"),
                            FuelType = 2,
                            ModelId = new Guid("ec21adfd-abfa-47bd-a5e7-410bd87e8f9e"),
                            Odo = 6285,
                            PlateNumber = "BMRRWLE1BARZ13904",
                            RentCost = 1861.3762631200179,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("fb394bfd-ace1-4bea-9fe6-1f04e315f25e"),
                            FuelType = 2,
                            ModelId = new Guid("ec21adfd-abfa-47bd-a5e7-410bd87e8f9e"),
                            Odo = 9040,
                            PlateNumber = "JBPPD1PBFPX339345",
                            RentCost = 3339.0652024513947,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("1106c07b-24a7-46b6-8e1b-79689c34c4e1"),
                            FuelType = 3,
                            ModelId = new Guid("ec21adfd-abfa-47bd-a5e7-410bd87e8f9e"),
                            Odo = 5444,
                            PlateNumber = "1XKUG9E6UHKZ30502",
                            RentCost = 861.84863483008667,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("46a6e7c4-7e86-49c1-8be6-54dc20d11e00"),
                            FuelType = 1,
                            ModelId = new Guid("1332b9aa-8cf2-4c67-a0f2-93e7a9f1f34e"),
                            Odo = 8229,
                            PlateNumber = "EM6KU48K4IXO71389",
                            RentCost = 1454.6270757777363,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("eee41d51-4ade-4ab6-b637-648ba22851f0"),
                            FuelType = 1,
                            ModelId = new Guid("1332b9aa-8cf2-4c67-a0f2-93e7a9f1f34e"),
                            Odo = 6042,
                            PlateNumber = "RVRXEA8ZJYIR17063",
                            RentCost = 3625.4445470832939,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("6ee44403-5b6c-46de-9f64-a381b813cd18"),
                            FuelType = 3,
                            ModelId = new Guid("1332b9aa-8cf2-4c67-a0f2-93e7a9f1f34e"),
                            Odo = 4788,
                            PlateNumber = "2J7QVAK20IHV40068",
                            RentCost = 3782.5775193418217,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("a8297195-4dae-47f2-8f8b-e1a7710fd0dd"),
                            FuelType = 3,
                            ModelId = new Guid("1332b9aa-8cf2-4c67-a0f2-93e7a9f1f34e"),
                            Odo = 8069,
                            PlateNumber = "EQ80PK81GAFN81312",
                            RentCost = 588.13207764374192,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("12fe8064-f7fb-4ee4-a0e0-885da9e7b160"),
                            FuelType = 3,
                            ModelId = new Guid("1332b9aa-8cf2-4c67-a0f2-93e7a9f1f34e"),
                            Odo = 8349,
                            PlateNumber = "XX4G9D6K8ZDH98413",
                            RentCost = 3419.7878252440332,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("ba421643-7b70-4634-b2bd-9ffa5dc64b5d"),
                            FuelType = 3,
                            ModelId = new Guid("0724e700-bbe8-4079-9f17-e2c09b21dcfb"),
                            Odo = 1406,
                            PlateNumber = "IZI338TYVCIU29294",
                            RentCost = 1420.2577381910346,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("e8ff642a-7925-4cb6-81e1-5de4c87e549d"),
                            FuelType = 2,
                            ModelId = new Guid("0724e700-bbe8-4079-9f17-e2c09b21dcfb"),
                            Odo = 5709,
                            PlateNumber = "B7VRWO9H9QG850235",
                            RentCost = 2959.9787482858678,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("6633ddd6-d01c-4a15-8ef5-dd87cd26e0c2"),
                            FuelType = 2,
                            ModelId = new Guid("0724e700-bbe8-4079-9f17-e2c09b21dcfb"),
                            Odo = 8741,
                            PlateNumber = "HIF0DERRH4Z744620",
                            RentCost = 650.45999106179931,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("21d79491-01f5-4b86-bbb5-77786cbb2382"),
                            FuelType = 0,
                            ModelId = new Guid("0724e700-bbe8-4079-9f17-e2c09b21dcfb"),
                            Odo = 4644,
                            PlateNumber = "4UM29MIEG9E164983",
                            RentCost = 1920.6084478762159,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("891871c7-ac95-41f8-be54-8da1356580a3"),
                            FuelType = 2,
                            ModelId = new Guid("0724e700-bbe8-4079-9f17-e2c09b21dcfb"),
                            Odo = 1340,
                            PlateNumber = "F4S8OSU66IZR68799",
                            RentCost = 3527.2867818644127,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("a210b75d-5c41-4893-8f62-a3599cda5192"),
                            FuelType = 0,
                            ModelId = new Guid("57a68423-673c-4c63-9067-9f0565474917"),
                            Odo = 3419,
                            PlateNumber = "87R8O9CKJBLD24825",
                            RentCost = 746.7931201628237,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c0e98a07-0d98-40c8-9c2d-d184483e0b95"),
                            FuelType = 1,
                            ModelId = new Guid("57a68423-673c-4c63-9067-9f0565474917"),
                            Odo = 323,
                            PlateNumber = "3EOMKKLMNZGT61421",
                            RentCost = 601.73971988299877,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("fc478c97-f232-45f6-bc68-b5389a4c9339"),
                            FuelType = 2,
                            ModelId = new Guid("57a68423-673c-4c63-9067-9f0565474917"),
                            Odo = 1928,
                            PlateNumber = "HVMQB9JGAIUZ42564",
                            RentCost = 1231.6055893021837,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4cbe4f2a-4bbe-49cd-9832-5c9e5b3e1971"),
                            FuelType = 1,
                            ModelId = new Guid("57a68423-673c-4c63-9067-9f0565474917"),
                            Odo = 2260,
                            PlateNumber = "95NWBYIWRTUL88327",
                            RentCost = 3827.9302014537384,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("11b2a283-5c68-430f-9133-7adaf57602b1"),
                            FuelType = 1,
                            ModelId = new Guid("57a68423-673c-4c63-9067-9f0565474917"),
                            Odo = 9772,
                            PlateNumber = "4PVUCT12J1WG76936",
                            RentCost = 741.35558741584782,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("ca3a1f98-5c2a-4662-9eb2-4370fcaa0cc8"),
                            FuelType = 1,
                            ModelId = new Guid("d78e8a63-167a-4323-b92d-c16cbca7ac27"),
                            Odo = 6318,
                            PlateNumber = "F4BN5M77VKYQ39126",
                            RentCost = 3929.8589886019745,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c12a50e5-2a38-4c7e-b89f-e0b23eba0b20"),
                            FuelType = 2,
                            ModelId = new Guid("d78e8a63-167a-4323-b92d-c16cbca7ac27"),
                            Odo = 10000,
                            PlateNumber = "MSLSG6Y8E6I792908",
                            RentCost = 1434.8163083207576,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("172f9abd-7822-4156-86d0-8557a4cffaca"),
                            FuelType = 0,
                            ModelId = new Guid("d78e8a63-167a-4323-b92d-c16cbca7ac27"),
                            Odo = 2078,
                            PlateNumber = "N0GDTS5DG1FI76401",
                            RentCost = 2064.9979373842893,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("b3f4a3f2-aa0d-44a5-a793-309fdc630c37"),
                            FuelType = 1,
                            ModelId = new Guid("d78e8a63-167a-4323-b92d-c16cbca7ac27"),
                            Odo = 5196,
                            PlateNumber = "2VJEFCIM8YE693931",
                            RentCost = 3115.7279906571416,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("7cb4e5dc-96e8-492c-8bfb-8dbfb784bc3c"),
                            FuelType = 3,
                            ModelId = new Guid("d78e8a63-167a-4323-b92d-c16cbca7ac27"),
                            Odo = 2753,
                            PlateNumber = "GYI8FQU9TTO134488",
                            RentCost = 1032.5213977442506,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("fa03ad51-ab21-4d7d-bc8c-d4f2a80ab138"),
                            FuelType = 0,
                            ModelId = new Guid("c174c72c-c49d-463e-b98f-7b0c802b0e96"),
                            Odo = 1188,
                            PlateNumber = "830SHX0OFPR848579",
                            RentCost = 2232.5118349552613,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("36b7d125-ad91-446b-a6e5-432cb5e30024"),
                            FuelType = 1,
                            ModelId = new Guid("c174c72c-c49d-463e-b98f-7b0c802b0e96"),
                            Odo = 9084,
                            PlateNumber = "W306ALROQLLR87907",
                            RentCost = 2052.2071805437076,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("dca2adad-0bf6-491c-bc53-aa00d17387b8"),
                            FuelType = 2,
                            ModelId = new Guid("c174c72c-c49d-463e-b98f-7b0c802b0e96"),
                            Odo = 7464,
                            PlateNumber = "1KOC263P8EXI58687",
                            RentCost = 3497.8207029109881,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("558b0365-4e26-4bc9-ab7e-244faec60060"),
                            FuelType = 3,
                            ModelId = new Guid("c174c72c-c49d-463e-b98f-7b0c802b0e96"),
                            Odo = 9718,
                            PlateNumber = "70PLE6O5X4FB60322",
                            RentCost = 3778.4605133821051,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("66c711f0-f027-42b5-a367-7bd6c7db3db0"),
                            FuelType = 0,
                            ModelId = new Guid("c174c72c-c49d-463e-b98f-7b0c802b0e96"),
                            Odo = 4136,
                            PlateNumber = "DZZ8BH49H4QQ92518",
                            RentCost = 3627.9434431998716,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("63fcd55f-f54c-46ad-bdbc-bc751edf8b4c"),
                            FuelType = 1,
                            ModelId = new Guid("50e24ab0-ce48-4d11-bd10-26e9f8d98f0c"),
                            Odo = 2584,
                            PlateNumber = "X6STTDTTETUC68527",
                            RentCost = 3838.2504659962096,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("c05332ca-5c1e-482d-83a9-47178d3e9725"),
                            FuelType = 0,
                            ModelId = new Guid("50e24ab0-ce48-4d11-bd10-26e9f8d98f0c"),
                            Odo = 1289,
                            PlateNumber = "B24N7PM42TSZ43814",
                            RentCost = 3701.9761568508084,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("dd44bae9-cdd3-4853-a700-42e8f913db7c"),
                            FuelType = 2,
                            ModelId = new Guid("50e24ab0-ce48-4d11-bd10-26e9f8d98f0c"),
                            Odo = 6334,
                            PlateNumber = "NAPBSO2O1NWQ95744",
                            RentCost = 3360.2423481550504,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("efc45ba4-b9f7-4433-a204-fcd40cd7ad53"),
                            FuelType = 2,
                            ModelId = new Guid("50e24ab0-ce48-4d11-bd10-26e9f8d98f0c"),
                            Odo = 608,
                            PlateNumber = "STLNV01VMFW741064",
                            RentCost = 2478.8666061101399,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("6aba9b73-0595-4196-9f7c-f714d045c771"),
                            FuelType = 0,
                            ModelId = new Guid("50e24ab0-ce48-4d11-bd10-26e9f8d98f0c"),
                            Odo = 3827,
                            PlateNumber = "8ZVW1Z5410UX21494",
                            RentCost = 3669.9500623477243,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c3bc470f-0e8b-4fac-918a-23f2399f2053"),
                            FuelType = 2,
                            ModelId = new Guid("f0a371df-2456-4543-8c2b-fc299a2e200e"),
                            Odo = 3994,
                            PlateNumber = "1JGRLBC10TZ250579",
                            RentCost = 2453.9214669062403,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("c136516a-017f-488b-a16a-9debecf3174c"),
                            FuelType = 3,
                            ModelId = new Guid("f0a371df-2456-4543-8c2b-fc299a2e200e"),
                            Odo = 4622,
                            PlateNumber = "6HA6RDJLVXJN74455",
                            RentCost = 3751.8102894066456,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("ec29f468-94ed-43a3-9330-23dfd2a4a33c"),
                            FuelType = 3,
                            ModelId = new Guid("f0a371df-2456-4543-8c2b-fc299a2e200e"),
                            Odo = 1349,
                            PlateNumber = "F2NTEHPYROXL72966",
                            RentCost = 2760.1280350597049,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("df6d930c-37fb-4373-907e-dad479b100b6"),
                            FuelType = 2,
                            ModelId = new Guid("f0a371df-2456-4543-8c2b-fc299a2e200e"),
                            Odo = 4900,
                            PlateNumber = "APOA8O72JUTH63440",
                            RentCost = 1026.8619073420682,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("3798bc0d-408e-43a9-909b-32fdf6623b6e"),
                            FuelType = 3,
                            ModelId = new Guid("f0a371df-2456-4543-8c2b-fc299a2e200e"),
                            Odo = 3800,
                            PlateNumber = "6DUWMF3BU5MJ25176",
                            RentCost = 2946.4222984079875,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("152100e2-c979-4e50-88bf-ff49b3319c53"),
                            FuelType = 1,
                            ModelId = new Guid("72b7ecb9-76f8-4f92-926f-42a419d25c93"),
                            Odo = 7726,
                            PlateNumber = "O294V078K1TW68004",
                            RentCost = 2410.0551568841606,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f355f804-38c6-4b47-95d0-391cd1f6213e"),
                            FuelType = 0,
                            ModelId = new Guid("72b7ecb9-76f8-4f92-926f-42a419d25c93"),
                            Odo = 2738,
                            PlateNumber = "U07MGJPQSYZ293344",
                            RentCost = 2254.5330279178247,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("a390d4f1-9b6a-4035-9e9c-88a8d43d38b1"),
                            FuelType = 3,
                            ModelId = new Guid("72b7ecb9-76f8-4f92-926f-42a419d25c93"),
                            Odo = 2795,
                            PlateNumber = "064GHIAM41N030283",
                            RentCost = 3010.2116751615645,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("1b7ef0e2-e839-4009-ad5e-2763e4ec1d36"),
                            FuelType = 0,
                            ModelId = new Guid("72b7ecb9-76f8-4f92-926f-42a419d25c93"),
                            Odo = 5983,
                            PlateNumber = "DZKV7GLK1YLE68997",
                            RentCost = 1361.2449044836519,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("4337700a-1686-469b-9810-5d5e98ce1e05"),
                            FuelType = 2,
                            ModelId = new Guid("72b7ecb9-76f8-4f92-926f-42a419d25c93"),
                            Odo = 9151,
                            PlateNumber = "WS84EVDFRDHL90517",
                            RentCost = 1155.7275733963525,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("faec0425-94f7-4ad0-8485-724cc04cc7a3"),
                            FuelType = 3,
                            ModelId = new Guid("dda0c099-f6e8-4891-aaa0-1b82138597ad"),
                            Odo = 9290,
                            PlateNumber = "O5Q2IOHK38FK45893",
                            RentCost = 3407.8655459180259,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("e8d9c08f-15b6-41b6-a4c3-bce0727466ce"),
                            FuelType = 1,
                            ModelId = new Guid("dda0c099-f6e8-4891-aaa0-1b82138597ad"),
                            Odo = 2209,
                            PlateNumber = "NQ91BP37V5WC12302",
                            RentCost = 679.46550167558325,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("5e606ca0-e45f-47fa-8b6f-7174ad44abe5"),
                            FuelType = 1,
                            ModelId = new Guid("dda0c099-f6e8-4891-aaa0-1b82138597ad"),
                            Odo = 3162,
                            PlateNumber = "60PXFGBAAVKC66848",
                            RentCost = 155.5103290625338,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f0d30711-3359-4cce-b461-868899f1ef42"),
                            FuelType = 0,
                            ModelId = new Guid("dda0c099-f6e8-4891-aaa0-1b82138597ad"),
                            Odo = 2072,
                            PlateNumber = "P4H43SZB1YJZ82455",
                            RentCost = 1528.1656324110038,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("b03016b1-82c1-4b28-8686-8366642b339f"),
                            FuelType = 0,
                            ModelId = new Guid("dda0c099-f6e8-4891-aaa0-1b82138597ad"),
                            Odo = 4937,
                            PlateNumber = "5KH8MIJGH1PH33501",
                            RentCost = 3957.4243383043668,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("a5b315b7-581e-4e1d-8384-9ac707174fad"),
                            FuelType = 0,
                            ModelId = new Guid("c2c3070c-ddd5-4470-9f20-23c3d37f667e"),
                            Odo = 2195,
                            PlateNumber = "VLIXVOXD2ZEF47826",
                            RentCost = 1965.2229983631985,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("86729864-793b-483b-9a7c-7c0716e429af"),
                            FuelType = 1,
                            ModelId = new Guid("c2c3070c-ddd5-4470-9f20-23c3d37f667e"),
                            Odo = 480,
                            PlateNumber = "03631K1MJILV89313",
                            RentCost = 1204.2306236101838,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("2789bb72-1e65-447b-b353-93c6973a6a0e"),
                            FuelType = 2,
                            ModelId = new Guid("c2c3070c-ddd5-4470-9f20-23c3d37f667e"),
                            Odo = 1314,
                            PlateNumber = "YSAB1AL3ZJV320478",
                            RentCost = 2304.5141174069122,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("b5b06b7c-8a20-4c7f-b0f8-9e4169102cb8"),
                            FuelType = 1,
                            ModelId = new Guid("c2c3070c-ddd5-4470-9f20-23c3d37f667e"),
                            Odo = 8472,
                            PlateNumber = "EQ0KDYCKN9N962271",
                            RentCost = 776.47953414805249,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("71b5f992-b507-455c-b8f1-04b012448cf2"),
                            FuelType = 3,
                            ModelId = new Guid("c2c3070c-ddd5-4470-9f20-23c3d37f667e"),
                            Odo = 3721,
                            PlateNumber = "LN5O29XXSBRC86193",
                            RentCost = 448.41044587287547,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("0f5f61c1-795d-4fba-adfb-5688ba43daee"),
                            FuelType = 1,
                            ModelId = new Guid("e432c58f-2712-4e67-aed0-0f2c9364cf34"),
                            Odo = 4227,
                            PlateNumber = "PK73YT10URJ713211",
                            RentCost = 730.14516983759881,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("7f5fd278-332e-4bc2-8494-70bccb50ddff"),
                            FuelType = 0,
                            ModelId = new Guid("e432c58f-2712-4e67-aed0-0f2c9364cf34"),
                            Odo = 9051,
                            PlateNumber = "Q6VRAGDW2XA124792",
                            RentCost = 2689.2210242409851,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("e4a78be6-02ae-4a84-8b78-083d6b9bd438"),
                            FuelType = 1,
                            ModelId = new Guid("e432c58f-2712-4e67-aed0-0f2c9364cf34"),
                            Odo = 3594,
                            PlateNumber = "G24IAL7OHXFZ19424",
                            RentCost = 3671.4790723464239,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("b215754e-bd07-454f-a376-47cf3c47cb0c"),
                            FuelType = 3,
                            ModelId = new Guid("e432c58f-2712-4e67-aed0-0f2c9364cf34"),
                            Odo = 9513,
                            PlateNumber = "G8DB2Y4OCZSS41805",
                            RentCost = 2971.3189985801373,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("4cfad2e1-5de5-4384-af6a-6b387c4ab61f"),
                            FuelType = 1,
                            ModelId = new Guid("e432c58f-2712-4e67-aed0-0f2c9364cf34"),
                            Odo = 3251,
                            PlateNumber = "CQYPQ17LAGT766317",
                            RentCost = 1054.7465773959461,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("f7310c54-92e0-4571-bad1-2302c0254819"),
                            FuelType = 3,
                            ModelId = new Guid("a36a97d8-4026-4db3-ba3e-cab18046c3ea"),
                            Odo = 4738,
                            PlateNumber = "5CLM7HF475O817615",
                            RentCost = 1733.8694126213829,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("c579a156-a4e9-4db3-830a-3ea5a53aace7"),
                            FuelType = 1,
                            ModelId = new Guid("a36a97d8-4026-4db3-ba3e-cab18046c3ea"),
                            Odo = 6482,
                            PlateNumber = "6ZBQ01VK2GPF64058",
                            RentCost = 2275.2512698065384,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("d7812b21-eba9-431a-a8d9-0b84319c9503"),
                            FuelType = 3,
                            ModelId = new Guid("a36a97d8-4026-4db3-ba3e-cab18046c3ea"),
                            Odo = 315,
                            PlateNumber = "3YPDTHQRKAII66049",
                            RentCost = 1602.5041135580259,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f7365d5d-c996-4ade-aad0-d861187a3694"),
                            FuelType = 2,
                            ModelId = new Guid("a36a97d8-4026-4db3-ba3e-cab18046c3ea"),
                            Odo = 6163,
                            PlateNumber = "F2AR5F714KWT23177",
                            RentCost = 3159.7157189542245,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("8817ff32-5f86-4985-8704-7d8f0426f7b1"),
                            FuelType = 0,
                            ModelId = new Guid("a36a97d8-4026-4db3-ba3e-cab18046c3ea"),
                            Odo = 8710,
                            PlateNumber = "TVJHJPMS58QP27130",
                            RentCost = 2005.6742507506935,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("3ca1931f-0793-4749-be09-369e9f548a57"),
                            FuelType = 0,
                            ModelId = new Guid("bfb570cb-387f-4e43-a39a-017daea04fe7"),
                            Odo = 3360,
                            PlateNumber = "JITB5TRVNRKD59866",
                            RentCost = 3917.8231446319851,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("5c2b1e32-6686-4f83-8e6e-1606517aabdc"),
                            FuelType = 2,
                            ModelId = new Guid("bfb570cb-387f-4e43-a39a-017daea04fe7"),
                            Odo = 7206,
                            PlateNumber = "23NG2P6K43KW84272",
                            RentCost = 3129.3534300201409,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("92a39b70-0d27-4582-b255-0ddc9b39bc53"),
                            FuelType = 0,
                            ModelId = new Guid("bfb570cb-387f-4e43-a39a-017daea04fe7"),
                            Odo = 156,
                            PlateNumber = "Z9U8YARZEXZX85085",
                            RentCost = 3440.2307458104733,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("60ca1a37-b6b8-48bf-a5a9-1b68aaa9281b"),
                            FuelType = 1,
                            ModelId = new Guid("bfb570cb-387f-4e43-a39a-017daea04fe7"),
                            Odo = 2881,
                            PlateNumber = "CIUYG4X8WIBV54077",
                            RentCost = 2218.678820173051,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("69510daa-7c56-45df-84e3-c11224491158"),
                            FuelType = 1,
                            ModelId = new Guid("bfb570cb-387f-4e43-a39a-017daea04fe7"),
                            Odo = 3622,
                            PlateNumber = "ETIUINQEW3IY86449",
                            RentCost = 3479.0016175871569,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("9a18854e-99b7-4a1c-8a92-c4bc41fda7db"),
                            FuelType = 0,
                            ModelId = new Guid("bc7f894f-d198-4ef5-af37-e394da7a037d"),
                            Odo = 9282,
                            PlateNumber = "3D83O4XBMUUQ56287",
                            RentCost = 2689.0613170180945,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("e6e1aa03-cb9e-46d3-b63d-be07b0a3b28b"),
                            FuelType = 3,
                            ModelId = new Guid("bc7f894f-d198-4ef5-af37-e394da7a037d"),
                            Odo = 9118,
                            PlateNumber = "ODQFNNU4TMBH47676",
                            RentCost = 823.52757597363757,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("02016f0c-a577-4f0e-add9-3fd4916fdd7b"),
                            FuelType = 0,
                            ModelId = new Guid("bc7f894f-d198-4ef5-af37-e394da7a037d"),
                            Odo = 3931,
                            PlateNumber = "68NZLY56SQXS55621",
                            RentCost = 2880.5196802347532,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("c2e0604d-b7e9-474d-9a28-ef71976bc20c"),
                            FuelType = 2,
                            ModelId = new Guid("bc7f894f-d198-4ef5-af37-e394da7a037d"),
                            Odo = 4448,
                            PlateNumber = "68K43P5Z93EI49173",
                            RentCost = 2204.5753223525676,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("de527ef4-5333-4313-aeac-b896fb295ff8"),
                            FuelType = 0,
                            ModelId = new Guid("bc7f894f-d198-4ef5-af37-e394da7a037d"),
                            Odo = 1819,
                            PlateNumber = "ICS5XKQWTCHA91189",
                            RentCost = 1220.798464795497,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("9ccd2bff-8833-4855-b67a-8bc7096a4e84"),
                            FuelType = 1,
                            ModelId = new Guid("462ed1d7-4c19-4572-a2eb-3366a2e4693a"),
                            Odo = 7212,
                            PlateNumber = "A36LCROPSTN644433",
                            RentCost = 3024.082094386456,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("289b1228-cdba-4465-8347-75fa66c2fe16"),
                            FuelType = 0,
                            ModelId = new Guid("462ed1d7-4c19-4572-a2eb-3366a2e4693a"),
                            Odo = 1299,
                            PlateNumber = "NPXU7LTZ5NQY50818",
                            RentCost = 3232.6175407059709,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("9316b814-bdbe-4b6b-a497-1f90c3419925"),
                            FuelType = 2,
                            ModelId = new Guid("462ed1d7-4c19-4572-a2eb-3366a2e4693a"),
                            Odo = 8707,
                            PlateNumber = "N8VIBO01YWSB20914",
                            RentCost = 912.97224019781277,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("1ebe8a6c-0f7c-4f69-87ff-8db988a2b54e"),
                            FuelType = 3,
                            ModelId = new Guid("462ed1d7-4c19-4572-a2eb-3366a2e4693a"),
                            Odo = 7373,
                            PlateNumber = "OFEARUHBHTA294631",
                            RentCost = 1495.3656024495599,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("02224568-e5ed-4ab5-a95c-c8331f0151ce"),
                            FuelType = 2,
                            ModelId = new Guid("462ed1d7-4c19-4572-a2eb-3366a2e4693a"),
                            Odo = 1931,
                            PlateNumber = "46RR02BA3ZP783434",
                            RentCost = 2929.1543324730865,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("2a4aaff4-28fc-4a18-abd0-ef158e8b85f2"),
                            FuelType = 3,
                            ModelId = new Guid("0a35ff90-4efc-4422-9612-76e03974a2f6"),
                            Odo = 5710,
                            PlateNumber = "HEV349J90NL718472",
                            RentCost = 2709.0207344426799,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("68a339fd-ace8-4ae0-884b-74405f0a18ab"),
                            FuelType = 2,
                            ModelId = new Guid("0a35ff90-4efc-4422-9612-76e03974a2f6"),
                            Odo = 9367,
                            PlateNumber = "WHU7CNO86YWD88841",
                            RentCost = 3811.2480486943268,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("ca1b8f24-9207-4a3a-bdfb-6dc44a1047f2"),
                            FuelType = 1,
                            ModelId = new Guid("0a35ff90-4efc-4422-9612-76e03974a2f6"),
                            Odo = 2493,
                            PlateNumber = "W210N4OEH7XD74031",
                            RentCost = 2676.7310546055869,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("ca2dd45c-ac50-4dcb-8281-d050be16a234"),
                            FuelType = 3,
                            ModelId = new Guid("0a35ff90-4efc-4422-9612-76e03974a2f6"),
                            Odo = 8922,
                            PlateNumber = "7QG0ET57MKJG31361",
                            RentCost = 1057.9457994399736,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("53a2471a-32ce-45be-963e-e5b7e2a99fa7"),
                            FuelType = 0,
                            ModelId = new Guid("0a35ff90-4efc-4422-9612-76e03974a2f6"),
                            Odo = 6948,
                            PlateNumber = "VXPPR2RV35QM28156",
                            RentCost = 3180.2481389966861,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("a3d729c7-63b0-4c89-b057-91d7265032bd"),
                            FuelType = 0,
                            ModelId = new Guid("5e57c9b9-b1b1-43a2-a487-f99a4e1b4592"),
                            Odo = 6706,
                            PlateNumber = "GPRK5GYMQ7B733859",
                            RentCost = 3996.4496536742777,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("43cbe8c2-2fdf-4492-8570-e77abfa3636a"),
                            FuelType = 0,
                            ModelId = new Guid("5e57c9b9-b1b1-43a2-a487-f99a4e1b4592"),
                            Odo = 9986,
                            PlateNumber = "6SUWZGWXRSA052353",
                            RentCost = 3148.2448216470143,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("b5b2b0b3-d6f7-4bf7-b2cc-9dbcb59a6b69"),
                            FuelType = 1,
                            ModelId = new Guid("5e57c9b9-b1b1-43a2-a487-f99a4e1b4592"),
                            Odo = 2658,
                            PlateNumber = "GTTWXPP30VZ899749",
                            RentCost = 2869.1196946400923,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("f4d8ed60-1def-455b-8216-3fe8dcad8551"),
                            FuelType = 1,
                            ModelId = new Guid("5e57c9b9-b1b1-43a2-a487-f99a4e1b4592"),
                            Odo = 3802,
                            PlateNumber = "VMOC6H2J41ZV97476",
                            RentCost = 2441.9335316123456,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("5c599e10-a41d-46c8-bd4e-5a040ba454d0"),
                            FuelType = 3,
                            ModelId = new Guid("5e57c9b9-b1b1-43a2-a487-f99a4e1b4592"),
                            Odo = 941,
                            PlateNumber = "7J5ECIWSDTVU43725",
                            RentCost = 212.8154657229739,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("7550637b-175c-4dad-9f01-c9b2ce2785ac"),
                            FuelType = 3,
                            ModelId = new Guid("88b6181a-e2f1-4533-a3c7-ca4f1ae6c330"),
                            Odo = 4000,
                            PlateNumber = "R3MWW3WPZPZI44626",
                            RentCost = 1458.2918360464269,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c9cbdfc5-a05a-45fc-96d5-dc2f8af1f3a6"),
                            FuelType = 2,
                            ModelId = new Guid("88b6181a-e2f1-4533-a3c7-ca4f1ae6c330"),
                            Odo = 1929,
                            PlateNumber = "WTPD4OFZF9VJ64294",
                            RentCost = 1343.4059013735323,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("4415269b-66aa-4685-9237-9c6bbbaa8990"),
                            FuelType = 3,
                            ModelId = new Guid("88b6181a-e2f1-4533-a3c7-ca4f1ae6c330"),
                            Odo = 1607,
                            PlateNumber = "6O97IZVSRYNV75732",
                            RentCost = 567.14686417467215,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("89ec2912-dfe3-43b5-af81-da168aa38fcc"),
                            FuelType = 1,
                            ModelId = new Guid("88b6181a-e2f1-4533-a3c7-ca4f1ae6c330"),
                            Odo = 7396,
                            PlateNumber = "UBFX3AVWJ1OL48750",
                            RentCost = 3920.7949486870307,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6397ed85-9f1b-4f4b-99fa-81c12ecaed48"),
                            FuelType = 3,
                            ModelId = new Guid("88b6181a-e2f1-4533-a3c7-ca4f1ae6c330"),
                            Odo = 5720,
                            PlateNumber = "85UPVNDBXNH095226",
                            RentCost = 1775.3547203875978,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("78272efa-de4d-45e5-9022-3d18fb55d0ec"),
                            FuelType = 1,
                            ModelId = new Guid("6db7c681-c188-4d29-ac1a-024b537c0973"),
                            Odo = 7717,
                            PlateNumber = "FB0KQ5PLEYR237715",
                            RentCost = 2201.3012343422702,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a646ad98-31a7-41e3-bb74-72769510dedf"),
                            FuelType = 1,
                            ModelId = new Guid("6db7c681-c188-4d29-ac1a-024b537c0973"),
                            Odo = 7795,
                            PlateNumber = "42T9F2T05ZO968172",
                            RentCost = 530.70520862582907,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("29136aed-8253-40b4-9d21-3e4654785097"),
                            FuelType = 3,
                            ModelId = new Guid("6db7c681-c188-4d29-ac1a-024b537c0973"),
                            Odo = 352,
                            PlateNumber = "2QFKL8Z6WQOA14436",
                            RentCost = 386.45881252793237,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("354e65f6-4caf-4719-81e7-f13d75b3729d"),
                            FuelType = 3,
                            ModelId = new Guid("6db7c681-c188-4d29-ac1a-024b537c0973"),
                            Odo = 8253,
                            PlateNumber = "IIQ3D858IPVK94928",
                            RentCost = 1221.092747293432,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("be65a1fc-ce5b-4c56-aaa2-c8a6fccdb06e"),
                            FuelType = 0,
                            ModelId = new Guid("6db7c681-c188-4d29-ac1a-024b537c0973"),
                            Odo = 1432,
                            PlateNumber = "U4BK8YY6FSDT90882",
                            RentCost = 2029.8185006509043,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("e72b7322-7c5e-456c-9d62-ff83d2194861"),
                            FuelType = 1,
                            ModelId = new Guid("88632cc1-1779-4579-8d2c-9fde553fce74"),
                            Odo = 5321,
                            PlateNumber = "DBAOARH1CSBK47003",
                            RentCost = 3085.2133975238526,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("2e038396-a028-40b4-a8e0-4d2ecece4388"),
                            FuelType = 2,
                            ModelId = new Guid("88632cc1-1779-4579-8d2c-9fde553fce74"),
                            Odo = 9523,
                            PlateNumber = "QDNNGHVUV2WC66858",
                            RentCost = 1133.7264180792677,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4c4980fb-e1af-4686-87d6-24a9505f5842"),
                            FuelType = 3,
                            ModelId = new Guid("88632cc1-1779-4579-8d2c-9fde553fce74"),
                            Odo = 6653,
                            PlateNumber = "EWY1OOIE64T023689",
                            RentCost = 1210.965201330403,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("96e21e3c-fabc-4c60-82d3-0cdbd8bd94a4"),
                            FuelType = 1,
                            ModelId = new Guid("88632cc1-1779-4579-8d2c-9fde553fce74"),
                            Odo = 1264,
                            PlateNumber = "M60N5S0TZWX958870",
                            RentCost = 2493.9629562836408,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("477e4711-ef10-46f2-acb6-a1125048d095"),
                            FuelType = 2,
                            ModelId = new Guid("88632cc1-1779-4579-8d2c-9fde553fce74"),
                            Odo = 8441,
                            PlateNumber = "C7L61CO8KDOG25207",
                            RentCost = 3316.7837718700939,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("0cbb9318-c83d-4efe-909b-c7e9c1a71cee"),
                            FuelType = 3,
                            ModelId = new Guid("647aabef-d596-449f-8634-ca7f3ad5ebb6"),
                            Odo = 1585,
                            PlateNumber = "71PDB49CKKSK64710",
                            RentCost = 3834.7154933561405,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("08bac291-dae6-41da-96ba-017280fa8652"),
                            FuelType = 0,
                            ModelId = new Guid("647aabef-d596-449f-8634-ca7f3ad5ebb6"),
                            Odo = 3405,
                            PlateNumber = "YUTWIUN0GCIP64836",
                            RentCost = 3171.902940874244,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("c0c752c9-a46f-4023-a5bf-a73cb564527d"),
                            FuelType = 1,
                            ModelId = new Guid("647aabef-d596-449f-8634-ca7f3ad5ebb6"),
                            Odo = 2495,
                            PlateNumber = "76RGXSOV3OSQ99260",
                            RentCost = 1781.6781766189572,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("b0c4cf82-c0eb-4bb2-b20f-ad53f0a589ae"),
                            FuelType = 2,
                            ModelId = new Guid("647aabef-d596-449f-8634-ca7f3ad5ebb6"),
                            Odo = 6656,
                            PlateNumber = "1BC2UWOHECOF29309",
                            RentCost = 950.29643640449888,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("97e52b68-1a66-4064-bb12-6ad5b242bac3"),
                            FuelType = 3,
                            ModelId = new Guid("647aabef-d596-449f-8634-ca7f3ad5ebb6"),
                            Odo = 7077,
                            PlateNumber = "XPDTH54RPPPV15519",
                            RentCost = 802.8121746145855,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("992e475c-e6fb-4b98-ac8d-94cec95bbf96"),
                            FuelType = 2,
                            ModelId = new Guid("98860bd4-682b-4930-a481-81e59e612aa0"),
                            Odo = 5777,
                            PlateNumber = "J6Q2BTZ75PTA78394",
                            RentCost = 1073.4217214782709,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("719062ca-84d3-4935-ae1a-ee63e70ac4a2"),
                            FuelType = 2,
                            ModelId = new Guid("98860bd4-682b-4930-a481-81e59e612aa0"),
                            Odo = 6327,
                            PlateNumber = "RT1XQ1QRTDPV61471",
                            RentCost = 3761.210981067672,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("a80cac89-5326-4b27-8be0-5a6500a237b0"),
                            FuelType = 3,
                            ModelId = new Guid("98860bd4-682b-4930-a481-81e59e612aa0"),
                            Odo = 6948,
                            PlateNumber = "L9SBMZ2Y04UE13354",
                            RentCost = 2552.7484795084742,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("132c75cc-b8c8-4404-a14b-45e549a781bd"),
                            FuelType = 1,
                            ModelId = new Guid("98860bd4-682b-4930-a481-81e59e612aa0"),
                            Odo = 759,
                            PlateNumber = "IV9ZAENTH1MI41177",
                            RentCost = 301.94562489851319,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("55f2074f-5382-493b-a996-84a8ca5b37b8"),
                            FuelType = 3,
                            ModelId = new Guid("98860bd4-682b-4930-a481-81e59e612aa0"),
                            Odo = 3649,
                            PlateNumber = "J1BIS42LFRUK68049",
                            RentCost = 2964.7214020071274,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("423d704d-71fe-448e-ba68-91703a29fb93"),
                            FuelType = 1,
                            ModelId = new Guid("5c8603db-1cf4-47a0-a02b-8164425ccace"),
                            Odo = 5821,
                            PlateNumber = "YWUYLUPIFRAM29462",
                            RentCost = 2495.7119213079177,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("314c741e-9539-4c37-bef2-111c70ad4f8e"),
                            FuelType = 1,
                            ModelId = new Guid("5c8603db-1cf4-47a0-a02b-8164425ccace"),
                            Odo = 5415,
                            PlateNumber = "H3JEJ7HLZFGD82968",
                            RentCost = 2441.3741835011269,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("93382c74-7bb2-461c-b246-ecb37abfd8f5"),
                            FuelType = 2,
                            ModelId = new Guid("5c8603db-1cf4-47a0-a02b-8164425ccace"),
                            Odo = 749,
                            PlateNumber = "EEP7QMYLXLT848219",
                            RentCost = 2816.4060542625934,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("b568a9cb-5a77-499a-b3ea-2f386a567d2d"),
                            FuelType = 3,
                            ModelId = new Guid("5c8603db-1cf4-47a0-a02b-8164425ccace"),
                            Odo = 8884,
                            PlateNumber = "SCJ6G4ISNATQ14017",
                            RentCost = 1946.6836780830679,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("21efec8f-8c8f-4a77-9d41-4ffa3da992d5"),
                            FuelType = 0,
                            ModelId = new Guid("5c8603db-1cf4-47a0-a02b-8164425ccace"),
                            Odo = 5888,
                            PlateNumber = "EVTJSJECRVRA75804",
                            RentCost = 593.22683076907379,
                            VehicleState = 3,
                            VehicleType = 3
                        });
                });

            modelBuilder.Entity("DAL.Entities.VehicleClientHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleClientHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55cf98a8-9065-48d0-8d01-cfff7c9fbaa4"),
                            ClientId = new Guid("c5aebbda-44d9-4ddc-8544-521aec01812f"),
                            EndDate = new DateTime(2023, 6, 24, 21, 20, 27, 191, DateTimeKind.Utc).AddTicks(5758),
                            StartDate = new DateTime(2024, 5, 1, 21, 49, 14, 200, DateTimeKind.Utc).AddTicks(186),
                            VehicleId = new Guid("de527ef4-5333-4313-aeac-b896fb295ff8")
                        },
                        new
                        {
                            Id = new Guid("1aa4fecb-c7bd-4e29-b79e-560bb656c913"),
                            ClientId = new Guid("c5aebbda-44d9-4ddc-8544-521aec01812f"),
                            EndDate = new DateTime(2024, 2, 28, 20, 9, 12, 351, DateTimeKind.Utc).AddTicks(5644),
                            StartDate = new DateTime(2023, 6, 24, 14, 41, 26, 922, DateTimeKind.Utc).AddTicks(5122),
                            VehicleId = new Guid("314c741e-9539-4c37-bef2-111c70ad4f8e")
                        },
                        new
                        {
                            Id = new Guid("af802c8d-58ed-42e4-adef-dd8dc9068a02"),
                            ClientId = new Guid("c5aebbda-44d9-4ddc-8544-521aec01812f"),
                            EndDate = new DateTime(2023, 7, 13, 6, 49, 45, 147, DateTimeKind.Utc).AddTicks(5818),
                            StartDate = new DateTime(2024, 3, 27, 12, 34, 54, 32, DateTimeKind.Utc).AddTicks(9357),
                            VehicleId = new Guid("c12a50e5-2a38-4c7e-b89f-e0b23eba0b20")
                        },
                        new
                        {
                            Id = new Guid("104e2c82-b906-4f90-be62-add9013bb3ca"),
                            ClientId = new Guid("c5aebbda-44d9-4ddc-8544-521aec01812f"),
                            EndDate = new DateTime(2024, 5, 27, 8, 44, 52, 22, DateTimeKind.Utc).AddTicks(6102),
                            StartDate = new DateTime(2024, 1, 23, 11, 48, 56, 964, DateTimeKind.Utc).AddTicks(7619),
                            VehicleId = new Guid("11b2a283-5c68-430f-9133-7adaf57602b1")
                        },
                        new
                        {
                            Id = new Guid("8c3274ac-dc36-4bd7-b1d6-c09020491952"),
                            ClientId = new Guid("c5aebbda-44d9-4ddc-8544-521aec01812f"),
                            EndDate = new DateTime(2024, 2, 4, 18, 0, 48, 314, DateTimeKind.Utc).AddTicks(1028),
                            StartDate = new DateTime(2024, 4, 11, 17, 50, 18, 264, DateTimeKind.Utc).AddTicks(387),
                            VehicleId = new Guid("c05332ca-5c1e-482d-83a9-47178d3e9725")
                        });
                });

            modelBuilder.Entity("DAL.Entities.ModelName", b =>
                {
                    b.HasOne("DAL.Entities.Manufacturer", "Manufacturer")
                        .WithMany("ModelNames")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DAL.Entities.Vehicle", b =>
                {
                    b.HasOne("DAL.Entities.ModelName", "ModelName")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelNameId");

                    b.Navigation("ModelName");
                });

            modelBuilder.Entity("DAL.Entities.VehicleClientHistory", b =>
                {
                    b.HasOne("DAL.Entities.Client", "Client")
                        .WithMany("VehicleClientHistory")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleClientHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DAL.Entities.Client", b =>
                {
                    b.Navigation("VehicleClientHistory");
                });

            modelBuilder.Entity("DAL.Entities.Manufacturer", b =>
                {
                    b.Navigation("ModelNames");
                });

            modelBuilder.Entity("DAL.Entities.ModelName", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DAL.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleClientHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
