// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AgencyDbContext))]
    [Migration("20240613090357_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7d576f3-a9f7-440e-9c34-2289923d464b"),
                            ManufacturerId = new Guid("33033254-55f6-4f3b-a8d2-c9dd071ffbd1"),
                            Name = "Volt"
                        },
                        new
                        {
                            Id = new Guid("c22744ad-e7e4-4083-9da8-68d3de702289"),
                            ManufacturerId = new Guid("33033254-55f6-4f3b-a8d2-c9dd071ffbd1"),
                            Name = "Escalade"
                        },
                        new
                        {
                            Id = new Guid("79034739-1060-4346-a39b-3800e3651960"),
                            ManufacturerId = new Guid("33033254-55f6-4f3b-a8d2-c9dd071ffbd1"),
                            Name = "Fiesta"
                        },
                        new
                        {
                            Id = new Guid("50433eaf-f309-4a9f-b603-d2a14e59701b"),
                            ManufacturerId = new Guid("33033254-55f6-4f3b-a8d2-c9dd071ffbd1"),
                            Name = "Camry"
                        },
                        new
                        {
                            Id = new Guid("44561354-904e-4ac5-bd97-10415a0d1585"),
                            ManufacturerId = new Guid("33033254-55f6-4f3b-a8d2-c9dd071ffbd1"),
                            Name = "2"
                        },
                        new
                        {
                            Id = new Guid("602fd8a7-57f7-4662-b82f-5351c7351af3"),
                            ManufacturerId = new Guid("be7f8ca5-7c97-4574-96a8-d7da0a317ffb"),
                            Name = "CX-9"
                        },
                        new
                        {
                            Id = new Guid("5e58ca15-9a3d-49ba-8054-8ea280e92980"),
                            ManufacturerId = new Guid("be7f8ca5-7c97-4574-96a8-d7da0a317ffb"),
                            Name = "Focus"
                        },
                        new
                        {
                            Id = new Guid("95b7414f-dc5a-4bb1-831e-bd915d295713"),
                            ManufacturerId = new Guid("be7f8ca5-7c97-4574-96a8-d7da0a317ffb"),
                            Name = "A8"
                        },
                        new
                        {
                            Id = new Guid("4387099b-8477-4ab3-a04c-5f8cd225ebdc"),
                            ManufacturerId = new Guid("be7f8ca5-7c97-4574-96a8-d7da0a317ffb"),
                            Name = "Focus"
                        },
                        new
                        {
                            Id = new Guid("34ce56cd-f2b9-495b-a839-7a9d285e0115"),
                            ManufacturerId = new Guid("be7f8ca5-7c97-4574-96a8-d7da0a317ffb"),
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = new Guid("eedb2e04-0223-4ab0-bbac-aa43b37b6d95"),
                            ManufacturerId = new Guid("4b3a93c1-aae1-4239-9b92-79a69ef177f7"),
                            Name = "Countach"
                        },
                        new
                        {
                            Id = new Guid("ee86b2a2-2428-4053-917b-9a5fef50d789"),
                            ManufacturerId = new Guid("4b3a93c1-aae1-4239-9b92-79a69ef177f7"),
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = new Guid("bffaddb9-36c2-484a-b968-78afa974fcac"),
                            ManufacturerId = new Guid("4b3a93c1-aae1-4239-9b92-79a69ef177f7"),
                            Name = "Spyder"
                        },
                        new
                        {
                            Id = new Guid("8e169234-04b3-48e5-9518-c21cd39f2c7f"),
                            ManufacturerId = new Guid("4b3a93c1-aae1-4239-9b92-79a69ef177f7"),
                            Name = "Impala"
                        },
                        new
                        {
                            Id = new Guid("9995fc8c-3844-4c97-8c99-e0bcfc360cad"),
                            ManufacturerId = new Guid("4b3a93c1-aae1-4239-9b92-79a69ef177f7"),
                            Name = "Element"
                        },
                        new
                        {
                            Id = new Guid("45f39368-4456-433c-ad9b-edaa7783e343"),
                            ManufacturerId = new Guid("c1893305-d1ba-4930-941e-00e2279a5d49"),
                            Name = "V90"
                        },
                        new
                        {
                            Id = new Guid("0cae08a1-e2de-4790-a1aa-5d3e91060acc"),
                            ManufacturerId = new Guid("c1893305-d1ba-4930-941e-00e2279a5d49"),
                            Name = "Focus"
                        },
                        new
                        {
                            Id = new Guid("703ff426-1d0e-403c-bfd6-664927657232"),
                            ManufacturerId = new Guid("c1893305-d1ba-4930-941e-00e2279a5d49"),
                            Name = "Mercielago"
                        },
                        new
                        {
                            Id = new Guid("15bf6bbf-a110-4a88-bc5e-8b4c47510b44"),
                            ManufacturerId = new Guid("c1893305-d1ba-4930-941e-00e2279a5d49"),
                            Name = "A8"
                        },
                        new
                        {
                            Id = new Guid("8ae805d5-0d78-4c71-bd7b-799b49a3a774"),
                            ManufacturerId = new Guid("c1893305-d1ba-4930-941e-00e2279a5d49"),
                            Name = "LeBaron"
                        },
                        new
                        {
                            Id = new Guid("4d54f5ee-5813-4c5e-9246-c065a85c99b9"),
                            ManufacturerId = new Guid("b6a7711c-a5ce-4197-9a36-a0e9c957a0bc"),
                            Name = "Wrangler"
                        },
                        new
                        {
                            Id = new Guid("ea1cc4b7-c655-4b48-8297-557e2d3fbff0"),
                            ManufacturerId = new Guid("b6a7711c-a5ce-4197-9a36-a0e9c957a0bc"),
                            Name = "Focus"
                        },
                        new
                        {
                            Id = new Guid("81ab22e6-6240-4b31-8586-2475de8edc51"),
                            ManufacturerId = new Guid("b6a7711c-a5ce-4197-9a36-a0e9c957a0bc"),
                            Name = "Grand Caravan"
                        },
                        new
                        {
                            Id = new Guid("db15f770-f6dc-4c94-a3ad-6799ed7df34a"),
                            ManufacturerId = new Guid("b6a7711c-a5ce-4197-9a36-a0e9c957a0bc"),
                            Name = "Ranchero"
                        },
                        new
                        {
                            Id = new Guid("cd76eccf-a3f0-4680-b90a-0b19b10c4d48"),
                            ManufacturerId = new Guid("b6a7711c-a5ce-4197-9a36-a0e9c957a0bc"),
                            Name = "XC90"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5da0b549-709d-42a7-911a-40c53532dd3b"),
                            Email = "Aurelia_Hirthe40@gmail.com",
                            FirstName = "Deja",
                            LastName = "Keebler",
                            PhoneNumber = "732.527.1470"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33033254-55f6-4f3b-a8d2-c9dd071ffbd1"),
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = new Guid("be7f8ca5-7c97-4574-96a8-d7da0a317ffb"),
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = new Guid("4b3a93c1-aae1-4239-9b92-79a69ef177f7"),
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = new Guid("c1893305-d1ba-4930-941e-00e2279a5d49"),
                            Name = "Mercedes Benz"
                        },
                        new
                        {
                            Id = new Guid("b6a7711c-a5ce-4197-9a36-a0e9c957a0bc"),
                            Name = "Tesla"
                        });
                });

            modelBuilder.Entity("DAL.Entities.VehicleClientHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleClientHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07ab88f5-ad1a-44ba-8d06-3bd0017c494f"),
                            ClientId = new Guid("5da0b549-709d-42a7-911a-40c53532dd3b"),
                            EndDate = new DateTime(2023, 6, 25, 21, 0, 29, 156, DateTimeKind.Utc).AddTicks(1853),
                            StartDate = new DateTime(2023, 6, 24, 4, 15, 42, 279, DateTimeKind.Utc).AddTicks(1620),
                            VehicleId = new Guid("dbc10c30-4a5b-4f91-9791-78bceec204f5")
                        },
                        new
                        {
                            Id = new Guid("4bad2048-9b59-4b98-9bc0-3e189e414317"),
                            ClientId = new Guid("5da0b549-709d-42a7-911a-40c53532dd3b"),
                            EndDate = new DateTime(2023, 8, 27, 21, 39, 1, 386, DateTimeKind.Utc).AddTicks(1114),
                            StartDate = new DateTime(2023, 10, 22, 7, 21, 17, 585, DateTimeKind.Utc).AddTicks(9345),
                            VehicleId = new Guid("e2722fa0-d09f-4b98-b551-0c681a82cf32")
                        },
                        new
                        {
                            Id = new Guid("4a7cd805-a270-4ea4-9b3c-56cb218e11ee"),
                            ClientId = new Guid("5da0b549-709d-42a7-911a-40c53532dd3b"),
                            EndDate = new DateTime(2024, 4, 29, 0, 25, 0, 602, DateTimeKind.Utc).AddTicks(7713),
                            StartDate = new DateTime(2024, 6, 8, 7, 41, 50, 274, DateTimeKind.Utc).AddTicks(1155),
                            VehicleId = new Guid("3bd49b40-1472-4a04-bd6c-acea90b50d8d")
                        },
                        new
                        {
                            Id = new Guid("d0e6f9af-04b5-4f1d-bf5a-9ff3bfe3588d"),
                            ClientId = new Guid("5da0b549-709d-42a7-911a-40c53532dd3b"),
                            EndDate = new DateTime(2024, 5, 4, 23, 14, 25, 962, DateTimeKind.Utc).AddTicks(3965),
                            StartDate = new DateTime(2023, 12, 4, 13, 24, 10, 501, DateTimeKind.Utc).AddTicks(1209),
                            VehicleId = new Guid("89e81961-7efb-469b-a9d5-c6ec7f973228")
                        },
                        new
                        {
                            Id = new Guid("455b43fe-2e14-4824-bffb-4623bed2f887"),
                            ClientId = new Guid("5da0b549-709d-42a7-911a-40c53532dd3b"),
                            EndDate = new DateTime(2023, 8, 28, 15, 29, 4, 860, DateTimeKind.Utc).AddTicks(6878),
                            StartDate = new DateTime(2024, 4, 10, 12, 42, 43, 950, DateTimeKind.Utc).AddTicks(9321),
                            VehicleId = new Guid("e2722fa0-d09f-4b98-b551-0c681a82cf32")
                        });
                });

            modelBuilder.Entity("DAL.Entities.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModelNameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Odo")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RentCost")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleState")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelNameId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38024e9f-36df-4168-a2d9-c62821219642"),
                            FuelType = 1,
                            ModelId = new Guid("b7d576f3-a9f7-440e-9c34-2289923d464b"),
                            Odo = 5094,
                            PlateNumber = "VQ6GECSSJDW628881",
                            RentCost = 3908.2002615417355,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("3bee9412-17d4-4265-9ad8-2f40f273bdf0"),
                            FuelType = 1,
                            ModelId = new Guid("b7d576f3-a9f7-440e-9c34-2289923d464b"),
                            Odo = 7815,
                            PlateNumber = "AWCZ3EV4H8TX41366",
                            RentCost = 3100.2564217338772,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("5cd498c0-7aa2-4a6a-a6b4-200481b1ecc3"),
                            FuelType = 2,
                            ModelId = new Guid("b7d576f3-a9f7-440e-9c34-2289923d464b"),
                            Odo = 8892,
                            PlateNumber = "XAKM0N9XC5EM27695",
                            RentCost = 3292.6074243568928,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("02bdb585-9037-46bd-9fee-b6387820d4ae"),
                            FuelType = 0,
                            ModelId = new Guid("b7d576f3-a9f7-440e-9c34-2289923d464b"),
                            Odo = 7704,
                            PlateNumber = "OLSMKUFGGQUH62585",
                            RentCost = 693.33826474577199,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("a1b4de89-a964-4e06-93e4-32616a99b28f"),
                            FuelType = 1,
                            ModelId = new Guid("b7d576f3-a9f7-440e-9c34-2289923d464b"),
                            Odo = 6721,
                            PlateNumber = "Q2CBZNAEKMWX95385",
                            RentCost = 2437.4293765347165,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6f64fd2b-b878-41ac-8ee9-b3530c805396"),
                            FuelType = 1,
                            ModelId = new Guid("c22744ad-e7e4-4083-9da8-68d3de702289"),
                            Odo = 9749,
                            PlateNumber = "1DJI9YAZOWIB19126",
                            RentCost = 2412.4581076387299,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("abde47ef-0186-4e8b-b9db-e2b0e82b8bcc"),
                            FuelType = 3,
                            ModelId = new Guid("c22744ad-e7e4-4083-9da8-68d3de702289"),
                            Odo = 3989,
                            PlateNumber = "PFMJFUURWEMQ85619",
                            RentCost = 1065.1524140114361,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("47ac843e-4cf8-4d52-bb77-82dc79a8cc66"),
                            FuelType = 2,
                            ModelId = new Guid("c22744ad-e7e4-4083-9da8-68d3de702289"),
                            Odo = 7215,
                            PlateNumber = "HO4300YG4KDK63786",
                            RentCost = 2873.9558369302054,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("538d25be-9805-4061-b559-4f47a1a58dcf"),
                            FuelType = 0,
                            ModelId = new Guid("c22744ad-e7e4-4083-9da8-68d3de702289"),
                            Odo = 1737,
                            PlateNumber = "UTLRMQ1ZUFF953552",
                            RentCost = 3502.6600331214436,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("b3bfd9f4-5e4e-4ba2-b8a8-c9050a10a0ec"),
                            FuelType = 2,
                            ModelId = new Guid("c22744ad-e7e4-4083-9da8-68d3de702289"),
                            Odo = 8473,
                            PlateNumber = "MTY2WIWKLCC831389",
                            RentCost = 1144.3321538621381,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("244e81ec-3e62-462e-8daf-101ce9ba93fb"),
                            FuelType = 2,
                            ModelId = new Guid("79034739-1060-4346-a39b-3800e3651960"),
                            Odo = 4517,
                            PlateNumber = "TWDRGUU1XABA76236",
                            RentCost = 910.49826017275529,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("9a685f64-f625-4d27-9ea6-13501258ccb4"),
                            FuelType = 0,
                            ModelId = new Guid("79034739-1060-4346-a39b-3800e3651960"),
                            Odo = 9933,
                            PlateNumber = "WHZJXMHV8OEI17073",
                            RentCost = 3949.6318946599931,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("d7d2a61b-57c0-461a-b268-df00bc5a8a2a"),
                            FuelType = 0,
                            ModelId = new Guid("79034739-1060-4346-a39b-3800e3651960"),
                            Odo = 3947,
                            PlateNumber = "AJ2H41NIALKJ45606",
                            RentCost = 1328.8014275830105,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("782a6007-8316-4345-ae2a-3e4c5bc0550d"),
                            FuelType = 2,
                            ModelId = new Guid("79034739-1060-4346-a39b-3800e3651960"),
                            Odo = 5528,
                            PlateNumber = "887306Q4QIAD96882",
                            RentCost = 3097.9350801498745,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("eb99eac3-d6a0-456a-8d65-eb94ba9a64b5"),
                            FuelType = 2,
                            ModelId = new Guid("79034739-1060-4346-a39b-3800e3651960"),
                            Odo = 460,
                            PlateNumber = "U3B3Z0A24WBP31037",
                            RentCost = 1893.3374230949175,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("eeb7722a-80ad-43ce-90cb-c4d7f217f752"),
                            FuelType = 1,
                            ModelId = new Guid("50433eaf-f309-4a9f-b603-d2a14e59701b"),
                            Odo = 203,
                            PlateNumber = "4L8TWMEHCSF018179",
                            RentCost = 1937.4305130505288,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4548b1cb-83b9-4cc7-a8e2-aca462c2239c"),
                            FuelType = 1,
                            ModelId = new Guid("50433eaf-f309-4a9f-b603-d2a14e59701b"),
                            Odo = 1487,
                            PlateNumber = "KFKKLTVZ5TYA52104",
                            RentCost = 3225.9165076959339,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("dea3935a-b76b-46aa-a6ed-d2a2e5e6a545"),
                            FuelType = 0,
                            ModelId = new Guid("50433eaf-f309-4a9f-b603-d2a14e59701b"),
                            Odo = 6850,
                            PlateNumber = "53JG4EY0QLDC72452",
                            RentCost = 2479.9299593447558,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("11b9f524-f621-44e8-b175-ec191ea4a48e"),
                            FuelType = 3,
                            ModelId = new Guid("50433eaf-f309-4a9f-b603-d2a14e59701b"),
                            Odo = 2591,
                            PlateNumber = "2US6Q8CED7LL25227",
                            RentCost = 3664.1969113054201,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("bf5d35d3-5c76-4000-8ed5-eaf86f534e04"),
                            FuelType = 0,
                            ModelId = new Guid("50433eaf-f309-4a9f-b603-d2a14e59701b"),
                            Odo = 8521,
                            PlateNumber = "FQJ6FDSHP5AW20346",
                            RentCost = 2444.6885333543332,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("768f480c-49f6-49ac-abd7-bc248eb92d54"),
                            FuelType = 0,
                            ModelId = new Guid("44561354-904e-4ac5-bd97-10415a0d1585"),
                            Odo = 3217,
                            PlateNumber = "ENMO45AFLNRV53448",
                            RentCost = 3619.3822536945831,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("31151c8a-b801-4f5e-8fd4-d092abc5cfd6"),
                            FuelType = 1,
                            ModelId = new Guid("44561354-904e-4ac5-bd97-10415a0d1585"),
                            Odo = 2204,
                            PlateNumber = "H0TT07WO5ISC50353",
                            RentCost = 3257.4311021946905,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("9172ab35-7cf3-48ac-9cbe-37b30131c467"),
                            FuelType = 1,
                            ModelId = new Guid("44561354-904e-4ac5-bd97-10415a0d1585"),
                            Odo = 5336,
                            PlateNumber = "727VZW6QOSGH72308",
                            RentCost = 1295.6064865532226,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("d3e25e66-7d90-43cd-ad1f-d69f22493786"),
                            FuelType = 3,
                            ModelId = new Guid("44561354-904e-4ac5-bd97-10415a0d1585"),
                            Odo = 8026,
                            PlateNumber = "MCVOAC40VYV085998",
                            RentCost = 1579.9343236179368,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("8ff89c2c-635b-4f38-a02f-b6794160a789"),
                            FuelType = 3,
                            ModelId = new Guid("44561354-904e-4ac5-bd97-10415a0d1585"),
                            Odo = 374,
                            PlateNumber = "HMBRAO884HBN68770",
                            RentCost = 1557.2330785261638,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("9c02cf28-1708-4ba4-85a7-bbb740bf7b1e"),
                            FuelType = 1,
                            ModelId = new Guid("602fd8a7-57f7-4662-b82f-5351c7351af3"),
                            Odo = 5551,
                            PlateNumber = "G7FBV7CFA7UW63103",
                            RentCost = 3979.6428673307041,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("47e675f4-ecf6-4325-90ef-93e16d86e8e0"),
                            FuelType = 2,
                            ModelId = new Guid("602fd8a7-57f7-4662-b82f-5351c7351af3"),
                            Odo = 7182,
                            PlateNumber = "95GM37TCNKVY41638",
                            RentCost = 1738.4591707470286,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("f5389ea0-1dbc-4c8b-aff1-734e7bf864a8"),
                            FuelType = 3,
                            ModelId = new Guid("602fd8a7-57f7-4662-b82f-5351c7351af3"),
                            Odo = 4827,
                            PlateNumber = "AII4DLO5AFL563487",
                            RentCost = 1845.0779876994732,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("45b0a26b-879e-41b3-ac9e-602d70d3c29e"),
                            FuelType = 1,
                            ModelId = new Guid("602fd8a7-57f7-4662-b82f-5351c7351af3"),
                            Odo = 2476,
                            PlateNumber = "QOS39CFOASPH62418",
                            RentCost = 2025.6523326295496,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4a298220-efc3-4a66-a3f0-f58fde993dc1"),
                            FuelType = 0,
                            ModelId = new Guid("602fd8a7-57f7-4662-b82f-5351c7351af3"),
                            Odo = 9076,
                            PlateNumber = "YTNKAWY5AJNU89675",
                            RentCost = 2062.8500094562442,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("10763b92-bfcf-45d2-ad3b-50c1e1184b40"),
                            FuelType = 1,
                            ModelId = new Guid("5e58ca15-9a3d-49ba-8054-8ea280e92980"),
                            Odo = 2420,
                            PlateNumber = "HJKHSUBQ7KN973582",
                            RentCost = 115.23149514356473,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("8838c6b1-c43f-45dd-9eef-4bf84d6aa712"),
                            FuelType = 3,
                            ModelId = new Guid("5e58ca15-9a3d-49ba-8054-8ea280e92980"),
                            Odo = 386,
                            PlateNumber = "V0KM7Y9Q10BX88302",
                            RentCost = 2367.9353224899965,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("b21131c0-1da9-4fb0-8935-6edc729d9d84"),
                            FuelType = 1,
                            ModelId = new Guid("5e58ca15-9a3d-49ba-8054-8ea280e92980"),
                            Odo = 6575,
                            PlateNumber = "N8EAHIAZ9RZ296656",
                            RentCost = 3322.819743113429,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("a8976017-657e-4ee5-b6e7-eb07e2232812"),
                            FuelType = 2,
                            ModelId = new Guid("5e58ca15-9a3d-49ba-8054-8ea280e92980"),
                            Odo = 9223,
                            PlateNumber = "LE5DDDZX0BXY75716",
                            RentCost = 2301.0439891306391,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("e566093e-912d-4b63-aec6-948fd0e4a6a1"),
                            FuelType = 0,
                            ModelId = new Guid("5e58ca15-9a3d-49ba-8054-8ea280e92980"),
                            Odo = 8141,
                            PlateNumber = "ZE0X1QPLHBF324687",
                            RentCost = 601.61277961403607,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("15c33d7f-8675-4841-b7b8-7d4a6c947db3"),
                            FuelType = 2,
                            ModelId = new Guid("95b7414f-dc5a-4bb1-831e-bd915d295713"),
                            Odo = 6352,
                            PlateNumber = "EZJFA1HHFEMX59110",
                            RentCost = 2736.1873562388141,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("923576ca-472a-4e52-849e-d1c01067c8da"),
                            FuelType = 3,
                            ModelId = new Guid("95b7414f-dc5a-4bb1-831e-bd915d295713"),
                            Odo = 101,
                            PlateNumber = "L10TIY1JAUPN51822",
                            RentCost = 2255.4564375101395,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("89e81961-7efb-469b-a9d5-c6ec7f973228"),
                            FuelType = 3,
                            ModelId = new Guid("95b7414f-dc5a-4bb1-831e-bd915d295713"),
                            Odo = 1473,
                            PlateNumber = "WT9Y001MSYVA34984",
                            RentCost = 3552.5784929035426,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("82ae790e-2fc3-43e6-9d44-910d16b8c0b8"),
                            FuelType = 1,
                            ModelId = new Guid("95b7414f-dc5a-4bb1-831e-bd915d295713"),
                            Odo = 514,
                            PlateNumber = "MXCP0KZHN1U239800",
                            RentCost = 1232.2532895763561,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4f8d8c54-76fc-4b8a-8e4f-3d529df898bd"),
                            FuelType = 3,
                            ModelId = new Guid("95b7414f-dc5a-4bb1-831e-bd915d295713"),
                            Odo = 5847,
                            PlateNumber = "LHD5K8FM83A364003",
                            RentCost = 3115.5767437333852,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("1da3a269-d59c-4b5a-99ba-4a75c28ed7e6"),
                            FuelType = 0,
                            ModelId = new Guid("4387099b-8477-4ab3-a04c-5f8cd225ebdc"),
                            Odo = 4089,
                            PlateNumber = "7EEFTYFH9ZKQ12040",
                            RentCost = 564.90221691955583,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("00be6035-a719-406b-9fd1-39313aaf9e16"),
                            FuelType = 1,
                            ModelId = new Guid("4387099b-8477-4ab3-a04c-5f8cd225ebdc"),
                            Odo = 7722,
                            PlateNumber = "5P61VY1ZY5ON67384",
                            RentCost = 2527.028805502775,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("b951e0ae-9ea3-44cc-bc65-b7b7067c4005"),
                            FuelType = 1,
                            ModelId = new Guid("4387099b-8477-4ab3-a04c-5f8cd225ebdc"),
                            Odo = 1886,
                            PlateNumber = "20VYGEQNNNLE60320",
                            RentCost = 426.53266456881829,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("8f97999d-46a0-4873-b2b0-8d45cac96248"),
                            FuelType = 0,
                            ModelId = new Guid("4387099b-8477-4ab3-a04c-5f8cd225ebdc"),
                            Odo = 538,
                            PlateNumber = "U4DH6HV1PQEJ94847",
                            RentCost = 3141.504362870533,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("6e93c7b8-54ea-4d6d-b893-789e4ac22819"),
                            FuelType = 0,
                            ModelId = new Guid("4387099b-8477-4ab3-a04c-5f8cd225ebdc"),
                            Odo = 820,
                            PlateNumber = "R9DM4TFP0KRK89779",
                            RentCost = 1669.0446185832534,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("dbc10c30-4a5b-4f91-9791-78bceec204f5"),
                            FuelType = 0,
                            ModelId = new Guid("34ce56cd-f2b9-495b-a839-7a9d285e0115"),
                            Odo = 4255,
                            PlateNumber = "LZEDB0AP3PZ946102",
                            RentCost = 1453.4188973053992,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f7b540db-9d79-4674-a182-d83ca8521370"),
                            FuelType = 1,
                            ModelId = new Guid("34ce56cd-f2b9-495b-a839-7a9d285e0115"),
                            Odo = 7238,
                            PlateNumber = "4KBXJHANVAN049703",
                            RentCost = 493.76313627594192,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("53e3af5e-c876-4534-9ada-47affc8e3a29"),
                            FuelType = 2,
                            ModelId = new Guid("34ce56cd-f2b9-495b-a839-7a9d285e0115"),
                            Odo = 5922,
                            PlateNumber = "RZLO1PFCFTSW61011",
                            RentCost = 1242.3798766909558,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("e4914beb-0204-4497-83a0-b65b56186a90"),
                            FuelType = 1,
                            ModelId = new Guid("34ce56cd-f2b9-495b-a839-7a9d285e0115"),
                            Odo = 3627,
                            PlateNumber = "C2KP1UUFMQQQ82949",
                            RentCost = 2451.8922634038163,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("df18d420-db36-4472-8b1b-e33b134f5001"),
                            FuelType = 1,
                            ModelId = new Guid("34ce56cd-f2b9-495b-a839-7a9d285e0115"),
                            Odo = 4966,
                            PlateNumber = "D2M2I9D9ULUU99898",
                            RentCost = 610.25924701163331,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("446cf47a-498e-4f51-b443-e2df15fc727a"),
                            FuelType = 3,
                            ModelId = new Guid("eedb2e04-0223-4ab0-bbac-aa43b37b6d95"),
                            Odo = 5186,
                            PlateNumber = "WOACESWFFXC647328",
                            RentCost = 2660.3450193888189,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("750da4bb-9e92-4529-9f47-811538035d39"),
                            FuelType = 0,
                            ModelId = new Guid("eedb2e04-0223-4ab0-bbac-aa43b37b6d95"),
                            Odo = 733,
                            PlateNumber = "H7AQB5AM6DFH57756",
                            RentCost = 2242.3684808137205,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("0c9ca35e-6927-4cf2-9acc-fe3cd817fc40"),
                            FuelType = 3,
                            ModelId = new Guid("eedb2e04-0223-4ab0-bbac-aa43b37b6d95"),
                            Odo = 3664,
                            PlateNumber = "WD1VR99LFJT257414",
                            RentCost = 1685.2751859954187,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("e2722fa0-d09f-4b98-b551-0c681a82cf32"),
                            FuelType = 2,
                            ModelId = new Guid("eedb2e04-0223-4ab0-bbac-aa43b37b6d95"),
                            Odo = 5815,
                            PlateNumber = "NQE4O6BSQ4DE50392",
                            RentCost = 318.60551016501847,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("6942e5ab-153b-477f-87fa-589aada8c0e4"),
                            FuelType = 1,
                            ModelId = new Guid("eedb2e04-0223-4ab0-bbac-aa43b37b6d95"),
                            Odo = 3670,
                            PlateNumber = "3E8WPOWR7CM686398",
                            RentCost = 3344.5251315146861,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("e46efc08-49f1-43fe-83b0-a79ec820a8d9"),
                            FuelType = 1,
                            ModelId = new Guid("ee86b2a2-2428-4053-917b-9a5fef50d789"),
                            Odo = 4689,
                            PlateNumber = "EUZC11TH6MDE61673",
                            RentCost = 1112.4091283222542,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("fbe42799-0a4c-4970-ac0f-38c02e8c0ed5"),
                            FuelType = 3,
                            ModelId = new Guid("ee86b2a2-2428-4053-917b-9a5fef50d789"),
                            Odo = 4267,
                            PlateNumber = "G1ZHA7GMC4U395314",
                            RentCost = 1345.1164075904464,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("6472dcc5-2e96-44c7-a987-e05007037e6c"),
                            FuelType = 0,
                            ModelId = new Guid("ee86b2a2-2428-4053-917b-9a5fef50d789"),
                            Odo = 2481,
                            PlateNumber = "PKRJ1THMIMII94518",
                            RentCost = 2160.6985150974974,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("4c794350-ba62-47c2-a8ba-2f39b1013f03"),
                            FuelType = 0,
                            ModelId = new Guid("ee86b2a2-2428-4053-917b-9a5fef50d789"),
                            Odo = 4847,
                            PlateNumber = "LRS78V0R3RYN16309",
                            RentCost = 1109.3985304300609,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("6f39f195-1419-4d42-8002-ecfc71593d8e"),
                            FuelType = 3,
                            ModelId = new Guid("ee86b2a2-2428-4053-917b-9a5fef50d789"),
                            Odo = 9295,
                            PlateNumber = "KEWTFWCRSBQ642653",
                            RentCost = 1442.3742433077341,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("21c1407b-5af8-4828-b3df-bb942670c4b3"),
                            FuelType = 0,
                            ModelId = new Guid("bffaddb9-36c2-484a-b968-78afa974fcac"),
                            Odo = 2888,
                            PlateNumber = "XB3X77LN2QQ359801",
                            RentCost = 400.16389433528195,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("8e9aba1e-3dd0-46cb-8e44-c38ced3a1ef3"),
                            FuelType = 1,
                            ModelId = new Guid("bffaddb9-36c2-484a-b968-78afa974fcac"),
                            Odo = 9951,
                            PlateNumber = "33QEHQ9AKTL417061",
                            RentCost = 748.81408590592412,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("927e1c03-7857-4617-a5ad-bec2caa9a88a"),
                            FuelType = 0,
                            ModelId = new Guid("bffaddb9-36c2-484a-b968-78afa974fcac"),
                            Odo = 9835,
                            PlateNumber = "GUSCB6A3DUQN46974",
                            RentCost = 1485.5746662921968,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("9a1ea418-b6f2-4c55-9be8-4b72f5d56d5e"),
                            FuelType = 1,
                            ModelId = new Guid("bffaddb9-36c2-484a-b968-78afa974fcac"),
                            Odo = 4779,
                            PlateNumber = "MBARZH97Z9Q694864",
                            RentCost = 242.68248916891176,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("dd96ba71-2080-40fb-bde1-49dde7b23698"),
                            FuelType = 3,
                            ModelId = new Guid("bffaddb9-36c2-484a-b968-78afa974fcac"),
                            Odo = 7471,
                            PlateNumber = "NM9KABO0ZIAA72504",
                            RentCost = 1306.9742638634457,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("3db17bb2-20d8-4f2b-8243-a0f96379e858"),
                            FuelType = 0,
                            ModelId = new Guid("8e169234-04b3-48e5-9518-c21cd39f2c7f"),
                            Odo = 4749,
                            PlateNumber = "IB7UEOQ3DXNT69710",
                            RentCost = 731.0120835602421,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("79b27d5d-85fd-4166-9057-2179c4336325"),
                            FuelType = 2,
                            ModelId = new Guid("8e169234-04b3-48e5-9518-c21cd39f2c7f"),
                            Odo = 4043,
                            PlateNumber = "DVQ84ZD8Y7DR35451",
                            RentCost = 3838.0699004557459,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("f14fbbf4-76bf-4055-9f9b-006cae06ac0b"),
                            FuelType = 2,
                            ModelId = new Guid("8e169234-04b3-48e5-9518-c21cd39f2c7f"),
                            Odo = 2767,
                            PlateNumber = "4WA8Y88KBMG950825",
                            RentCost = 562.43534454488849,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("17f06459-ebab-4271-a79b-afbef15277f9"),
                            FuelType = 1,
                            ModelId = new Guid("8e169234-04b3-48e5-9518-c21cd39f2c7f"),
                            Odo = 3308,
                            PlateNumber = "0XFR2ZTMRIP717788",
                            RentCost = 3122.9669077444701,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("7d0f2101-d4d6-4a35-8a9e-e31a3d4af432"),
                            FuelType = 0,
                            ModelId = new Guid("8e169234-04b3-48e5-9518-c21cd39f2c7f"),
                            Odo = 1781,
                            PlateNumber = "60RJGFPTDOW161437",
                            RentCost = 3247.0601344374381,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6c866869-5bd0-4466-a4e0-75939c12f43f"),
                            FuelType = 2,
                            ModelId = new Guid("9995fc8c-3844-4c97-8c99-e0bcfc360cad"),
                            Odo = 5320,
                            PlateNumber = "O85887Z6DSPV73647",
                            RentCost = 2559.5853708365721,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("11f179bf-30c2-4593-9050-87afce1aa112"),
                            FuelType = 2,
                            ModelId = new Guid("9995fc8c-3844-4c97-8c99-e0bcfc360cad"),
                            Odo = 2602,
                            PlateNumber = "XXOAPVW7NNV157834",
                            RentCost = 1154.1018424728377,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("97b78eb0-dff7-49b7-90ca-89f4aeae9d1d"),
                            FuelType = 2,
                            ModelId = new Guid("9995fc8c-3844-4c97-8c99-e0bcfc360cad"),
                            Odo = 4905,
                            PlateNumber = "W2WBZ4LOJYGO20575",
                            RentCost = 1964.2106161244046,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("b70c608b-85b6-4235-862e-e9239cb4eb03"),
                            FuelType = 3,
                            ModelId = new Guid("9995fc8c-3844-4c97-8c99-e0bcfc360cad"),
                            Odo = 4588,
                            PlateNumber = "1TYEA6QWYCQD99644",
                            RentCost = 3056.7319506534864,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("a7bc50f8-1415-424d-826f-9e57c12338c6"),
                            FuelType = 1,
                            ModelId = new Guid("9995fc8c-3844-4c97-8c99-e0bcfc360cad"),
                            Odo = 5765,
                            PlateNumber = "E5JCT2EJQNE477385",
                            RentCost = 2588.7853149260973,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("61c0d1ac-693c-47a0-9de8-aa63caac7d64"),
                            FuelType = 1,
                            ModelId = new Guid("45f39368-4456-433c-ad9b-edaa7783e343"),
                            Odo = 7627,
                            PlateNumber = "G057RLGLS1WN33869",
                            RentCost = 966.96979296551717,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("6ac9b28d-1517-4759-917d-8977a1541b3c"),
                            FuelType = 2,
                            ModelId = new Guid("45f39368-4456-433c-ad9b-edaa7783e343"),
                            Odo = 1965,
                            PlateNumber = "N2N1E3BF8EGM66557",
                            RentCost = 2809.7659068949315,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("496b9fad-261c-45a3-b3c7-9ef7dbb06cd0"),
                            FuelType = 1,
                            ModelId = new Guid("45f39368-4456-433c-ad9b-edaa7783e343"),
                            Odo = 9040,
                            PlateNumber = "62BP1G1XNPPP29312",
                            RentCost = 1950.2579431421236,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("1b085255-c951-4318-b233-c6c834356fcd"),
                            FuelType = 1,
                            ModelId = new Guid("45f39368-4456-433c-ad9b-edaa7783e343"),
                            Odo = 6632,
                            PlateNumber = "KW5BXYPR09B099674",
                            RentCost = 501.89836141179285,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("670f5130-e264-49db-bda9-8df326af012a"),
                            FuelType = 2,
                            ModelId = new Guid("45f39368-4456-433c-ad9b-edaa7783e343"),
                            Odo = 3234,
                            PlateNumber = "5NPMXUSUIHCG10113",
                            RentCost = 1124.0457303336852,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("3f6deafd-eafd-49a2-9cbd-9eccaeee911a"),
                            FuelType = 2,
                            ModelId = new Guid("0cae08a1-e2de-4790-a1aa-5d3e91060acc"),
                            Odo = 6112,
                            PlateNumber = "0VMKE2ML3IQ613643",
                            RentCost = 3403.0045672769211,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("de07f4ab-2872-4e63-bf31-d449ca4ed851"),
                            FuelType = 1,
                            ModelId = new Guid("0cae08a1-e2de-4790-a1aa-5d3e91060acc"),
                            Odo = 3528,
                            PlateNumber = "7IA9Y68JJUCA54730",
                            RentCost = 295.92911944626388,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("0cddd240-ee9a-4d30-879b-ba5123f3c22b"),
                            FuelType = 2,
                            ModelId = new Guid("0cae08a1-e2de-4790-a1aa-5d3e91060acc"),
                            Odo = 1092,
                            PlateNumber = "BGPXO8KW48SJ41753",
                            RentCost = 3648.495677067162,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("5cf0fa82-da19-4ec4-b55b-308b47ddcbac"),
                            FuelType = 3,
                            ModelId = new Guid("0cae08a1-e2de-4790-a1aa-5d3e91060acc"),
                            Odo = 5923,
                            PlateNumber = "I975S5OUGNDF17644",
                            RentCost = 1216.6122813215902,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("faa4b28f-91a1-4094-ae5b-6c559277c390"),
                            FuelType = 3,
                            ModelId = new Guid("0cae08a1-e2de-4790-a1aa-5d3e91060acc"),
                            Odo = 5453,
                            PlateNumber = "8V7KG4888KBZ32404",
                            RentCost = 2973.1591687363839,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("a69e8837-a628-40e5-9d03-16502f35b599"),
                            FuelType = 2,
                            ModelId = new Guid("703ff426-1d0e-403c-bfd6-664927657232"),
                            Odo = 2868,
                            PlateNumber = "V7ILO64TY7B634187",
                            RentCost = 3490.3174330292973,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("59ca6ad6-4664-4dba-92d4-a532c67ba3f7"),
                            FuelType = 2,
                            ModelId = new Guid("703ff426-1d0e-403c-bfd6-664927657232"),
                            Odo = 3562,
                            PlateNumber = "454NWQCN2LIZ57424",
                            RentCost = 1774.5622062529451,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("58102c09-5c15-4e36-9b89-d24ad5b98291"),
                            FuelType = 3,
                            ModelId = new Guid("703ff426-1d0e-403c-bfd6-664927657232"),
                            Odo = 81,
                            PlateNumber = "C30N2T6O54MI39561",
                            RentCost = 3631.1928856201066,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("c95e1902-2480-416e-a81e-160b59e5e449"),
                            FuelType = 0,
                            ModelId = new Guid("703ff426-1d0e-403c-bfd6-664927657232"),
                            Odo = 3466,
                            PlateNumber = "NGCJP1EFAETD19096",
                            RentCost = 1778.9095953301774,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("d1a653d6-d565-49ec-97a3-5686d72800d3"),
                            FuelType = 3,
                            ModelId = new Guid("703ff426-1d0e-403c-bfd6-664927657232"),
                            Odo = 5963,
                            PlateNumber = "6X3LSHUITWY187078",
                            RentCost = 3979.0517726401963,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("dba740a9-9070-477b-a3da-e3a1207197e3"),
                            FuelType = 1,
                            ModelId = new Guid("15bf6bbf-a110-4a88-bc5e-8b4c47510b44"),
                            Odo = 5123,
                            PlateNumber = "AJ0FP7S4DPNF53804",
                            RentCost = 1321.6271989951376,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("b53bcca4-d811-4b7f-b074-1eb9662b17b8"),
                            FuelType = 2,
                            ModelId = new Guid("15bf6bbf-a110-4a88-bc5e-8b4c47510b44"),
                            Odo = 3461,
                            PlateNumber = "527Q7D0TJVLX13970",
                            RentCost = 1801.5914961220824,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("3bd49b40-1472-4a04-bd6c-acea90b50d8d"),
                            FuelType = 0,
                            ModelId = new Guid("15bf6bbf-a110-4a88-bc5e-8b4c47510b44"),
                            Odo = 9497,
                            PlateNumber = "RGYX2N0AWNUH14391",
                            RentCost = 3212.0614621721188,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("af3b5a24-796c-45b6-802d-87edac0e0cc4"),
                            FuelType = 3,
                            ModelId = new Guid("15bf6bbf-a110-4a88-bc5e-8b4c47510b44"),
                            Odo = 9254,
                            PlateNumber = "L4BN8Z0AOCSU92534",
                            RentCost = 3058.1908939835307,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("8b5f8d92-ab8f-4583-bfe7-f4099388dc84"),
                            FuelType = 0,
                            ModelId = new Guid("15bf6bbf-a110-4a88-bc5e-8b4c47510b44"),
                            Odo = 8357,
                            PlateNumber = "1J8U1MPYCHPM81865",
                            RentCost = 409.14694021276961,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("a0d22b27-6cc9-4a15-8fbe-b0a93ec4289c"),
                            FuelType = 0,
                            ModelId = new Guid("8ae805d5-0d78-4c71-bd7b-799b49a3a774"),
                            Odo = 973,
                            PlateNumber = "V4K3W7E0BBM280328",
                            RentCost = 1979.5383017298959,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("76f37ce8-1957-4ec1-9f93-a8e287c1e2ce"),
                            FuelType = 1,
                            ModelId = new Guid("8ae805d5-0d78-4c71-bd7b-799b49a3a774"),
                            Odo = 3599,
                            PlateNumber = "UFM4A98O8KLC55263",
                            RentCost = 1515.1963515422754,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("ba784c0f-cc66-4677-ad26-f3b0b737be43"),
                            FuelType = 2,
                            ModelId = new Guid("8ae805d5-0d78-4c71-bd7b-799b49a3a774"),
                            Odo = 2477,
                            PlateNumber = "P433YQBMR9OM68877",
                            RentCost = 2390.6491200764117,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("16101dac-7bb2-4e4e-83be-51a28ba55aa0"),
                            FuelType = 2,
                            ModelId = new Guid("8ae805d5-0d78-4c71-bd7b-799b49a3a774"),
                            Odo = 3242,
                            PlateNumber = "7OG6F1S8F8SC91768",
                            RentCost = 1430.0654789232035,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f9a199f2-5c4b-4c0f-ac81-324665e642e8"),
                            FuelType = 0,
                            ModelId = new Guid("8ae805d5-0d78-4c71-bd7b-799b49a3a774"),
                            Odo = 6759,
                            PlateNumber = "4Q81LIR5H7AW41624",
                            RentCost = 583.43270143449433,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("79d212d3-045f-45e3-8bc2-5a73bd2a36eb"),
                            FuelType = 3,
                            ModelId = new Guid("4d54f5ee-5813-4c5e-9246-c065a85c99b9"),
                            Odo = 7816,
                            PlateNumber = "CCKQYQVDKXSL20440",
                            RentCost = 677.85628659378096,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("d3e2d749-f411-4d2f-be69-5fde49a73eeb"),
                            FuelType = 2,
                            ModelId = new Guid("4d54f5ee-5813-4c5e-9246-c065a85c99b9"),
                            Odo = 6671,
                            PlateNumber = "9W42KVYU8OJC98247",
                            RentCost = 3769.8490324375207,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("a531ee2b-3f11-4ec7-9a72-c15186890739"),
                            FuelType = 2,
                            ModelId = new Guid("4d54f5ee-5813-4c5e-9246-c065a85c99b9"),
                            Odo = 5191,
                            PlateNumber = "ICXVYO8OBURB95521",
                            RentCost = 1593.3804027223368,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("4f8b7f50-2a57-48c6-9170-89f033d2b86f"),
                            FuelType = 3,
                            ModelId = new Guid("4d54f5ee-5813-4c5e-9246-c065a85c99b9"),
                            Odo = 8679,
                            PlateNumber = "PECKFPXG16PI71781",
                            RentCost = 1465.9194183590942,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("42e79489-70e7-4c89-8912-fea0214590f0"),
                            FuelType = 2,
                            ModelId = new Guid("4d54f5ee-5813-4c5e-9246-c065a85c99b9"),
                            Odo = 3542,
                            PlateNumber = "OON9W94808QB70853",
                            RentCost = 315.64282322497041,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("404a789e-7494-4cff-a672-f6d24a5431fe"),
                            FuelType = 2,
                            ModelId = new Guid("ea1cc4b7-c655-4b48-8297-557e2d3fbff0"),
                            Odo = 1567,
                            PlateNumber = "3837S71LPVEG80427",
                            RentCost = 3587.045664381536,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("7aa431a8-c425-41f9-98c9-ca7226d60316"),
                            FuelType = 0,
                            ModelId = new Guid("ea1cc4b7-c655-4b48-8297-557e2d3fbff0"),
                            Odo = 1973,
                            PlateNumber = "E23XU6ILE8MX64598",
                            RentCost = 2291.0589837434554,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("c9584dcd-b427-42f7-a4b5-e977f43c05c4"),
                            FuelType = 2,
                            ModelId = new Guid("ea1cc4b7-c655-4b48-8297-557e2d3fbff0"),
                            Odo = 6576,
                            PlateNumber = "CKYF7KQGEFPQ63223",
                            RentCost = 3351.1321108407283,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6d087d7b-2fca-4ed1-8da8-a36aa973ff9f"),
                            FuelType = 2,
                            ModelId = new Guid("ea1cc4b7-c655-4b48-8297-557e2d3fbff0"),
                            Odo = 81,
                            PlateNumber = "O2FUODLEBWDO93475",
                            RentCost = 1400.6560790769736,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c59a3a8f-3155-469d-9452-ca5b69053b0c"),
                            FuelType = 1,
                            ModelId = new Guid("ea1cc4b7-c655-4b48-8297-557e2d3fbff0"),
                            Odo = 6288,
                            PlateNumber = "L4FFEVRCOUUO50449",
                            RentCost = 3634.641414006931,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("8d89b45f-423c-4133-9cf3-fbcf6ee36532"),
                            FuelType = 0,
                            ModelId = new Guid("81ab22e6-6240-4b31-8586-2475de8edc51"),
                            Odo = 3545,
                            PlateNumber = "4DC2Z2TFAFZK77050",
                            RentCost = 2836.7248072209422,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("fb7fea6a-e9a5-4f45-a8f4-b9011ad7387e"),
                            FuelType = 0,
                            ModelId = new Guid("81ab22e6-6240-4b31-8586-2475de8edc51"),
                            Odo = 9698,
                            PlateNumber = "EAYRVV3CR5HR15390",
                            RentCost = 218.50419556275401,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("da6972b8-7c23-4cac-8b7a-0483799ac322"),
                            FuelType = 3,
                            ModelId = new Guid("81ab22e6-6240-4b31-8586-2475de8edc51"),
                            Odo = 7397,
                            PlateNumber = "OLJKO8RQN7O081713",
                            RentCost = 3121.1362260487231,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("aaaaa1c3-96a4-4233-b013-cb0fe1dd40ed"),
                            FuelType = 2,
                            ModelId = new Guid("81ab22e6-6240-4b31-8586-2475de8edc51"),
                            Odo = 2554,
                            PlateNumber = "OFJCKEZFHUDS21917",
                            RentCost = 1661.6974565308451,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("a50cdf57-6867-4d3e-9b19-e7e9add00783"),
                            FuelType = 3,
                            ModelId = new Guid("81ab22e6-6240-4b31-8586-2475de8edc51"),
                            Odo = 3772,
                            PlateNumber = "AHD5XCXZJDTM82490",
                            RentCost = 3866.9087134807064,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("5a809356-3312-4883-aac2-03e57df5e85d"),
                            FuelType = 3,
                            ModelId = new Guid("db15f770-f6dc-4c94-a3ad-6799ed7df34a"),
                            Odo = 9067,
                            PlateNumber = "LO9OTEBNDXZ116054",
                            RentCost = 3058.2299487996079,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("53c45c17-442e-4962-acc9-f17a1dd8f3c7"),
                            FuelType = 1,
                            ModelId = new Guid("db15f770-f6dc-4c94-a3ad-6799ed7df34a"),
                            Odo = 1992,
                            PlateNumber = "IAATY91OYIW130907",
                            RentCost = 2791.5189720640815,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("07674a44-014c-4091-ab6b-ca40fd132a23"),
                            FuelType = 0,
                            ModelId = new Guid("db15f770-f6dc-4c94-a3ad-6799ed7df34a"),
                            Odo = 2694,
                            PlateNumber = "4CFT91AVMJEM67450",
                            RentCost = 2669.2403603777684,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("0464f160-5894-4798-a48d-e89b7ad760d0"),
                            FuelType = 0,
                            ModelId = new Guid("db15f770-f6dc-4c94-a3ad-6799ed7df34a"),
                            Odo = 4302,
                            PlateNumber = "5E45LYOWHGR628259",
                            RentCost = 1460.7347868621173,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("bd9c217d-58d6-41dc-bd9d-59697f9a7877"),
                            FuelType = 1,
                            ModelId = new Guid("db15f770-f6dc-4c94-a3ad-6799ed7df34a"),
                            Odo = 7281,
                            PlateNumber = "9ZEFLA7R05OJ18297",
                            RentCost = 266.1001381614584,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("e18fe9eb-8948-400c-bb55-cc5de8e609ea"),
                            FuelType = 0,
                            ModelId = new Guid("cd76eccf-a3f0-4680-b90a-0b19b10c4d48"),
                            Odo = 3378,
                            PlateNumber = "QZW2F2ICNTHY42698",
                            RentCost = 3595.9452799517412,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("e46c6467-783d-4540-a931-1b837251d039"),
                            FuelType = 2,
                            ModelId = new Guid("cd76eccf-a3f0-4680-b90a-0b19b10c4d48"),
                            Odo = 711,
                            PlateNumber = "VNADP9D5X3MR21419",
                            RentCost = 2353.0020756198201,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("b378ebbb-e4d6-4027-8466-f7cab9b153ad"),
                            FuelType = 3,
                            ModelId = new Guid("cd76eccf-a3f0-4680-b90a-0b19b10c4d48"),
                            Odo = 7802,
                            PlateNumber = "E515QM9TSCA139047",
                            RentCost = 3674.6122738784852,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("343a615c-e28b-4f45-ba96-041d9f917f37"),
                            FuelType = 0,
                            ModelId = new Guid("cd76eccf-a3f0-4680-b90a-0b19b10c4d48"),
                            Odo = 8143,
                            PlateNumber = "SAMLSNNBHKBQ99550",
                            RentCost = 2036.0845886707107,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("f8214993-0cdd-4c2a-88d0-75b74149a35e"),
                            FuelType = 2,
                            ModelId = new Guid("cd76eccf-a3f0-4680-b90a-0b19b10c4d48"),
                            Odo = 446,
                            PlateNumber = "12XLKLKXMRDM13924",
                            RentCost = 1448.2184584411414,
                            VehicleState = 0,
                            VehicleType = 5
                        });
                });

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.HasOne("DAL.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("ModelNames")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DAL.Entities.VehicleClientHistoryEntity", b =>
                {
                    b.HasOne("DAL.Entities.ClientEntity", "Client")
                        .WithMany("VehicleClientHistory")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.VehicleEntity", "Vehicle")
                        .WithMany("VehicleClientHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DAL.Entities.VehicleEntity", b =>
                {
                    b.HasOne("DAL.Entities.CarModelEntity", "ModelName")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelNameId");

                    b.Navigation("ModelName");
                });

            modelBuilder.Entity("DAL.Entities.CarModelEntity", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DAL.Entities.ClientEntity", b =>
                {
                    b.Navigation("VehicleClientHistory");
                });

            modelBuilder.Entity("DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("ModelNames");
                });

            modelBuilder.Entity("DAL.Entities.VehicleEntity", b =>
                {
                    b.Navigation("VehicleClientHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
