// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AgencyDbContext))]
    [Migration("20240611085235_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("620e1326-bd16-474c-ba79-16356640f3a8"),
                            Email = "Milo.Botsford33@gmail.com",
                            FirstName = "Bette",
                            LastName = "Barton",
                            PhoneNumber = "1-209-931-9131 x886"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0300098-2a0f-4ab5-b987-74af75739d8f"),
                            Name = "Honda"
                        },
                        new
                        {
                            Id = new Guid("fb42c12c-595b-4760-9d0b-f7bcf36d367d"),
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = new Guid("c114a801-3f6d-4eb0-9a60-8e31a5039589"),
                            Name = "Maserati"
                        },
                        new
                        {
                            Id = new Guid("da266208-001c-4ada-ad4f-96978db63c94"),
                            Name = "Rolls Royce"
                        },
                        new
                        {
                            Id = new Guid("a2e3d429-9c44-4cc8-94c7-57f11b0848ac"),
                            Name = "Porsche"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ModelName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cf5ccd2-f87e-4026-8d13-ebbb023c9be6"),
                            ManufacturerId = new Guid("c0300098-2a0f-4ab5-b987-74af75739d8f"),
                            Name = "ATS"
                        },
                        new
                        {
                            Id = new Guid("3fdc8922-31d4-4f81-a804-29aba5c78600"),
                            ManufacturerId = new Guid("c0300098-2a0f-4ab5-b987-74af75739d8f"),
                            Name = "Taurus"
                        },
                        new
                        {
                            Id = new Guid("9eb8a33e-0351-4be0-9f4b-2ce6398fd703"),
                            ManufacturerId = new Guid("c0300098-2a0f-4ab5-b987-74af75739d8f"),
                            Name = "Golf"
                        },
                        new
                        {
                            Id = new Guid("d9f2bff6-0afd-4146-b36f-da2882fa76a6"),
                            ManufacturerId = new Guid("c0300098-2a0f-4ab5-b987-74af75739d8f"),
                            Name = "Ranchero"
                        },
                        new
                        {
                            Id = new Guid("64611803-bcef-4bf8-8132-fee42ebd2d55"),
                            ManufacturerId = new Guid("c0300098-2a0f-4ab5-b987-74af75739d8f"),
                            Name = "PT Cruiser"
                        },
                        new
                        {
                            Id = new Guid("3d60ff96-9955-40f4-9fec-8101045a3365"),
                            ManufacturerId = new Guid("fb42c12c-595b-4760-9d0b-f7bcf36d367d"),
                            Name = "Fiesta"
                        },
                        new
                        {
                            Id = new Guid("3b07cda8-76d4-4989-bf35-07092bf9a35c"),
                            ManufacturerId = new Guid("fb42c12c-595b-4760-9d0b-f7bcf36d367d"),
                            Name = "Silverado"
                        },
                        new
                        {
                            Id = new Guid("fa5e1095-f059-4672-b7e8-cef2bb2c9098"),
                            ManufacturerId = new Guid("fb42c12c-595b-4760-9d0b-f7bcf36d367d"),
                            Name = "Camry"
                        },
                        new
                        {
                            Id = new Guid("c148e18a-88b1-446d-be26-212243cdffb7"),
                            ManufacturerId = new Guid("fb42c12c-595b-4760-9d0b-f7bcf36d367d"),
                            Name = "A4"
                        },
                        new
                        {
                            Id = new Guid("02b35ef0-01cd-4d8a-9b19-3f1e24ee155c"),
                            ManufacturerId = new Guid("fb42c12c-595b-4760-9d0b-f7bcf36d367d"),
                            Name = "Silverado"
                        },
                        new
                        {
                            Id = new Guid("acea193c-79ff-490a-b56b-3eea1c5c9216"),
                            ManufacturerId = new Guid("c114a801-3f6d-4eb0-9a60-8e31a5039589"),
                            Name = "PT Cruiser"
                        },
                        new
                        {
                            Id = new Guid("6c3295fd-474b-4269-84ac-cf60439fbbe9"),
                            ManufacturerId = new Guid("c114a801-3f6d-4eb0-9a60-8e31a5039589"),
                            Name = "Sentra"
                        },
                        new
                        {
                            Id = new Guid("98648004-1d56-44cf-ad84-24b8eeb6ed20"),
                            ManufacturerId = new Guid("c114a801-3f6d-4eb0-9a60-8e31a5039589"),
                            Name = "Silverado"
                        },
                        new
                        {
                            Id = new Guid("1e62b078-df9d-4b57-b963-e071b9729821"),
                            ManufacturerId = new Guid("c114a801-3f6d-4eb0-9a60-8e31a5039589"),
                            Name = "Spyder"
                        },
                        new
                        {
                            Id = new Guid("8b66b146-b82e-4057-a343-a49e8fca8269"),
                            ManufacturerId = new Guid("c114a801-3f6d-4eb0-9a60-8e31a5039589"),
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = new Guid("24a8daaf-8337-459d-b365-125bc0a5554f"),
                            ManufacturerId = new Guid("da266208-001c-4ada-ad4f-96978db63c94"),
                            Name = "Camry"
                        },
                        new
                        {
                            Id = new Guid("d80c6e25-4af7-4c49-97ca-58fa1f3f9e39"),
                            ManufacturerId = new Guid("da266208-001c-4ada-ad4f-96978db63c94"),
                            Name = "Charger"
                        },
                        new
                        {
                            Id = new Guid("21408ca9-511f-4b9c-a360-ec6907d22884"),
                            ManufacturerId = new Guid("da266208-001c-4ada-ad4f-96978db63c94"),
                            Name = "Camry"
                        },
                        new
                        {
                            Id = new Guid("3e8f4dc1-850d-4b56-9f79-eb3bfd8e2c1c"),
                            ManufacturerId = new Guid("da266208-001c-4ada-ad4f-96978db63c94"),
                            Name = "Expedition"
                        },
                        new
                        {
                            Id = new Guid("d36a0d38-25e1-44da-bfdc-2354fcee7ee3"),
                            ManufacturerId = new Guid("da266208-001c-4ada-ad4f-96978db63c94"),
                            Name = "Durango"
                        },
                        new
                        {
                            Id = new Guid("5a57d85e-6ad8-4ad1-9365-6a88076d5da5"),
                            ManufacturerId = new Guid("a2e3d429-9c44-4cc8-94c7-57f11b0848ac"),
                            Name = "El Camino"
                        },
                        new
                        {
                            Id = new Guid("0db382d2-09a9-44a3-9751-a87c3d450cca"),
                            ManufacturerId = new Guid("a2e3d429-9c44-4cc8-94c7-57f11b0848ac"),
                            Name = "A8"
                        },
                        new
                        {
                            Id = new Guid("d8c337a9-c89d-41e1-8c1f-4bee38c64ec1"),
                            ManufacturerId = new Guid("a2e3d429-9c44-4cc8-94c7-57f11b0848ac"),
                            Name = "Fiesta"
                        },
                        new
                        {
                            Id = new Guid("23b61a3c-ce67-4d25-8177-da9c7f8f43ae"),
                            ManufacturerId = new Guid("a2e3d429-9c44-4cc8-94c7-57f11b0848ac"),
                            Name = "Challenger"
                        },
                        new
                        {
                            Id = new Guid("599a7abb-6894-4d72-98a4-26e359262fab"),
                            ManufacturerId = new Guid("a2e3d429-9c44-4cc8-94c7-57f11b0848ac"),
                            Name = "2"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModelNameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Odo")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RentCost")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleState")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelNameId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3c102be-3316-4f82-9f0c-9fd01e900803"),
                            FuelType = 0,
                            ModelId = new Guid("0cf5ccd2-f87e-4026-8d13-ebbb023c9be6"),
                            Odo = 6038,
                            PlateNumber = "GHU0GTZO8QRI65629",
                            RentCost = 2203.224038148393,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("519768bc-91f2-43d7-9a51-2574ddeb3cb6"),
                            FuelType = 2,
                            ModelId = new Guid("0cf5ccd2-f87e-4026-8d13-ebbb023c9be6"),
                            Odo = 660,
                            PlateNumber = "4H8LDHRPNTI457201",
                            RentCost = 2418.5535448430005,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("07aa72ef-bca8-4d4b-bbd1-3de776ad50bc"),
                            FuelType = 3,
                            ModelId = new Guid("0cf5ccd2-f87e-4026-8d13-ebbb023c9be6"),
                            Odo = 5118,
                            PlateNumber = "QP9L9VZWXLNM84817",
                            RentCost = 1597.0541317258915,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("953bb464-19a0-4ba9-893f-e90700b726f7"),
                            FuelType = 1,
                            ModelId = new Guid("0cf5ccd2-f87e-4026-8d13-ebbb023c9be6"),
                            Odo = 6331,
                            PlateNumber = "INPTBUD7JQNM70078",
                            RentCost = 620.25259981552904,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("a18e89ad-f259-407a-af83-4452c753bb84"),
                            FuelType = 2,
                            ModelId = new Guid("0cf5ccd2-f87e-4026-8d13-ebbb023c9be6"),
                            Odo = 9258,
                            PlateNumber = "P4HLQZZFXCNN51612",
                            RentCost = 240.79053504587102,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("745fffd4-116a-4795-a9a3-6729ccc3d00a"),
                            FuelType = 3,
                            ModelId = new Guid("3fdc8922-31d4-4f81-a804-29aba5c78600"),
                            Odo = 7745,
                            PlateNumber = "1K5ZVBJ5BYD691691",
                            RentCost = 336.56903265942447,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("537b287f-affc-47dd-aa2b-0f71ea3de567"),
                            FuelType = 1,
                            ModelId = new Guid("3fdc8922-31d4-4f81-a804-29aba5c78600"),
                            Odo = 9766,
                            PlateNumber = "YR3FFZSWKYQ444783",
                            RentCost = 713.07114407357813,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("6be71611-038e-46fe-a62a-d116df453460"),
                            FuelType = 1,
                            ModelId = new Guid("3fdc8922-31d4-4f81-a804-29aba5c78600"),
                            Odo = 4651,
                            PlateNumber = "QWLFC8IB40H394645",
                            RentCost = 1345.7959469046168,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("685ea0ce-1ef5-40c6-be6a-089a07b712b1"),
                            FuelType = 0,
                            ModelId = new Guid("3fdc8922-31d4-4f81-a804-29aba5c78600"),
                            Odo = 6520,
                            PlateNumber = "OW891YYB9NIU86795",
                            RentCost = 1134.1244473735417,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("186522b6-26c7-4d66-ba7a-568231e772ef"),
                            FuelType = 3,
                            ModelId = new Guid("3fdc8922-31d4-4f81-a804-29aba5c78600"),
                            Odo = 2391,
                            PlateNumber = "Y718Y7O1MLG086679",
                            RentCost = 3582.9712118987982,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("1d259bba-0f40-4393-afa4-135c787607d4"),
                            FuelType = 2,
                            ModelId = new Guid("9eb8a33e-0351-4be0-9f4b-2ce6398fd703"),
                            Odo = 4138,
                            PlateNumber = "PKLB52QUJEJI34478",
                            RentCost = 2445.5318650653271,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("8c0a1598-931e-47a1-99f3-ed3222e965bd"),
                            FuelType = 2,
                            ModelId = new Guid("9eb8a33e-0351-4be0-9f4b-2ce6398fd703"),
                            Odo = 7911,
                            PlateNumber = "4FMI5RZVOFSI99469",
                            RentCost = 3197.3257836845523,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("3b2f312b-9c00-407c-b6c4-85f57b06fd78"),
                            FuelType = 0,
                            ModelId = new Guid("9eb8a33e-0351-4be0-9f4b-2ce6398fd703"),
                            Odo = 6782,
                            PlateNumber = "D8EZZSRNNAPK55329",
                            RentCost = 3239.2241011309416,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("cdb1726d-0881-4a39-97f1-9797f289c9d3"),
                            FuelType = 1,
                            ModelId = new Guid("9eb8a33e-0351-4be0-9f4b-2ce6398fd703"),
                            Odo = 8224,
                            PlateNumber = "TJYRTSE7ZBRY78582",
                            RentCost = 2274.5228800853311,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("11ea5c62-b25e-4b9a-ab59-ff7b03a1e4a6"),
                            FuelType = 1,
                            ModelId = new Guid("9eb8a33e-0351-4be0-9f4b-2ce6398fd703"),
                            Odo = 6498,
                            PlateNumber = "EF6XZXGOU1G728575",
                            RentCost = 307.98316771867701,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("80f35aec-967e-43c2-9db5-dce3656ccd79"),
                            FuelType = 3,
                            ModelId = new Guid("d9f2bff6-0afd-4146-b36f-da2882fa76a6"),
                            Odo = 25,
                            PlateNumber = "Y5AOWSJYOYQP39363",
                            RentCost = 1778.4557397505955,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("6f024be1-f0ae-4cf4-aee4-2d85025134a8"),
                            FuelType = 1,
                            ModelId = new Guid("d9f2bff6-0afd-4146-b36f-da2882fa76a6"),
                            Odo = 1859,
                            PlateNumber = "KNDCBU2MS5DE95983",
                            RentCost = 3322.86287147638,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f7ffaa45-fdbd-4480-aeab-49f7149e6d3b"),
                            FuelType = 1,
                            ModelId = new Guid("d9f2bff6-0afd-4146-b36f-da2882fa76a6"),
                            Odo = 8337,
                            PlateNumber = "F1KGIJNAB0D817627",
                            RentCost = 3055.0243245550155,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("cc14932a-85b1-49a2-b346-fde004561b85"),
                            FuelType = 3,
                            ModelId = new Guid("d9f2bff6-0afd-4146-b36f-da2882fa76a6"),
                            Odo = 6534,
                            PlateNumber = "ZY2ZVQSGB1SU49590",
                            RentCost = 1714.0347753904,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("b6908416-e012-4fba-b5f5-0922a979fe46"),
                            FuelType = 0,
                            ModelId = new Guid("d9f2bff6-0afd-4146-b36f-da2882fa76a6"),
                            Odo = 117,
                            PlateNumber = "YKNEUE5GD0F568315",
                            RentCost = 677.42381156206841,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("275e809e-77ae-4516-bbad-2c198e27860b"),
                            FuelType = 2,
                            ModelId = new Guid("64611803-bcef-4bf8-8132-fee42ebd2d55"),
                            Odo = 4093,
                            PlateNumber = "6R96YP2FJLE230861",
                            RentCost = 3480.5379752108256,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("29ee4b9d-d10e-4e7a-96c5-74d3b05d5ffc"),
                            FuelType = 1,
                            ModelId = new Guid("64611803-bcef-4bf8-8132-fee42ebd2d55"),
                            Odo = 2950,
                            PlateNumber = "ERHIOKVSH0PR99783",
                            RentCost = 2081.1253646544114,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("9d1c5ce7-7080-44ad-b8bb-e2f20b1ab524"),
                            FuelType = 1,
                            ModelId = new Guid("64611803-bcef-4bf8-8132-fee42ebd2d55"),
                            Odo = 1131,
                            PlateNumber = "HNERK1UEVRU165773",
                            RentCost = 916.31754917794001,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("b21be1c8-fa9e-451e-b5e1-4c5e7ccf8517"),
                            FuelType = 0,
                            ModelId = new Guid("64611803-bcef-4bf8-8132-fee42ebd2d55"),
                            Odo = 7678,
                            PlateNumber = "D21KCB6ASSOM51934",
                            RentCost = 564.21959656696993,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("a89007b2-a72d-4ffe-802e-dfebd037e0d5"),
                            FuelType = 1,
                            ModelId = new Guid("64611803-bcef-4bf8-8132-fee42ebd2d55"),
                            Odo = 1660,
                            PlateNumber = "NACPI9Z6I8WK85979",
                            RentCost = 2452.8924061816169,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("a03612bc-d777-4527-8cce-cc2d85d41481"),
                            FuelType = 1,
                            ModelId = new Guid("3d60ff96-9955-40f4-9fec-8101045a3365"),
                            Odo = 87,
                            PlateNumber = "D6C34JJDHTA074184",
                            RentCost = 3998.6831534849694,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("11826336-14cb-4814-9f97-cd07aee2792f"),
                            FuelType = 3,
                            ModelId = new Guid("3d60ff96-9955-40f4-9fec-8101045a3365"),
                            Odo = 9627,
                            PlateNumber = "7WYQ2UDCQ8S729873",
                            RentCost = 3064.0080884434601,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("37b04e06-b8d0-478c-8157-fb58e30c3a84"),
                            FuelType = 0,
                            ModelId = new Guid("3d60ff96-9955-40f4-9fec-8101045a3365"),
                            Odo = 629,
                            PlateNumber = "PAS3GT83M5CX18379",
                            RentCost = 2938.9659038900782,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("fec374ff-80d1-4b8d-bf5b-7db26a59e4c8"),
                            FuelType = 3,
                            ModelId = new Guid("3d60ff96-9955-40f4-9fec-8101045a3365"),
                            Odo = 9262,
                            PlateNumber = "9HEDY89B5DUJ38940",
                            RentCost = 3535.5021801880052,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("8d57fa56-2cfd-4350-a433-185dd2e67fad"),
                            FuelType = 0,
                            ModelId = new Guid("3d60ff96-9955-40f4-9fec-8101045a3365"),
                            Odo = 5095,
                            PlateNumber = "SX97FT3PTEKI43578",
                            RentCost = 3176.1325420089124,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("1c429dd3-4928-4c01-86b0-b47123fa3787"),
                            FuelType = 2,
                            ModelId = new Guid("3b07cda8-76d4-4989-bf35-07092bf9a35c"),
                            Odo = 4457,
                            PlateNumber = "P0M70OTPTMCG23261",
                            RentCost = 3346.8026703228852,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("00a04a8c-d571-48f4-a77e-f36b98aaf02d"),
                            FuelType = 3,
                            ModelId = new Guid("3b07cda8-76d4-4989-bf35-07092bf9a35c"),
                            Odo = 3535,
                            PlateNumber = "8LM6BBVXFPKG75996",
                            RentCost = 1490.7600270925757,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("802ed124-218d-40db-81b8-549a19580d71"),
                            FuelType = 1,
                            ModelId = new Guid("3b07cda8-76d4-4989-bf35-07092bf9a35c"),
                            Odo = 1937,
                            PlateNumber = "G98MNIRXSSD552574",
                            RentCost = 2968.5830755564234,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c6e96234-c30f-4563-af7c-d3071f01769d"),
                            FuelType = 1,
                            ModelId = new Guid("3b07cda8-76d4-4989-bf35-07092bf9a35c"),
                            Odo = 2120,
                            PlateNumber = "GWTQ17O1S8JM62754",
                            RentCost = 895.06267290926246,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("16a3e8a6-21ec-4c94-ab06-997218188151"),
                            FuelType = 0,
                            ModelId = new Guid("3b07cda8-76d4-4989-bf35-07092bf9a35c"),
                            Odo = 5200,
                            PlateNumber = "4XOSVZ2GEKVN96514",
                            RentCost = 859.47673476129614,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("f03e4e15-4e67-470e-ae11-48f1d99856ec"),
                            FuelType = 0,
                            ModelId = new Guid("fa5e1095-f059-4672-b7e8-cef2bb2c9098"),
                            Odo = 352,
                            PlateNumber = "1GDZ1E4NVWIU66260",
                            RentCost = 1271.4954962520183,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("e4843a6d-ecb2-45b2-a201-4d49abfc7405"),
                            FuelType = 0,
                            ModelId = new Guid("fa5e1095-f059-4672-b7e8-cef2bb2c9098"),
                            Odo = 2099,
                            PlateNumber = "CJZXC8XIR9TQ86688",
                            RentCost = 1471.7578467180101,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("070e1c1d-5c63-4f15-8239-80b60d084d23"),
                            FuelType = 2,
                            ModelId = new Guid("fa5e1095-f059-4672-b7e8-cef2bb2c9098"),
                            Odo = 6456,
                            PlateNumber = "RJH753WXW0O488661",
                            RentCost = 2641.6658812010351,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("4f08f1fe-18a8-46a5-bedd-ce757fbdce49"),
                            FuelType = 2,
                            ModelId = new Guid("fa5e1095-f059-4672-b7e8-cef2bb2c9098"),
                            Odo = 2717,
                            PlateNumber = "Y85IQQFL94PC64968",
                            RentCost = 2363.8227909476655,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("aa1a99e6-42ec-420e-9552-207205bce135"),
                            FuelType = 1,
                            ModelId = new Guid("fa5e1095-f059-4672-b7e8-cef2bb2c9098"),
                            Odo = 9119,
                            PlateNumber = "4161G6DYFIF479333",
                            RentCost = 2957.2057403765384,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("f8aa1bb2-a95d-4fa1-b66e-6219bcdc7158"),
                            FuelType = 3,
                            ModelId = new Guid("c148e18a-88b1-446d-be26-212243cdffb7"),
                            Odo = 4136,
                            PlateNumber = "QEKATN6SWNQ095269",
                            RentCost = 1536.7221430432478,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("13e4a11e-ead7-4322-9e5d-447075cbe09e"),
                            FuelType = 2,
                            ModelId = new Guid("c148e18a-88b1-446d-be26-212243cdffb7"),
                            Odo = 8027,
                            PlateNumber = "4BX68E7M46BE59910",
                            RentCost = 2022.9649864584626,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("76adfa35-1e4a-4742-b226-ddb0a5489e6b"),
                            FuelType = 0,
                            ModelId = new Guid("c148e18a-88b1-446d-be26-212243cdffb7"),
                            Odo = 8266,
                            PlateNumber = "JVQLK2K77RM077146",
                            RentCost = 255.09284488754147,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("a29a0576-f3ee-4062-9833-79c1855760d8"),
                            FuelType = 0,
                            ModelId = new Guid("c148e18a-88b1-446d-be26-212243cdffb7"),
                            Odo = 4107,
                            PlateNumber = "QJ2PS6RVZ6SE47959",
                            RentCost = 3094.8346422807881,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("3e5ba169-c5f7-45e7-926d-95edaab459fe"),
                            FuelType = 3,
                            ModelId = new Guid("c148e18a-88b1-446d-be26-212243cdffb7"),
                            Odo = 3671,
                            PlateNumber = "JVL9YYAMYTNK37515",
                            RentCost = 152.10833898870916,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("8db133cf-cc08-4003-aebf-37124a263145"),
                            FuelType = 0,
                            ModelId = new Guid("02b35ef0-01cd-4d8a-9b19-3f1e24ee155c"),
                            Odo = 7563,
                            PlateNumber = "QA2BQT1IB6PY95773",
                            RentCost = 3576.4826760206515,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("a7d3cc33-84b9-41d4-b53e-0706f76f634c"),
                            FuelType = 3,
                            ModelId = new Guid("02b35ef0-01cd-4d8a-9b19-3f1e24ee155c"),
                            Odo = 9676,
                            PlateNumber = "6PK84VTNN6UD35389",
                            RentCost = 2192.5344973847054,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("2a529d90-1905-49af-b54f-d849c15b5756"),
                            FuelType = 1,
                            ModelId = new Guid("02b35ef0-01cd-4d8a-9b19-3f1e24ee155c"),
                            Odo = 5892,
                            PlateNumber = "61CQ21PHJEQB84728",
                            RentCost = 2360.4493733266804,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("6a1f6d04-4b66-42e7-895c-ad8e8aeb0921"),
                            FuelType = 1,
                            ModelId = new Guid("02b35ef0-01cd-4d8a-9b19-3f1e24ee155c"),
                            Odo = 8499,
                            PlateNumber = "Q103IYPE8EYA92448",
                            RentCost = 3068.2537831923269,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("f0ec4117-2dbb-4c23-bd6f-a1a75da13431"),
                            FuelType = 1,
                            ModelId = new Guid("02b35ef0-01cd-4d8a-9b19-3f1e24ee155c"),
                            Odo = 8513,
                            PlateNumber = "7IKFO0ZXJFM771060",
                            RentCost = 825.68540331373833,
                            VehicleState = 0,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("74435be8-d980-41aa-8058-0dc5ec3bdb51"),
                            FuelType = 3,
                            ModelId = new Guid("acea193c-79ff-490a-b56b-3eea1c5c9216"),
                            Odo = 5875,
                            PlateNumber = "XG5EIPZGTWI238124",
                            RentCost = 3998.2196207984343,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("191eeaab-980c-4f31-ac56-1d3d6f8c584c"),
                            FuelType = 0,
                            ModelId = new Guid("acea193c-79ff-490a-b56b-3eea1c5c9216"),
                            Odo = 4653,
                            PlateNumber = "11TWF0IWB2LG27531",
                            RentCost = 2343.9848786960765,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("12649ecb-e49f-4e3d-a84a-94a88b8e26f7"),
                            FuelType = 3,
                            ModelId = new Guid("acea193c-79ff-490a-b56b-3eea1c5c9216"),
                            Odo = 9402,
                            PlateNumber = "V7ZAWQCYDVCV41550",
                            RentCost = 870.45853545001614,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f576de07-210c-40ce-bc20-8b75c9ed8438"),
                            FuelType = 0,
                            ModelId = new Guid("acea193c-79ff-490a-b56b-3eea1c5c9216"),
                            Odo = 1463,
                            PlateNumber = "DCEO3KOJOKE363826",
                            RentCost = 2070.9305944122107,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("8b41fba8-2fdb-4373-a846-04dda59c7711"),
                            FuelType = 2,
                            ModelId = new Guid("acea193c-79ff-490a-b56b-3eea1c5c9216"),
                            Odo = 5861,
                            PlateNumber = "BZ23HR9VTGBC34599",
                            RentCost = 3669.3605118855317,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("09a29a83-25ae-4193-b4c5-59ef66789322"),
                            FuelType = 3,
                            ModelId = new Guid("6c3295fd-474b-4269-84ac-cf60439fbbe9"),
                            Odo = 4604,
                            PlateNumber = "XL9UPYRS8RKE65356",
                            RentCost = 1939.1321656701823,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6300ca68-436b-4987-8d53-dce55688d7c7"),
                            FuelType = 2,
                            ModelId = new Guid("6c3295fd-474b-4269-84ac-cf60439fbbe9"),
                            Odo = 4893,
                            PlateNumber = "2B6RB34BA2AY93581",
                            RentCost = 2719.8724181549042,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("100b7e97-5060-4799-b69b-56b710148293"),
                            FuelType = 2,
                            ModelId = new Guid("6c3295fd-474b-4269-84ac-cf60439fbbe9"),
                            Odo = 5524,
                            PlateNumber = "1ME6RFPMNZOL61663",
                            RentCost = 3617.6797943490178,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("4e0cf3be-7f28-4461-bf51-a18d5d828df4"),
                            FuelType = 0,
                            ModelId = new Guid("6c3295fd-474b-4269-84ac-cf60439fbbe9"),
                            Odo = 7034,
                            PlateNumber = "JPPM8NPYM3JT25511",
                            RentCost = 2458.5095205294774,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("541cfb64-1f2e-4828-bb8b-ebb93b8e38a4"),
                            FuelType = 3,
                            ModelId = new Guid("6c3295fd-474b-4269-84ac-cf60439fbbe9"),
                            Odo = 5996,
                            PlateNumber = "W09P7SD5R0I517259",
                            RentCost = 1844.0447221336351,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("8bf6f7d8-a809-4fa1-8304-975400f9eb67"),
                            FuelType = 3,
                            ModelId = new Guid("98648004-1d56-44cf-ad84-24b8eeb6ed20"),
                            Odo = 9438,
                            PlateNumber = "91OWY9V8CSRY70479",
                            RentCost = 1557.5433097131938,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("2176da9e-ee14-472f-a64f-e1d029bddf40"),
                            FuelType = 1,
                            ModelId = new Guid("98648004-1d56-44cf-ad84-24b8eeb6ed20"),
                            Odo = 4967,
                            PlateNumber = "IKOCNJQTLKNH26513",
                            RentCost = 1899.9188987968473,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("6b692e15-d3a5-4b26-b713-a3703b270442"),
                            FuelType = 3,
                            ModelId = new Guid("98648004-1d56-44cf-ad84-24b8eeb6ed20"),
                            Odo = 2933,
                            PlateNumber = "FPD6I3890FYM24967",
                            RentCost = 3820.8066427564863,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("9f5f24e3-0c1f-497f-9eeb-fffbad523402"),
                            FuelType = 0,
                            ModelId = new Guid("98648004-1d56-44cf-ad84-24b8eeb6ed20"),
                            Odo = 5693,
                            PlateNumber = "Z8MTGIY7XAE714175",
                            RentCost = 1906.0088581891769,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("32579633-7b96-4a6e-bf0a-1bd82d361e08"),
                            FuelType = 1,
                            ModelId = new Guid("98648004-1d56-44cf-ad84-24b8eeb6ed20"),
                            Odo = 9390,
                            PlateNumber = "DDV3WGCVSBR621126",
                            RentCost = 1417.7165334625208,
                            VehicleState = 3,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("b98a3862-0eb4-49c3-b053-20fa1b3f2dd5"),
                            FuelType = 2,
                            ModelId = new Guid("1e62b078-df9d-4b57-b963-e071b9729821"),
                            Odo = 433,
                            PlateNumber = "AHKR838VEVJ412211",
                            RentCost = 2817.3936137682799,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("2d2b5b55-6ecb-473c-96e2-7ae460296aa2"),
                            FuelType = 2,
                            ModelId = new Guid("1e62b078-df9d-4b57-b963-e071b9729821"),
                            Odo = 4171,
                            PlateNumber = "G7ZHPFSD60EE56944",
                            RentCost = 3811.0146292437871,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("35ba11d0-5296-494e-87a9-bc2d7235989f"),
                            FuelType = 3,
                            ModelId = new Guid("1e62b078-df9d-4b57-b963-e071b9729821"),
                            Odo = 8355,
                            PlateNumber = "6T3OPWVCZHVI38238",
                            RentCost = 2702.4004507984887,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("5efe115d-aad0-489a-b8fe-8932890d602f"),
                            FuelType = 1,
                            ModelId = new Guid("1e62b078-df9d-4b57-b963-e071b9729821"),
                            Odo = 3312,
                            PlateNumber = "FZP5IEBVTLAI82925",
                            RentCost = 1262.4197680288567,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("b8f33ac9-6db3-4d80-bd7f-382ab431aea7"),
                            FuelType = 3,
                            ModelId = new Guid("1e62b078-df9d-4b57-b963-e071b9729821"),
                            Odo = 8297,
                            PlateNumber = "OG2AQI139YAQ84095",
                            RentCost = 1644.531347418837,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("712590f2-556d-41ea-b0c2-d861f670ab56"),
                            FuelType = 0,
                            ModelId = new Guid("8b66b146-b82e-4057-a343-a49e8fca8269"),
                            Odo = 5494,
                            PlateNumber = "016T9MGNI2JC52800",
                            RentCost = 853.62920187091504,
                            VehicleState = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("b10f4510-ef09-47f7-a716-693cacdd81d4"),
                            FuelType = 1,
                            ModelId = new Guid("8b66b146-b82e-4057-a343-a49e8fca8269"),
                            Odo = 235,
                            PlateNumber = "G63LOCUWIRK542308",
                            RentCost = 2562.6032086194441,
                            VehicleState = 2,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("05e48f36-49c6-4c7d-ae3b-1379d52760df"),
                            FuelType = 0,
                            ModelId = new Guid("8b66b146-b82e-4057-a343-a49e8fca8269"),
                            Odo = 2106,
                            PlateNumber = "MJ9LEJJ190C363219",
                            RentCost = 1978.9778969493589,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("ce41f512-af93-48d5-88a9-ee792ce4b1fb"),
                            FuelType = 3,
                            ModelId = new Guid("8b66b146-b82e-4057-a343-a49e8fca8269"),
                            Odo = 9495,
                            PlateNumber = "FD3IOFI2EZLX82949",
                            RentCost = 3116.9174316025751,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("a02370aa-aec7-4f60-8199-45befeb8c5e5"),
                            FuelType = 2,
                            ModelId = new Guid("8b66b146-b82e-4057-a343-a49e8fca8269"),
                            Odo = 4524,
                            PlateNumber = "RAH4VF65WVG084850",
                            RentCost = 3091.4233530135225,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("c9daee2b-e548-4465-a1d5-868e0325d1ea"),
                            FuelType = 0,
                            ModelId = new Guid("24a8daaf-8337-459d-b365-125bc0a5554f"),
                            Odo = 206,
                            PlateNumber = "8EFI4CZ7QGQC47785",
                            RentCost = 2704.5109348878077,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("961a7b80-183e-458f-b740-3dfb35cbda14"),
                            FuelType = 1,
                            ModelId = new Guid("24a8daaf-8337-459d-b365-125bc0a5554f"),
                            Odo = 6844,
                            PlateNumber = "O9R0N3SGXAEC72128",
                            RentCost = 3382.1115284662546,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("a6257dc7-7fac-4746-8a2d-3311a771a597"),
                            FuelType = 3,
                            ModelId = new Guid("24a8daaf-8337-459d-b365-125bc0a5554f"),
                            Odo = 2745,
                            PlateNumber = "UH2XA0IJUTON87619",
                            RentCost = 3567.7283860022517,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("0b749eb8-58a2-4d1f-95b1-64bc9fe5cba2"),
                            FuelType = 1,
                            ModelId = new Guid("24a8daaf-8337-459d-b365-125bc0a5554f"),
                            Odo = 598,
                            PlateNumber = "UQGOV0WMECOY43231",
                            RentCost = 3635.498519060814,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("d58b74a4-130e-4fcc-892e-6cc77c837547"),
                            FuelType = 3,
                            ModelId = new Guid("24a8daaf-8337-459d-b365-125bc0a5554f"),
                            Odo = 3686,
                            PlateNumber = "GENZIJ9XGVS219239",
                            RentCost = 3982.6413052588318,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("0c1c03dd-c19d-4195-aeca-04751c67cdd3"),
                            FuelType = 1,
                            ModelId = new Guid("d80c6e25-4af7-4c49-97ca-58fa1f3f9e39"),
                            Odo = 8822,
                            PlateNumber = "6QFZMH1VIYWO45604",
                            RentCost = 156.25753726330609,
                            VehicleState = 0,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("283a58de-39b7-4fb8-8473-f4f221dd4df0"),
                            FuelType = 2,
                            ModelId = new Guid("d80c6e25-4af7-4c49-97ca-58fa1f3f9e39"),
                            Odo = 6998,
                            PlateNumber = "1UYG6AI3IRFW60135",
                            RentCost = 1117.2577036075099,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("9257584f-c5c9-4fc0-b8da-d41df0cc98c9"),
                            FuelType = 0,
                            ModelId = new Guid("d80c6e25-4af7-4c49-97ca-58fa1f3f9e39"),
                            Odo = 5295,
                            PlateNumber = "EFT163ADLTBX33885",
                            RentCost = 353.13516957939532,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("0cdefbf4-0007-4d72-a701-ef7442fba331"),
                            FuelType = 1,
                            ModelId = new Guid("d80c6e25-4af7-4c49-97ca-58fa1f3f9e39"),
                            Odo = 6300,
                            PlateNumber = "M5008EQTD9KG23920",
                            RentCost = 2286.896023983863,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("db041257-e2e0-45f3-80f8-2acf79ddbb4e"),
                            FuelType = 0,
                            ModelId = new Guid("d80c6e25-4af7-4c49-97ca-58fa1f3f9e39"),
                            Odo = 8506,
                            PlateNumber = "1SMJGSJZ75NN15476",
                            RentCost = 662.81294688272567,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("ea678c2b-50a1-498b-94ed-84822e554630"),
                            FuelType = 2,
                            ModelId = new Guid("21408ca9-511f-4b9c-a360-ec6907d22884"),
                            Odo = 8364,
                            PlateNumber = "3E2SYOSV31GR19721",
                            RentCost = 2127.5530897941771,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("7a56b932-482b-4be8-b457-72152b7d6750"),
                            FuelType = 1,
                            ModelId = new Guid("21408ca9-511f-4b9c-a360-ec6907d22884"),
                            Odo = 3231,
                            PlateNumber = "W511B8D0O4TO84529",
                            RentCost = 1905.8158403506054,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("f74da237-00db-41b4-85ab-e3d3f8fd7588"),
                            FuelType = 1,
                            ModelId = new Guid("21408ca9-511f-4b9c-a360-ec6907d22884"),
                            Odo = 7539,
                            PlateNumber = "AT9NHB976RP118140",
                            RentCost = 3811.630273283693,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("e52600d2-ca3f-42d6-ad44-4f8efaba63ce"),
                            FuelType = 2,
                            ModelId = new Guid("21408ca9-511f-4b9c-a360-ec6907d22884"),
                            Odo = 3345,
                            PlateNumber = "JCCNE1X08SJ753431",
                            RentCost = 3746.8559841851256,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("7e446375-7c8f-47b2-aec3-0ea8da2aabc7"),
                            FuelType = 3,
                            ModelId = new Guid("21408ca9-511f-4b9c-a360-ec6907d22884"),
                            Odo = 525,
                            PlateNumber = "UMN84515PPIZ52258",
                            RentCost = 3286.7666630660756,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("1a71c3fe-eb53-4190-9c22-2c148bfae794"),
                            FuelType = 2,
                            ModelId = new Guid("3e8f4dc1-850d-4b56-9f79-eb3bfd8e2c1c"),
                            Odo = 5073,
                            PlateNumber = "6KZQ5VAEKLAR76955",
                            RentCost = 262.12617774841362,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("8438a8d4-8d54-46c4-a8e5-77e44b1a83c2"),
                            FuelType = 0,
                            ModelId = new Guid("3e8f4dc1-850d-4b56-9f79-eb3bfd8e2c1c"),
                            Odo = 1803,
                            PlateNumber = "Z5A8Q9VEQRKF20044",
                            RentCost = 1402.805627942111,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("dcdc4b9f-8a47-44e0-b89a-e01c9aef54e7"),
                            FuelType = 1,
                            ModelId = new Guid("3e8f4dc1-850d-4b56-9f79-eb3bfd8e2c1c"),
                            Odo = 2264,
                            PlateNumber = "8B7XM7E0WYER46268",
                            RentCost = 285.01109205374689,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("6c9000d7-1844-429e-b91f-eb7b601fbd87"),
                            FuelType = 1,
                            ModelId = new Guid("3e8f4dc1-850d-4b56-9f79-eb3bfd8e2c1c"),
                            Odo = 4916,
                            PlateNumber = "7B1OXNCUCEXT91506",
                            RentCost = 3819.9986544522762,
                            VehicleState = 1,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("9158f753-593e-4891-a51d-effeeeeba0d6"),
                            FuelType = 3,
                            ModelId = new Guid("3e8f4dc1-850d-4b56-9f79-eb3bfd8e2c1c"),
                            Odo = 442,
                            PlateNumber = "418K1IYURIT244086",
                            RentCost = 1669.3026033561518,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("8a618924-1763-4ab8-b731-08e8636176f4"),
                            FuelType = 2,
                            ModelId = new Guid("d36a0d38-25e1-44da-bfdc-2354fcee7ee3"),
                            Odo = 2843,
                            PlateNumber = "T1P1ADGN8VNO92612",
                            RentCost = 1285.5653724363683,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("606ebb88-ff1a-4f3a-b943-3fc95f82f9d9"),
                            FuelType = 2,
                            ModelId = new Guid("d36a0d38-25e1-44da-bfdc-2354fcee7ee3"),
                            Odo = 5880,
                            PlateNumber = "QVRME0GSBMN888418",
                            RentCost = 3696.333324100317,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("5fe10317-edac-442e-b4a0-5ff2e1df8395"),
                            FuelType = 0,
                            ModelId = new Guid("d36a0d38-25e1-44da-bfdc-2354fcee7ee3"),
                            Odo = 3860,
                            PlateNumber = "G4OJBPPKA8TH54762",
                            RentCost = 3711.4968648426157,
                            VehicleState = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("338cb5c2-06dc-407d-af4b-7fa2444ad8b4"),
                            FuelType = 1,
                            ModelId = new Guid("d36a0d38-25e1-44da-bfdc-2354fcee7ee3"),
                            Odo = 6010,
                            PlateNumber = "LFY26L7R3OSR56944",
                            RentCost = 2079.3187614863918,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("f1ba06f4-2d87-47c1-b79f-88e5ef7b5462"),
                            FuelType = 3,
                            ModelId = new Guid("d36a0d38-25e1-44da-bfdc-2354fcee7ee3"),
                            Odo = 6618,
                            PlateNumber = "WQHWKB2IJ0FQ83862",
                            RentCost = 1469.3248090655247,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("7d9a17f4-d652-4dc2-8179-6721b23c2af8"),
                            FuelType = 0,
                            ModelId = new Guid("5a57d85e-6ad8-4ad1-9365-6a88076d5da5"),
                            Odo = 6979,
                            PlateNumber = "LORG10MEA4WI18482",
                            RentCost = 2015.9225439134977,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("5f09567d-c009-4d6b-9b6b-36e338b2e95a"),
                            FuelType = 3,
                            ModelId = new Guid("5a57d85e-6ad8-4ad1-9365-6a88076d5da5"),
                            Odo = 8063,
                            PlateNumber = "GYYNAAGK3FVC84726",
                            RentCost = 203.04529528220894,
                            VehicleState = 1,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("d51c8fe2-2dff-4e32-87f5-d0b90b73e5bc"),
                            FuelType = 2,
                            ModelId = new Guid("5a57d85e-6ad8-4ad1-9365-6a88076d5da5"),
                            Odo = 3870,
                            PlateNumber = "83JHNUGHS7BC51688",
                            RentCost = 4000.370907766533,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("379f55f8-f99e-4a8b-a166-9bcf3d893a90"),
                            FuelType = 3,
                            ModelId = new Guid("5a57d85e-6ad8-4ad1-9365-6a88076d5da5"),
                            Odo = 7781,
                            PlateNumber = "IZE06PB7IMEB89726",
                            RentCost = 361.34840582819538,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("aeb377b7-d0d7-4c0a-afe1-45d0cf497b5f"),
                            FuelType = 2,
                            ModelId = new Guid("5a57d85e-6ad8-4ad1-9365-6a88076d5da5"),
                            Odo = 2055,
                            PlateNumber = "14HOGFMPIPCD19491",
                            RentCost = 392.18191301111636,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("fe039996-5784-4c34-9f3f-4273b993f6a9"),
                            FuelType = 1,
                            ModelId = new Guid("0db382d2-09a9-44a3-9751-a87c3d450cca"),
                            Odo = 1048,
                            PlateNumber = "IE02T4P275Y425203",
                            RentCost = 1004.6382049572555,
                            VehicleState = 1,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("923c440d-4747-4634-a850-5dcf1ab6576d"),
                            FuelType = 2,
                            ModelId = new Guid("0db382d2-09a9-44a3-9751-a87c3d450cca"),
                            Odo = 4958,
                            PlateNumber = "HUQXKOWPIKSL94472",
                            RentCost = 825.57098550474279,
                            VehicleState = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("26cb3558-d8e2-4c0a-91d1-2ebbd6531ccb"),
                            FuelType = 1,
                            ModelId = new Guid("0db382d2-09a9-44a3-9751-a87c3d450cca"),
                            Odo = 8124,
                            PlateNumber = "5SDY2GWF2AJV41262",
                            RentCost = 3218.3110492415767,
                            VehicleState = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("861e652f-542b-4cd4-9c58-7498f804e489"),
                            FuelType = 0,
                            ModelId = new Guid("0db382d2-09a9-44a3-9751-a87c3d450cca"),
                            Odo = 8635,
                            PlateNumber = "ZXHPJZ1TTOST16959",
                            RentCost = 3714.1675068798818,
                            VehicleState = 0,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("91b6110d-4cf2-4b6d-8da5-3cd698fc96f3"),
                            FuelType = 2,
                            ModelId = new Guid("0db382d2-09a9-44a3-9751-a87c3d450cca"),
                            Odo = 2342,
                            PlateNumber = "HNMFXHKSZ9EG24141",
                            RentCost = 2412.0835520622518,
                            VehicleState = 2,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("4b3bae51-ebec-4440-afe3-782376e92883"),
                            FuelType = 2,
                            ModelId = new Guid("d8c337a9-c89d-41e1-8c1f-4bee38c64ec1"),
                            Odo = 1293,
                            PlateNumber = "UBSE6ND1N0OJ80265",
                            RentCost = 245.64447733619608,
                            VehicleState = 3,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("af36fda8-c9ed-4702-a1eb-7c11bed80e31"),
                            FuelType = 1,
                            ModelId = new Guid("d8c337a9-c89d-41e1-8c1f-4bee38c64ec1"),
                            Odo = 9717,
                            PlateNumber = "3O9U0LR94GZX19330",
                            RentCost = 2643.6938244925045,
                            VehicleState = 1,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("f52b8eea-83fd-433e-9e10-e70050636df5"),
                            FuelType = 2,
                            ModelId = new Guid("d8c337a9-c89d-41e1-8c1f-4bee38c64ec1"),
                            Odo = 4820,
                            PlateNumber = "LSN2B5DR3MJA79693",
                            RentCost = 1229.3767607202458,
                            VehicleState = 2,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("5494750d-7d36-4a46-8924-991c4af88fb3"),
                            FuelType = 1,
                            ModelId = new Guid("d8c337a9-c89d-41e1-8c1f-4bee38c64ec1"),
                            Odo = 8452,
                            PlateNumber = "7DTHOIM9HQIB51188",
                            RentCost = 1025.3419589040475,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("b99c3f41-eed6-49fe-9fd9-910b1b044b46"),
                            FuelType = 0,
                            ModelId = new Guid("d8c337a9-c89d-41e1-8c1f-4bee38c64ec1"),
                            Odo = 9469,
                            PlateNumber = "D8VHNODCW5IY41344",
                            RentCost = 1400.1283854183669,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("b43407ab-13ab-40a3-9a7b-b4c431bf2540"),
                            FuelType = 3,
                            ModelId = new Guid("23b61a3c-ce67-4d25-8177-da9c7f8f43ae"),
                            Odo = 5977,
                            PlateNumber = "8R1X2R9OBSQ985070",
                            RentCost = 556.66163906470968,
                            VehicleState = 3,
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("4aa8e619-7693-46ec-9edb-cccc6212fc1e"),
                            FuelType = 0,
                            ModelId = new Guid("23b61a3c-ce67-4d25-8177-da9c7f8f43ae"),
                            Odo = 4891,
                            PlateNumber = "PH8KCTA47HKI81501",
                            RentCost = 2896.0013046541035,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("c58ee51b-162d-437e-9175-22ba1cee632e"),
                            FuelType = 1,
                            ModelId = new Guid("23b61a3c-ce67-4d25-8177-da9c7f8f43ae"),
                            Odo = 7264,
                            PlateNumber = "VWSDC5YA1CC987363",
                            RentCost = 1436.1891083990788,
                            VehicleState = 3,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("aac3d840-3487-47cc-92fa-c7374337df91"),
                            FuelType = 0,
                            ModelId = new Guid("23b61a3c-ce67-4d25-8177-da9c7f8f43ae"),
                            Odo = 2336,
                            PlateNumber = "87UMLUE9PNJF51643",
                            RentCost = 1136.0411825917686,
                            VehicleState = 2,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("917fd3d8-67f8-4004-9537-c32b91f98182"),
                            FuelType = 2,
                            ModelId = new Guid("23b61a3c-ce67-4d25-8177-da9c7f8f43ae"),
                            Odo = 697,
                            PlateNumber = "GYDQ3RR73NVX68952",
                            RentCost = 1507.0534633258433,
                            VehicleState = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("9a246027-7e5a-4ff7-b3de-a891b62c7b1c"),
                            FuelType = 2,
                            ModelId = new Guid("599a7abb-6894-4d72-98a4-26e359262fab"),
                            Odo = 6636,
                            PlateNumber = "4KGJSW43NGPV94925",
                            RentCost = 597.19496120008102,
                            VehicleState = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("18385aa3-b59d-43d7-afc4-ee33ee36e9e9"),
                            FuelType = 0,
                            ModelId = new Guid("599a7abb-6894-4d72-98a4-26e359262fab"),
                            Odo = 9069,
                            PlateNumber = "J8DXAE8VP3BI59616",
                            RentCost = 3943.2708959579354,
                            VehicleState = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("2434822d-f404-46ab-a670-d6cffff72f24"),
                            FuelType = 1,
                            ModelId = new Guid("599a7abb-6894-4d72-98a4-26e359262fab"),
                            Odo = 264,
                            PlateNumber = "RV1UTU87B0NO69655",
                            RentCost = 1040.3018346513875,
                            VehicleState = 0,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("729aa0f7-cdef-4372-880a-6484c61c2a11"),
                            FuelType = 0,
                            ModelId = new Guid("599a7abb-6894-4d72-98a4-26e359262fab"),
                            Odo = 368,
                            PlateNumber = "MQJO480UOVTI64860",
                            RentCost = 2620.4637397463116,
                            VehicleState = 3,
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("3f203177-c264-4511-99ce-e18f4b11edf4"),
                            FuelType = 0,
                            ModelId = new Guid("599a7abb-6894-4d72-98a4-26e359262fab"),
                            Odo = 182,
                            PlateNumber = "UIRZ0M1TX3AE71489",
                            RentCost = 3878.9434551483496,
                            VehicleState = 1,
                            VehicleType = 5
                        });
                });

            modelBuilder.Entity("DAL.Entities.VehicleClientHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleClientHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bf37bc1-59b2-4ccf-86c5-f0fdda7b1229"),
                            ClientId = new Guid("620e1326-bd16-474c-ba79-16356640f3a8"),
                            EndDate = new DateTime(2024, 5, 29, 13, 18, 3, 368, DateTimeKind.Utc).AddTicks(986),
                            StartDate = new DateTime(2024, 5, 31, 21, 32, 52, 224, DateTimeKind.Utc).AddTicks(9977),
                            VehicleId = new Guid("519768bc-91f2-43d7-9a51-2574ddeb3cb6")
                        },
                        new
                        {
                            Id = new Guid("fbd68544-a853-4de3-b819-e98ff7eb1062"),
                            ClientId = new Guid("620e1326-bd16-474c-ba79-16356640f3a8"),
                            EndDate = new DateTime(2024, 2, 6, 16, 8, 31, 669, DateTimeKind.Utc).AddTicks(4578),
                            StartDate = new DateTime(2023, 10, 12, 7, 20, 2, 705, DateTimeKind.Utc).AddTicks(6309),
                            VehicleId = new Guid("537b287f-affc-47dd-aa2b-0f71ea3de567")
                        },
                        new
                        {
                            Id = new Guid("3b35d673-bda9-4e1d-94a1-3ba3e49b7bf1"),
                            ClientId = new Guid("620e1326-bd16-474c-ba79-16356640f3a8"),
                            EndDate = new DateTime(2024, 2, 1, 23, 50, 8, 33, DateTimeKind.Utc).AddTicks(7330),
                            StartDate = new DateTime(2023, 10, 21, 16, 2, 2, 516, DateTimeKind.Utc).AddTicks(9011),
                            VehicleId = new Guid("6c9000d7-1844-429e-b91f-eb7b601fbd87")
                        },
                        new
                        {
                            Id = new Guid("b5031f7f-5f77-4542-af6d-71e2a6f27f5e"),
                            ClientId = new Guid("620e1326-bd16-474c-ba79-16356640f3a8"),
                            EndDate = new DateTime(2024, 1, 30, 19, 21, 25, 933, DateTimeKind.Utc).AddTicks(1547),
                            StartDate = new DateTime(2024, 4, 5, 20, 50, 53, 845, DateTimeKind.Utc).AddTicks(1850),
                            VehicleId = new Guid("c58ee51b-162d-437e-9175-22ba1cee632e")
                        },
                        new
                        {
                            Id = new Guid("7d6de991-b39b-4aea-a50a-00d3d372b3c7"),
                            ClientId = new Guid("620e1326-bd16-474c-ba79-16356640f3a8"),
                            EndDate = new DateTime(2024, 2, 8, 1, 44, 24, 645, DateTimeKind.Utc).AddTicks(8031),
                            StartDate = new DateTime(2024, 2, 14, 3, 48, 3, 74, DateTimeKind.Utc).AddTicks(3968),
                            VehicleId = new Guid("186522b6-26c7-4d66-ba7a-568231e772ef")
                        });
                });

            modelBuilder.Entity("DAL.Entities.ModelName", b =>
                {
                    b.HasOne("DAL.Entities.Manufacturer", "Manufacturer")
                        .WithMany("ModelNames")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DAL.Entities.Vehicle", b =>
                {
                    b.HasOne("DAL.Entities.ModelName", "ModelName")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelNameId");

                    b.Navigation("ModelName");
                });

            modelBuilder.Entity("DAL.Entities.VehicleClientHistory", b =>
                {
                    b.HasOne("DAL.Entities.Client", "Client")
                        .WithMany("VehicleClientHistory")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleClientHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DAL.Entities.Client", b =>
                {
                    b.Navigation("VehicleClientHistory");
                });

            modelBuilder.Entity("DAL.Entities.Manufacturer", b =>
                {
                    b.Navigation("ModelNames");
                });

            modelBuilder.Entity("DAL.Entities.ModelName", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DAL.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleClientHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
